
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point s_axi_awid[4] s_axi_awid[4] -type PI PI
add mapped point s_axi_awid[3] s_axi_awid[3] -type PI PI
add mapped point s_axi_awid[2] s_axi_awid[2] -type PI PI
add mapped point s_axi_awid[1] s_axi_awid[1] -type PI PI
add mapped point s_axi_awid[0] s_axi_awid[0] -type PI PI
add mapped point s_axi_awaddr[31] s_axi_awaddr[31] -type PI PI
add mapped point s_axi_awaddr[30] s_axi_awaddr[30] -type PI PI
add mapped point s_axi_awaddr[29] s_axi_awaddr[29] -type PI PI
add mapped point s_axi_awaddr[28] s_axi_awaddr[28] -type PI PI
add mapped point s_axi_awaddr[27] s_axi_awaddr[27] -type PI PI
add mapped point s_axi_awaddr[26] s_axi_awaddr[26] -type PI PI
add mapped point s_axi_awaddr[25] s_axi_awaddr[25] -type PI PI
add mapped point s_axi_awaddr[24] s_axi_awaddr[24] -type PI PI
add mapped point s_axi_awaddr[23] s_axi_awaddr[23] -type PI PI
add mapped point s_axi_awaddr[22] s_axi_awaddr[22] -type PI PI
add mapped point s_axi_awaddr[21] s_axi_awaddr[21] -type PI PI
add mapped point s_axi_awaddr[20] s_axi_awaddr[20] -type PI PI
add mapped point s_axi_awaddr[19] s_axi_awaddr[19] -type PI PI
add mapped point s_axi_awaddr[18] s_axi_awaddr[18] -type PI PI
add mapped point s_axi_awaddr[17] s_axi_awaddr[17] -type PI PI
add mapped point s_axi_awaddr[16] s_axi_awaddr[16] -type PI PI
add mapped point s_axi_awaddr[15] s_axi_awaddr[15] -type PI PI
add mapped point s_axi_awaddr[14] s_axi_awaddr[14] -type PI PI
add mapped point s_axi_awaddr[13] s_axi_awaddr[13] -type PI PI
add mapped point s_axi_awaddr[12] s_axi_awaddr[12] -type PI PI
add mapped point s_axi_awaddr[11] s_axi_awaddr[11] -type PI PI
add mapped point s_axi_awaddr[10] s_axi_awaddr[10] -type PI PI
add mapped point s_axi_awaddr[9] s_axi_awaddr[9] -type PI PI
add mapped point s_axi_awaddr[8] s_axi_awaddr[8] -type PI PI
add mapped point s_axi_awaddr[7] s_axi_awaddr[7] -type PI PI
add mapped point s_axi_awaddr[6] s_axi_awaddr[6] -type PI PI
add mapped point s_axi_awaddr[5] s_axi_awaddr[5] -type PI PI
add mapped point s_axi_awaddr[4] s_axi_awaddr[4] -type PI PI
add mapped point s_axi_awaddr[3] s_axi_awaddr[3] -type PI PI
add mapped point s_axi_awaddr[2] s_axi_awaddr[2] -type PI PI
add mapped point s_axi_awaddr[1] s_axi_awaddr[1] -type PI PI
add mapped point s_axi_awaddr[0] s_axi_awaddr[0] -type PI PI
add mapped point s_axi_awlen[7] s_axi_awlen[7] -type PI PI
add mapped point s_axi_awlen[6] s_axi_awlen[6] -type PI PI
add mapped point s_axi_awlen[5] s_axi_awlen[5] -type PI PI
add mapped point s_axi_awlen[4] s_axi_awlen[4] -type PI PI
add mapped point s_axi_awlen[3] s_axi_awlen[3] -type PI PI
add mapped point s_axi_awlen[2] s_axi_awlen[2] -type PI PI
add mapped point s_axi_awlen[1] s_axi_awlen[1] -type PI PI
add mapped point s_axi_awlen[0] s_axi_awlen[0] -type PI PI
add mapped point s_axi_awsize[2] s_axi_awsize[2] -type PI PI
add mapped point s_axi_awsize[1] s_axi_awsize[1] -type PI PI
add mapped point s_axi_awsize[0] s_axi_awsize[0] -type PI PI
add mapped point s_axi_awburst[1] s_axi_awburst[1] -type PI PI
add mapped point s_axi_awburst[0] s_axi_awburst[0] -type PI PI
add mapped point s_axi_awlock s_axi_awlock -type PI PI
add mapped point s_axi_awcache[3] s_axi_awcache[3] -type PI PI
add mapped point s_axi_awcache[2] s_axi_awcache[2] -type PI PI
add mapped point s_axi_awcache[1] s_axi_awcache[1] -type PI PI
add mapped point s_axi_awcache[0] s_axi_awcache[0] -type PI PI
add mapped point s_axi_awprot[2] s_axi_awprot[2] -type PI PI
add mapped point s_axi_awprot[1] s_axi_awprot[1] -type PI PI
add mapped point s_axi_awprot[0] s_axi_awprot[0] -type PI PI
add mapped point s_axi_awqos[3] s_axi_awqos[3] -type PI PI
add mapped point s_axi_awqos[2] s_axi_awqos[2] -type PI PI
add mapped point s_axi_awqos[1] s_axi_awqos[1] -type PI PI
add mapped point s_axi_awqos[0] s_axi_awqos[0] -type PI PI
add mapped point s_axi_awregion[3] s_axi_awregion[3] -type PI PI
add mapped point s_axi_awregion[2] s_axi_awregion[2] -type PI PI
add mapped point s_axi_awregion[1] s_axi_awregion[1] -type PI PI
add mapped point s_axi_awregion[0] s_axi_awregion[0] -type PI PI
add mapped point s_axi_awvalid s_axi_awvalid -type PI PI
add mapped point s_axi_wdata[31] s_axi_wdata[31] -type PI PI
add mapped point s_axi_wdata[30] s_axi_wdata[30] -type PI PI
add mapped point s_axi_wdata[29] s_axi_wdata[29] -type PI PI
add mapped point s_axi_wdata[28] s_axi_wdata[28] -type PI PI
add mapped point s_axi_wdata[27] s_axi_wdata[27] -type PI PI
add mapped point s_axi_wdata[26] s_axi_wdata[26] -type PI PI
add mapped point s_axi_wdata[25] s_axi_wdata[25] -type PI PI
add mapped point s_axi_wdata[24] s_axi_wdata[24] -type PI PI
add mapped point s_axi_wdata[23] s_axi_wdata[23] -type PI PI
add mapped point s_axi_wdata[22] s_axi_wdata[22] -type PI PI
add mapped point s_axi_wdata[21] s_axi_wdata[21] -type PI PI
add mapped point s_axi_wdata[20] s_axi_wdata[20] -type PI PI
add mapped point s_axi_wdata[19] s_axi_wdata[19] -type PI PI
add mapped point s_axi_wdata[18] s_axi_wdata[18] -type PI PI
add mapped point s_axi_wdata[17] s_axi_wdata[17] -type PI PI
add mapped point s_axi_wdata[16] s_axi_wdata[16] -type PI PI
add mapped point s_axi_wdata[15] s_axi_wdata[15] -type PI PI
add mapped point s_axi_wdata[14] s_axi_wdata[14] -type PI PI
add mapped point s_axi_wdata[13] s_axi_wdata[13] -type PI PI
add mapped point s_axi_wdata[12] s_axi_wdata[12] -type PI PI
add mapped point s_axi_wdata[11] s_axi_wdata[11] -type PI PI
add mapped point s_axi_wdata[10] s_axi_wdata[10] -type PI PI
add mapped point s_axi_wdata[9] s_axi_wdata[9] -type PI PI
add mapped point s_axi_wdata[8] s_axi_wdata[8] -type PI PI
add mapped point s_axi_wdata[7] s_axi_wdata[7] -type PI PI
add mapped point s_axi_wdata[6] s_axi_wdata[6] -type PI PI
add mapped point s_axi_wdata[5] s_axi_wdata[5] -type PI PI
add mapped point s_axi_wdata[4] s_axi_wdata[4] -type PI PI
add mapped point s_axi_wdata[3] s_axi_wdata[3] -type PI PI
add mapped point s_axi_wdata[2] s_axi_wdata[2] -type PI PI
add mapped point s_axi_wdata[1] s_axi_wdata[1] -type PI PI
add mapped point s_axi_wdata[0] s_axi_wdata[0] -type PI PI
add mapped point s_axi_wstrb[3] s_axi_wstrb[3] -type PI PI
add mapped point s_axi_wstrb[2] s_axi_wstrb[2] -type PI PI
add mapped point s_axi_wstrb[1] s_axi_wstrb[1] -type PI PI
add mapped point s_axi_wstrb[0] s_axi_wstrb[0] -type PI PI
add mapped point s_axi_wlast s_axi_wlast -type PI PI
add mapped point s_axi_wvalid s_axi_wvalid -type PI PI
add mapped point s_axi_bready s_axi_bready -type PI PI
add mapped point s_axi_arid[4] s_axi_arid[4] -type PI PI
add mapped point s_axi_arid[3] s_axi_arid[3] -type PI PI
add mapped point s_axi_arid[2] s_axi_arid[2] -type PI PI
add mapped point s_axi_arid[1] s_axi_arid[1] -type PI PI
add mapped point s_axi_arid[0] s_axi_arid[0] -type PI PI
add mapped point s_axi_araddr[31] s_axi_araddr[31] -type PI PI
add mapped point s_axi_araddr[30] s_axi_araddr[30] -type PI PI
add mapped point s_axi_araddr[29] s_axi_araddr[29] -type PI PI
add mapped point s_axi_araddr[28] s_axi_araddr[28] -type PI PI
add mapped point s_axi_araddr[27] s_axi_araddr[27] -type PI PI
add mapped point s_axi_araddr[26] s_axi_araddr[26] -type PI PI
add mapped point s_axi_araddr[25] s_axi_araddr[25] -type PI PI
add mapped point s_axi_araddr[24] s_axi_araddr[24] -type PI PI
add mapped point s_axi_araddr[23] s_axi_araddr[23] -type PI PI
add mapped point s_axi_araddr[22] s_axi_araddr[22] -type PI PI
add mapped point s_axi_araddr[21] s_axi_araddr[21] -type PI PI
add mapped point s_axi_araddr[20] s_axi_araddr[20] -type PI PI
add mapped point s_axi_araddr[19] s_axi_araddr[19] -type PI PI
add mapped point s_axi_araddr[18] s_axi_araddr[18] -type PI PI
add mapped point s_axi_araddr[17] s_axi_araddr[17] -type PI PI
add mapped point s_axi_araddr[16] s_axi_araddr[16] -type PI PI
add mapped point s_axi_araddr[15] s_axi_araddr[15] -type PI PI
add mapped point s_axi_araddr[14] s_axi_araddr[14] -type PI PI
add mapped point s_axi_araddr[13] s_axi_araddr[13] -type PI PI
add mapped point s_axi_araddr[12] s_axi_araddr[12] -type PI PI
add mapped point s_axi_araddr[11] s_axi_araddr[11] -type PI PI
add mapped point s_axi_araddr[10] s_axi_araddr[10] -type PI PI
add mapped point s_axi_araddr[9] s_axi_araddr[9] -type PI PI
add mapped point s_axi_araddr[8] s_axi_araddr[8] -type PI PI
add mapped point s_axi_araddr[7] s_axi_araddr[7] -type PI PI
add mapped point s_axi_araddr[6] s_axi_araddr[6] -type PI PI
add mapped point s_axi_araddr[5] s_axi_araddr[5] -type PI PI
add mapped point s_axi_araddr[4] s_axi_araddr[4] -type PI PI
add mapped point s_axi_araddr[3] s_axi_araddr[3] -type PI PI
add mapped point s_axi_araddr[2] s_axi_araddr[2] -type PI PI
add mapped point s_axi_araddr[1] s_axi_araddr[1] -type PI PI
add mapped point s_axi_araddr[0] s_axi_araddr[0] -type PI PI
add mapped point s_axi_arlen[7] s_axi_arlen[7] -type PI PI
add mapped point s_axi_arlen[6] s_axi_arlen[6] -type PI PI
add mapped point s_axi_arlen[5] s_axi_arlen[5] -type PI PI
add mapped point s_axi_arlen[4] s_axi_arlen[4] -type PI PI
add mapped point s_axi_arlen[3] s_axi_arlen[3] -type PI PI
add mapped point s_axi_arlen[2] s_axi_arlen[2] -type PI PI
add mapped point s_axi_arlen[1] s_axi_arlen[1] -type PI PI
add mapped point s_axi_arlen[0] s_axi_arlen[0] -type PI PI
add mapped point s_axi_arsize[2] s_axi_arsize[2] -type PI PI
add mapped point s_axi_arsize[1] s_axi_arsize[1] -type PI PI
add mapped point s_axi_arsize[0] s_axi_arsize[0] -type PI PI
add mapped point s_axi_arburst[1] s_axi_arburst[1] -type PI PI
add mapped point s_axi_arburst[0] s_axi_arburst[0] -type PI PI
add mapped point s_axi_arlock s_axi_arlock -type PI PI
add mapped point s_axi_arcache[3] s_axi_arcache[3] -type PI PI
add mapped point s_axi_arcache[2] s_axi_arcache[2] -type PI PI
add mapped point s_axi_arcache[1] s_axi_arcache[1] -type PI PI
add mapped point s_axi_arcache[0] s_axi_arcache[0] -type PI PI
add mapped point s_axi_arprot[2] s_axi_arprot[2] -type PI PI
add mapped point s_axi_arprot[1] s_axi_arprot[1] -type PI PI
add mapped point s_axi_arprot[0] s_axi_arprot[0] -type PI PI
add mapped point s_axi_arqos[3] s_axi_arqos[3] -type PI PI
add mapped point s_axi_arqos[2] s_axi_arqos[2] -type PI PI
add mapped point s_axi_arqos[1] s_axi_arqos[1] -type PI PI
add mapped point s_axi_arqos[0] s_axi_arqos[0] -type PI PI
add mapped point s_axi_arregion[3] s_axi_arregion[3] -type PI PI
add mapped point s_axi_arregion[2] s_axi_arregion[2] -type PI PI
add mapped point s_axi_arregion[1] s_axi_arregion[1] -type PI PI
add mapped point s_axi_arregion[0] s_axi_arregion[0] -type PI PI
add mapped point s_axi_arvalid s_axi_arvalid -type PI PI
add mapped point s_axi_rready s_axi_rready -type PI PI

//output ports
add mapped point s_axi_awready s_axi_awready -type PO PO
add mapped point s_axi_wready s_axi_wready -type PO PO
add mapped point s_axi_bid[4] s_axi_bid[4] -type PO PO
add mapped point s_axi_bid[3] s_axi_bid[3] -type PO PO
add mapped point s_axi_bid[2] s_axi_bid[2] -type PO PO
add mapped point s_axi_bid[1] s_axi_bid[1] -type PO PO
add mapped point s_axi_bid[0] s_axi_bid[0] -type PO PO
add mapped point s_axi_bresp[1] s_axi_bresp[1] -type PO PO
add mapped point s_axi_bresp[0] s_axi_bresp[0] -type PO PO
add mapped point s_axi_bvalid s_axi_bvalid -type PO PO
add mapped point s_axi_arready s_axi_arready -type PO PO
add mapped point s_axi_rid[4] s_axi_rid[4] -type PO PO
add mapped point s_axi_rid[3] s_axi_rid[3] -type PO PO
add mapped point s_axi_rid[2] s_axi_rid[2] -type PO PO
add mapped point s_axi_rid[1] s_axi_rid[1] -type PO PO
add mapped point s_axi_rid[0] s_axi_rid[0] -type PO PO
add mapped point s_axi_rdata[31] s_axi_rdata[31] -type PO PO
add mapped point s_axi_rdata[30] s_axi_rdata[30] -type PO PO
add mapped point s_axi_rdata[29] s_axi_rdata[29] -type PO PO
add mapped point s_axi_rdata[28] s_axi_rdata[28] -type PO PO
add mapped point s_axi_rdata[27] s_axi_rdata[27] -type PO PO
add mapped point s_axi_rdata[26] s_axi_rdata[26] -type PO PO
add mapped point s_axi_rdata[25] s_axi_rdata[25] -type PO PO
add mapped point s_axi_rdata[24] s_axi_rdata[24] -type PO PO
add mapped point s_axi_rdata[23] s_axi_rdata[23] -type PO PO
add mapped point s_axi_rdata[22] s_axi_rdata[22] -type PO PO
add mapped point s_axi_rdata[21] s_axi_rdata[21] -type PO PO
add mapped point s_axi_rdata[20] s_axi_rdata[20] -type PO PO
add mapped point s_axi_rdata[19] s_axi_rdata[19] -type PO PO
add mapped point s_axi_rdata[18] s_axi_rdata[18] -type PO PO
add mapped point s_axi_rdata[17] s_axi_rdata[17] -type PO PO
add mapped point s_axi_rdata[16] s_axi_rdata[16] -type PO PO
add mapped point s_axi_rdata[15] s_axi_rdata[15] -type PO PO
add mapped point s_axi_rdata[14] s_axi_rdata[14] -type PO PO
add mapped point s_axi_rdata[13] s_axi_rdata[13] -type PO PO
add mapped point s_axi_rdata[12] s_axi_rdata[12] -type PO PO
add mapped point s_axi_rdata[11] s_axi_rdata[11] -type PO PO
add mapped point s_axi_rdata[10] s_axi_rdata[10] -type PO PO
add mapped point s_axi_rdata[9] s_axi_rdata[9] -type PO PO
add mapped point s_axi_rdata[8] s_axi_rdata[8] -type PO PO
add mapped point s_axi_rdata[7] s_axi_rdata[7] -type PO PO
add mapped point s_axi_rdata[6] s_axi_rdata[6] -type PO PO
add mapped point s_axi_rdata[5] s_axi_rdata[5] -type PO PO
add mapped point s_axi_rdata[4] s_axi_rdata[4] -type PO PO
add mapped point s_axi_rdata[3] s_axi_rdata[3] -type PO PO
add mapped point s_axi_rdata[2] s_axi_rdata[2] -type PO PO
add mapped point s_axi_rdata[1] s_axi_rdata[1] -type PO PO
add mapped point s_axi_rdata[0] s_axi_rdata[0] -type PO PO
add mapped point s_axi_rresp[1] s_axi_rresp[1] -type PO PO
add mapped point s_axi_rresp[0] s_axi_rresp[0] -type PO PO
add mapped point s_axi_rlast s_axi_rlast -type PO PO
add mapped point s_axi_rvalid s_axi_rvalid -type PO PO

//inout ports




//Sequential Pins
add mapped point u_axi_ctrl/ar_addr_reg[0]/q u_axi_ctrl_ar_addr_reg_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[1]/q u_axi_ctrl_ar_addr_reg_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[2]/q u_axi_ctrl_ar_addr_reg_reg[2]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[3]/q u_axi_ctrl_ar_addr_reg_reg[3]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[4]/q u_axi_ctrl_ar_addr_reg_reg[4]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[5]/q u_axi_ctrl_ar_addr_reg_reg[5]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[6]/q u_axi_ctrl_ar_addr_reg_reg[6]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[7]/q u_axi_ctrl_ar_addr_reg_reg[7]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[8]/q u_axi_ctrl_ar_addr_reg_reg[8]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[9]/q u_axi_ctrl_ar_addr_reg_reg[9]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[10]/q u_axi_ctrl_ar_addr_reg_reg[10]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_addr_reg[11]/q u_axi_ctrl_ar_addr_reg_reg[11]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_len_reg[0]/q u_axi_ctrl_ar_len_reg_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_len_reg[1]/q u_axi_ctrl_ar_len_reg_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_len_reg[2]/q u_axi_ctrl_ar_len_reg_reg[2]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_len_reg[3]/q u_axi_ctrl_ar_len_reg_reg[3]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_len_reg[4]/q u_axi_ctrl_ar_len_reg_reg[4]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_len_reg[5]/q u_axi_ctrl_ar_len_reg_reg[5]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_len_reg[6]/q u_axi_ctrl_ar_len_reg_reg[6]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_len_reg[7]/q u_axi_ctrl_ar_len_reg_reg[7]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_size_reg[0]/q u_axi_ctrl_ar_size_reg_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_size_reg[1]/q u_axi_ctrl_ar_size_reg_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/ar_size_reg[2]/q u_axi_ctrl_ar_size_reg_reg[2]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[0]/q u_axi_ctrl_aw_addr_reg_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[1]/q u_axi_ctrl_aw_addr_reg_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[2]/q u_axi_ctrl_aw_addr_reg_reg[2]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[3]/q u_axi_ctrl_aw_addr_reg_reg[3]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[4]/q u_axi_ctrl_aw_addr_reg_reg[4]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[5]/q u_axi_ctrl_aw_addr_reg_reg[5]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[6]/q u_axi_ctrl_aw_addr_reg_reg[6]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[7]/q u_axi_ctrl_aw_addr_reg_reg[7]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[8]/q u_axi_ctrl_aw_addr_reg_reg[8]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[9]/q u_axi_ctrl_aw_addr_reg_reg[9]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[10]/q u_axi_ctrl_aw_addr_reg_reg[10]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_addr_reg[11]/q u_axi_ctrl_aw_addr_reg_reg[11]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_size_reg[0]/q u_axi_ctrl_aw_size_reg_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_size_reg[1]/q u_axi_ctrl_aw_size_reg_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/aw_size_reg[2]/q u_axi_ctrl_aw_size_reg_reg[2]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_count[0]/q u_axi_ctrl_r_count_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_count[1]/q u_axi_ctrl_r_count_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_count[2]/q u_axi_ctrl_r_count_reg[2]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_count[3]/q u_axi_ctrl_r_count_reg[3]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_count[4]/q u_axi_ctrl_r_count_reg[4]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_count[5]/q u_axi_ctrl_r_count_reg[5]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_count[6]/q u_axi_ctrl_r_count_reg[6]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_count[7]/q u_axi_ctrl_r_count_reg[7]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_state[0]/q u_axi_ctrl_r_state_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/r_state[1]/q u_axi_ctrl_r_state_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_arready/q u_axi_ctrl_s_axi_arready_reg/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_awready/q u_axi_ctrl_s_axi_awready_reg/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_bid[0]/q u_axi_ctrl_s_axi_bid_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_bid[1]/q u_axi_ctrl_s_axi_bid_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_bid[2]/q u_axi_ctrl_s_axi_bid_reg[2]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_bid[3]/q u_axi_ctrl_s_axi_bid_reg[3]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_bid[4]/q u_axi_ctrl_s_axi_bid_reg[4]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_bvalid/q u_axi_ctrl_s_axi_bvalid_reg/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_rid[0]/q u_axi_ctrl_s_axi_rid_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_rid[1]/q u_axi_ctrl_s_axi_rid_reg[1]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_rid[2]/q u_axi_ctrl_s_axi_rid_reg[2]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_rid[3]/q u_axi_ctrl_s_axi_rid_reg[3]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_rid[4]/q u_axi_ctrl_s_axi_rid_reg[4]/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_rlast/q u_axi_ctrl_s_axi_rlast_reg/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_rvalid/q u_axi_ctrl_s_axi_rvalid_reg/QN -type DFF DFF
add mapped point u_axi_ctrl/s_axi_wready/q u_axi_ctrl_s_axi_wready_reg/QN -type DFF DFF
add mapped point u_axi_ctrl/w_state[0]/q u_axi_ctrl_w_state_reg[0]/QN -type DFF DFF
add mapped point u_axi_ctrl/w_state[1]/q u_axi_ctrl_w_state_reg[1]/QN -type DFF DFF



//Black Boxes
add mapped point u_sram_macro/u_sram_macro u_sram_macro_u_sram_macro -type BBOX BBOX



//Empty Modules as Blackboxes
