
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Apr  4 2026 15:11:44 +07 (Apr  4 2026 08:11:44 UTC)

// Verification Directory fv/Adder32 

module Adder32(iClk, iA, iB, oS);
  input iClk;
  input [31:0] iA, iB;
  output [31:0] oS;
  wire iClk;
  wire [31:0] iA, iB;
  wire [31:0] oS;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, add_8_11_n_0;
  wire add_8_11_n_1, add_8_11_n_34, add_8_11_n_35, add_8_11_n_37,
       add_8_11_n_38, add_8_11_n_40, add_8_11_n_41, add_8_11_n_43;
  wire add_8_11_n_44, add_8_11_n_46, add_8_11_n_47, add_8_11_n_49,
       add_8_11_n_50, add_8_11_n_52, add_8_11_n_53, add_8_11_n_55;
  wire add_8_11_n_56, add_8_11_n_58, add_8_11_n_59, add_8_11_n_61,
       add_8_11_n_62, add_8_11_n_64, add_8_11_n_65, add_8_11_n_67;
  wire add_8_11_n_68, add_8_11_n_70, add_8_11_n_71, add_8_11_n_73,
       add_8_11_n_74, add_8_11_n_76, add_8_11_n_77, add_8_11_n_79;
  wire add_8_11_n_80, add_8_11_n_82, add_8_11_n_83, add_8_11_n_85,
       add_8_11_n_86, add_8_11_n_88, add_8_11_n_89, add_8_11_n_91;
  wire add_8_11_n_92, add_8_11_n_94, add_8_11_n_95, add_8_11_n_97,
       add_8_11_n_98, add_8_11_n_100, add_8_11_n_101, add_8_11_n_103;
  wire add_8_11_n_104, add_8_11_n_106, add_8_11_n_107, add_8_11_n_109,
       add_8_11_n_110, add_8_11_n_112, add_8_11_n_113, add_8_11_n_115;
  wire add_8_11_n_116, add_8_11_n_118, add_8_11_n_119, add_8_11_n_121,
       n_95, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218;
  DFFHQx4_ASAP7_75t_R \oS_reg[11] (.CLK (iClk), .D (n_208), .Q
       (oS[11]));
  DFFHQx4_ASAP7_75t_R \oS_reg[2] (.CLK (iClk), .D (n_217), .Q (oS[2]));
  DFFHQx4_ASAP7_75t_R \oS_reg[9] (.CLK (iClk), .D (n_210), .Q (oS[9]));
  DFFHQx4_ASAP7_75t_R \oS_reg[30] (.CLK (iClk), .D (n_189), .Q
       (oS[30]));
  DFFHQx4_ASAP7_75t_R \oS_reg[28] (.CLK (iClk), .D (n_191), .Q
       (oS[28]));
  DFFHQx4_ASAP7_75t_R \oS_reg[24] (.CLK (iClk), .D (n_195), .Q
       (oS[24]));
  DFFHQx4_ASAP7_75t_R \oS_reg[16] (.CLK (iClk), .D (n_203), .Q
       (oS[16]));
  DFFHQx4_ASAP7_75t_R \oS_reg[0] (.CLK (iClk), .D (n_95), .Q (oS[0]));
  DFFHQx4_ASAP7_75t_R \oS_reg[15] (.CLK (iClk), .D (n_204), .Q
       (oS[15]));
  DFFHQx4_ASAP7_75t_R \oS_reg[23] (.CLK (iClk), .D (n_196), .Q
       (oS[23]));
  DFFHQx4_ASAP7_75t_R \oS_reg[14] (.CLK (iClk), .D (n_205), .Q
       (oS[14]));
  DFFHQx4_ASAP7_75t_R \oS_reg[13] (.CLK (iClk), .D (n_206), .Q
       (oS[13]));
  DFFHQx4_ASAP7_75t_R \oS_reg[27] (.CLK (iClk), .D (n_192), .Q
       (oS[27]));
  DFFHQx4_ASAP7_75t_R \oS_reg[22] (.CLK (iClk), .D (n_197), .Q
       (oS[22]));
  DFFHQx4_ASAP7_75t_R \oS_reg[12] (.CLK (iClk), .D (n_207), .Q
       (oS[12]));
  DFFHQx4_ASAP7_75t_R \oS_reg[10] (.CLK (iClk), .D (n_209), .Q
       (oS[10]));
  DFFHQx4_ASAP7_75t_R \oS_reg[17] (.CLK (iClk), .D (n_202), .Q
       (oS[17]));
  DFFHQx4_ASAP7_75t_R \oS_reg[31] (.CLK (iClk), .D (n_188), .Q
       (oS[31]));
  DFFHQx4_ASAP7_75t_R \oS_reg[1] (.CLK (iClk), .D (n_218), .Q (oS[1]));
  DFFHQx4_ASAP7_75t_R \oS_reg[29] (.CLK (iClk), .D (n_190), .Q
       (oS[29]));
  DFFHQx4_ASAP7_75t_R \oS_reg[26] (.CLK (iClk), .D (n_193), .Q
       (oS[26]));
  DFFHQx4_ASAP7_75t_R \oS_reg[20] (.CLK (iClk), .D (n_199), .Q
       (oS[20]));
  DFFHQx4_ASAP7_75t_R \oS_reg[8] (.CLK (iClk), .D (n_211), .Q (oS[8]));
  DFFHQx4_ASAP7_75t_R \oS_reg[7] (.CLK (iClk), .D (n_212), .Q (oS[7]));
  DFFHQx4_ASAP7_75t_R \oS_reg[19] (.CLK (iClk), .D (n_200), .Q
       (oS[19]));
  DFFHQx4_ASAP7_75t_R \oS_reg[6] (.CLK (iClk), .D (n_213), .Q (oS[6]));
  DFFHQx4_ASAP7_75t_R \oS_reg[5] (.CLK (iClk), .D (n_214), .Q (oS[5]));
  DFFHQx4_ASAP7_75t_R \oS_reg[25] (.CLK (iClk), .D (n_194), .Q
       (oS[25]));
  DFFHQx4_ASAP7_75t_R \oS_reg[18] (.CLK (iClk), .D (n_201), .Q
       (oS[18]));
  DFFHQx4_ASAP7_75t_R \oS_reg[4] (.CLK (iClk), .D (n_215), .Q (oS[4]));
  DFFHQx4_ASAP7_75t_R \oS_reg[3] (.CLK (iClk), .D (n_216), .Q (oS[3]));
  DFFHQx4_ASAP7_75t_R \oS_reg[21] (.CLK (iClk), .D (n_198), .Q
       (oS[21]));
  MAJIxp5_ASAP7_75t_R add_8_11_g752__6260(.A (add_8_11_n_119), .B
       (iB[30]), .C (iA[30]), .Y (add_8_11_n_121));
  INVx1_ASAP7_75t_R add_8_11_g754(.A (add_8_11_n_118), .Y
       (add_8_11_n_119));
  MAJIxp5_ASAP7_75t_R add_8_11_g755__8428(.A (add_8_11_n_116), .B
       (iB[29]), .C (iA[29]), .Y (add_8_11_n_118));
  INVx1_ASAP7_75t_R add_8_11_g757(.A (add_8_11_n_115), .Y
       (add_8_11_n_116));
  MAJIxp5_ASAP7_75t_R add_8_11_g758__6783(.A (add_8_11_n_113), .B
       (iB[28]), .C (iA[28]), .Y (add_8_11_n_115));
  INVx1_ASAP7_75t_R add_8_11_g760(.A (add_8_11_n_112), .Y
       (add_8_11_n_113));
  MAJIxp5_ASAP7_75t_R add_8_11_g761__1617(.A (add_8_11_n_110), .B
       (iB[27]), .C (iA[27]), .Y (add_8_11_n_112));
  INVx1_ASAP7_75t_R add_8_11_g763(.A (add_8_11_n_109), .Y
       (add_8_11_n_110));
  MAJIxp5_ASAP7_75t_R add_8_11_g764__1705(.A (add_8_11_n_107), .B
       (iB[26]), .C (iA[26]), .Y (add_8_11_n_109));
  INVx1_ASAP7_75t_R add_8_11_g766(.A (add_8_11_n_106), .Y
       (add_8_11_n_107));
  MAJIxp5_ASAP7_75t_R add_8_11_g767__8246(.A (add_8_11_n_104), .B
       (iB[25]), .C (iA[25]), .Y (add_8_11_n_106));
  INVx1_ASAP7_75t_R add_8_11_g769(.A (add_8_11_n_103), .Y
       (add_8_11_n_104));
  MAJIxp5_ASAP7_75t_R add_8_11_g770__6131(.A (add_8_11_n_101), .B
       (iB[24]), .C (iA[24]), .Y (add_8_11_n_103));
  INVx1_ASAP7_75t_R add_8_11_g772(.A (add_8_11_n_100), .Y
       (add_8_11_n_101));
  MAJIxp5_ASAP7_75t_R add_8_11_g773__5115(.A (add_8_11_n_98), .B
       (iB[23]), .C (iA[23]), .Y (add_8_11_n_100));
  INVx1_ASAP7_75t_R add_8_11_g775(.A (add_8_11_n_97), .Y
       (add_8_11_n_98));
  MAJIxp5_ASAP7_75t_R add_8_11_g776__4733(.A (add_8_11_n_95), .B
       (iB[22]), .C (iA[22]), .Y (add_8_11_n_97));
  INVx1_ASAP7_75t_R add_8_11_g778(.A (add_8_11_n_94), .Y
       (add_8_11_n_95));
  MAJIxp5_ASAP7_75t_R add_8_11_g779__9315(.A (add_8_11_n_92), .B
       (iB[21]), .C (iA[21]), .Y (add_8_11_n_94));
  INVx1_ASAP7_75t_R add_8_11_g781(.A (add_8_11_n_91), .Y
       (add_8_11_n_92));
  MAJIxp5_ASAP7_75t_R add_8_11_g782__2883(.A (add_8_11_n_89), .B
       (iB[20]), .C (iA[20]), .Y (add_8_11_n_91));
  INVx1_ASAP7_75t_R add_8_11_g784(.A (add_8_11_n_88), .Y
       (add_8_11_n_89));
  MAJIxp5_ASAP7_75t_R add_8_11_g785__1666(.A (add_8_11_n_86), .B
       (iB[19]), .C (iA[19]), .Y (add_8_11_n_88));
  INVx1_ASAP7_75t_R add_8_11_g787(.A (add_8_11_n_85), .Y
       (add_8_11_n_86));
  MAJIxp5_ASAP7_75t_R add_8_11_g788__6417(.A (add_8_11_n_83), .B
       (iB[18]), .C (iA[18]), .Y (add_8_11_n_85));
  INVx1_ASAP7_75t_R add_8_11_g790(.A (add_8_11_n_82), .Y
       (add_8_11_n_83));
  MAJIxp5_ASAP7_75t_R add_8_11_g791__2398(.A (add_8_11_n_80), .B
       (iB[17]), .C (iA[17]), .Y (add_8_11_n_82));
  INVx1_ASAP7_75t_R add_8_11_g793(.A (add_8_11_n_79), .Y
       (add_8_11_n_80));
  MAJIxp5_ASAP7_75t_R add_8_11_g794__6260(.A (add_8_11_n_77), .B
       (iB[16]), .C (iA[16]), .Y (add_8_11_n_79));
  INVx1_ASAP7_75t_R add_8_11_g796(.A (add_8_11_n_76), .Y
       (add_8_11_n_77));
  MAJIxp5_ASAP7_75t_R add_8_11_g797__8428(.A (add_8_11_n_74), .B
       (iB[15]), .C (iA[15]), .Y (add_8_11_n_76));
  INVx1_ASAP7_75t_R add_8_11_g799(.A (add_8_11_n_73), .Y
       (add_8_11_n_74));
  MAJIxp5_ASAP7_75t_R add_8_11_g800__6783(.A (add_8_11_n_71), .B
       (iB[14]), .C (iA[14]), .Y (add_8_11_n_73));
  INVx1_ASAP7_75t_R add_8_11_g802(.A (add_8_11_n_70), .Y
       (add_8_11_n_71));
  MAJIxp5_ASAP7_75t_R add_8_11_g803__1617(.A (add_8_11_n_68), .B
       (iB[13]), .C (iA[13]), .Y (add_8_11_n_70));
  INVx1_ASAP7_75t_R add_8_11_g805(.A (add_8_11_n_67), .Y
       (add_8_11_n_68));
  MAJIxp5_ASAP7_75t_R add_8_11_g806__1705(.A (add_8_11_n_65), .B
       (iB[12]), .C (iA[12]), .Y (add_8_11_n_67));
  INVx1_ASAP7_75t_R add_8_11_g808(.A (add_8_11_n_64), .Y
       (add_8_11_n_65));
  MAJIxp5_ASAP7_75t_R add_8_11_g809__8246(.A (add_8_11_n_62), .B
       (iB[11]), .C (iA[11]), .Y (add_8_11_n_64));
  INVx1_ASAP7_75t_R add_8_11_g811(.A (add_8_11_n_61), .Y
       (add_8_11_n_62));
  MAJIxp5_ASAP7_75t_R add_8_11_g812__6131(.A (add_8_11_n_59), .B
       (iB[10]), .C (iA[10]), .Y (add_8_11_n_61));
  INVx1_ASAP7_75t_R add_8_11_g814(.A (add_8_11_n_58), .Y
       (add_8_11_n_59));
  MAJIxp5_ASAP7_75t_R add_8_11_g815__5115(.A (add_8_11_n_56), .B
       (iB[9]), .C (iA[9]), .Y (add_8_11_n_58));
  INVx1_ASAP7_75t_R add_8_11_g817(.A (add_8_11_n_55), .Y
       (add_8_11_n_56));
  MAJIxp5_ASAP7_75t_R add_8_11_g818__4733(.A (add_8_11_n_53), .B
       (iB[8]), .C (iA[8]), .Y (add_8_11_n_55));
  INVx1_ASAP7_75t_R add_8_11_g820(.A (add_8_11_n_52), .Y
       (add_8_11_n_53));
  MAJIxp5_ASAP7_75t_R add_8_11_g821__9315(.A (add_8_11_n_50), .B
       (iB[7]), .C (iA[7]), .Y (add_8_11_n_52));
  INVx1_ASAP7_75t_R add_8_11_g823(.A (add_8_11_n_49), .Y
       (add_8_11_n_50));
  MAJIxp5_ASAP7_75t_R add_8_11_g824__2883(.A (add_8_11_n_47), .B
       (iB[6]), .C (iA[6]), .Y (add_8_11_n_49));
  INVx1_ASAP7_75t_R add_8_11_g826(.A (add_8_11_n_46), .Y
       (add_8_11_n_47));
  MAJIxp5_ASAP7_75t_R add_8_11_g827__1666(.A (add_8_11_n_44), .B
       (iB[5]), .C (iA[5]), .Y (add_8_11_n_46));
  INVx1_ASAP7_75t_R add_8_11_g829(.A (add_8_11_n_43), .Y
       (add_8_11_n_44));
  MAJIxp5_ASAP7_75t_R add_8_11_g830__6417(.A (add_8_11_n_41), .B
       (iB[4]), .C (iA[4]), .Y (add_8_11_n_43));
  INVx1_ASAP7_75t_R add_8_11_g832(.A (add_8_11_n_40), .Y
       (add_8_11_n_41));
  MAJIxp5_ASAP7_75t_R add_8_11_g833__2398(.A (add_8_11_n_38), .B
       (iB[3]), .C (iA[3]), .Y (add_8_11_n_40));
  INVx1_ASAP7_75t_R add_8_11_g835(.A (add_8_11_n_37), .Y
       (add_8_11_n_38));
  MAJIxp5_ASAP7_75t_R add_8_11_g836__6260(.A (add_8_11_n_35), .B
       (iB[2]), .C (iA[2]), .Y (add_8_11_n_37));
  INVx1_ASAP7_75t_R add_8_11_g838(.A (add_8_11_n_34), .Y
       (add_8_11_n_35));
  MAJIxp5_ASAP7_75t_R add_8_11_g839__8428(.A (add_8_11_n_0), .B
       (iB[1]), .C (iA[1]), .Y (add_8_11_n_34));
  OA21x2_ASAP7_75t_R add_8_11_g840__5526(.A1 (iB[0]), .A2 (iA[0]), .B
       (add_8_11_n_1), .Y (n_95));
  INVx1_ASAP7_75t_R add_8_11_g872(.A (add_8_11_n_1), .Y (add_8_11_n_0));
  NAND2xp33_ASAP7_75t_R add_8_11_g873__2802(.A (iB[0]), .B (iA[0]), .Y
       (add_8_11_n_1));
  FAx1_ASAP7_75t_R g2(.A (iB[31]), .B (iA[31]), .CI (add_8_11_n_121),
       .CON (UNCONNECTED), .SN (n_188));
  FAx1_ASAP7_75t_R g874(.A (iB[30]), .B (iA[30]), .CI (add_8_11_n_118),
       .CON (UNCONNECTED0), .SN (n_189));
  FAx1_ASAP7_75t_R g875(.A (iB[29]), .B (iA[29]), .CI (add_8_11_n_115),
       .CON (UNCONNECTED1), .SN (n_190));
  FAx1_ASAP7_75t_R g876(.A (iB[28]), .B (iA[28]), .CI (add_8_11_n_112),
       .CON (UNCONNECTED2), .SN (n_191));
  FAx1_ASAP7_75t_R g877(.A (iB[27]), .B (iA[27]), .CI (add_8_11_n_109),
       .CON (UNCONNECTED3), .SN (n_192));
  FAx1_ASAP7_75t_R g878(.A (iB[26]), .B (iA[26]), .CI (add_8_11_n_106),
       .CON (UNCONNECTED4), .SN (n_193));
  FAx1_ASAP7_75t_R g879(.A (iB[25]), .B (iA[25]), .CI (add_8_11_n_103),
       .CON (UNCONNECTED5), .SN (n_194));
  FAx1_ASAP7_75t_R g880(.A (iB[24]), .B (iA[24]), .CI (add_8_11_n_100),
       .CON (UNCONNECTED6), .SN (n_195));
  FAx1_ASAP7_75t_R g881(.A (iB[23]), .B (iA[23]), .CI (add_8_11_n_97),
       .CON (UNCONNECTED7), .SN (n_196));
  FAx1_ASAP7_75t_R g882(.A (iB[22]), .B (iA[22]), .CI (add_8_11_n_94),
       .CON (UNCONNECTED8), .SN (n_197));
  FAx1_ASAP7_75t_R g883(.A (iB[21]), .B (iA[21]), .CI (add_8_11_n_91),
       .CON (UNCONNECTED9), .SN (n_198));
  FAx1_ASAP7_75t_R g884(.A (iB[20]), .B (iA[20]), .CI (add_8_11_n_88),
       .CON (UNCONNECTED10), .SN (n_199));
  FAx1_ASAP7_75t_R g885(.A (iB[19]), .B (iA[19]), .CI (add_8_11_n_85),
       .CON (UNCONNECTED11), .SN (n_200));
  FAx1_ASAP7_75t_R g886(.A (iB[18]), .B (iA[18]), .CI (add_8_11_n_82),
       .CON (UNCONNECTED12), .SN (n_201));
  FAx1_ASAP7_75t_R g887(.A (iB[17]), .B (iA[17]), .CI (add_8_11_n_79),
       .CON (UNCONNECTED13), .SN (n_202));
  FAx1_ASAP7_75t_R g888(.A (iB[16]), .B (iA[16]), .CI (add_8_11_n_76),
       .CON (UNCONNECTED14), .SN (n_203));
  FAx1_ASAP7_75t_R g889(.A (iB[15]), .B (iA[15]), .CI (add_8_11_n_73),
       .CON (UNCONNECTED15), .SN (n_204));
  FAx1_ASAP7_75t_R g890(.A (iB[14]), .B (iA[14]), .CI (add_8_11_n_70),
       .CON (UNCONNECTED16), .SN (n_205));
  FAx1_ASAP7_75t_R g891(.A (iB[13]), .B (iA[13]), .CI (add_8_11_n_67),
       .CON (UNCONNECTED17), .SN (n_206));
  FAx1_ASAP7_75t_R g892(.A (iB[12]), .B (iA[12]), .CI (add_8_11_n_64),
       .CON (UNCONNECTED18), .SN (n_207));
  FAx1_ASAP7_75t_R g893(.A (iB[11]), .B (iA[11]), .CI (add_8_11_n_61),
       .CON (UNCONNECTED19), .SN (n_208));
  FAx1_ASAP7_75t_R g894(.A (iB[10]), .B (iA[10]), .CI (add_8_11_n_58),
       .CON (UNCONNECTED20), .SN (n_209));
  FAx1_ASAP7_75t_R g895(.A (iB[9]), .B (iA[9]), .CI (add_8_11_n_55),
       .CON (UNCONNECTED21), .SN (n_210));
  FAx1_ASAP7_75t_R g896(.A (iB[8]), .B (iA[8]), .CI (add_8_11_n_52),
       .CON (UNCONNECTED22), .SN (n_211));
  FAx1_ASAP7_75t_R g897(.A (iB[7]), .B (iA[7]), .CI (add_8_11_n_49),
       .CON (UNCONNECTED23), .SN (n_212));
  FAx1_ASAP7_75t_R g898(.A (iB[6]), .B (iA[6]), .CI (add_8_11_n_46),
       .CON (UNCONNECTED24), .SN (n_213));
  FAx1_ASAP7_75t_R g899(.A (iB[5]), .B (iA[5]), .CI (add_8_11_n_43),
       .CON (UNCONNECTED25), .SN (n_214));
  FAx1_ASAP7_75t_R g900(.A (iB[4]), .B (iA[4]), .CI (add_8_11_n_40),
       .CON (UNCONNECTED26), .SN (n_215));
  FAx1_ASAP7_75t_R g901(.A (iB[3]), .B (iA[3]), .CI (add_8_11_n_37),
       .CON (UNCONNECTED27), .SN (n_216));
  FAx1_ASAP7_75t_R g902(.A (iB[2]), .B (iA[2]), .CI (add_8_11_n_34),
       .CON (UNCONNECTED28), .SN (n_217));
  FAx1_ASAP7_75t_R g903(.A (add_8_11_n_1), .B (iB[1]), .CI (iA[1]),
       .CON (UNCONNECTED29), .SN (n_218));
endmodule

