
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Mar 30 2026 15:31:30 +07 (Mar 30 2026 08:31:30 UTC)

// Verification Directory fv/Adder32 

module Adder32(iClk, iA, iB, oS);
  input iClk;
  input [31:0] iA, iB;
  output [31:0] oS;
  wire iClk;
  wire [31:0] iA, iB;
  wire [31:0] oS;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, add_8_11_n_674;
  wire add_8_11_n_677, add_8_11_n_680, add_8_11_n_683, add_8_11_n_686,
       add_8_11_n_689, add_8_11_n_692, add_8_11_n_695, add_8_11_n_698;
  wire add_8_11_n_701, add_8_11_n_704, add_8_11_n_707, add_8_11_n_710,
       add_8_11_n_713, add_8_11_n_716, add_8_11_n_719, add_8_11_n_722;
  wire add_8_11_n_725, add_8_11_n_728, add_8_11_n_731, add_8_11_n_734,
       add_8_11_n_737, add_8_11_n_740, add_8_11_n_743, add_8_11_n_746;
  wire add_8_11_n_749, add_8_11_n_752, add_8_11_n_755, add_8_11_n_758,
       add_8_11_n_762, add_8_11_n_770, add_8_11_n_772, add_8_11_n_774;
  wire add_8_11_n_776, add_8_11_n_784, add_8_11_n_786, add_8_11_n_788,
       add_8_11_n_790, add_8_11_n_798, add_8_11_n_807, add_8_11_n_812;
  wire add_8_11_n_820, add_8_11_n_822, add_8_11_n_827, add_8_11_n_829,
       add_8_11_n_837, add_8_11_n_841, add_8_11_n_842, add_8_11_n_843;
  wire add_8_11_n_844, add_8_11_n_845, add_8_11_n_846, add_8_11_n_847,
       add_8_11_n_848, add_8_11_n_849, add_8_11_n_850, add_8_11_n_851;
  wire add_8_11_n_858, add_8_11_n_861, add_8_11_n_868, add_8_11_n_873,
       add_8_11_n_880, add_8_11_n_881, add_8_11_n_882, add_8_11_n_883;
  wire add_8_11_n_884, add_8_11_n_886, add_8_11_n_887, add_8_11_n_890,
       add_8_11_n_893, add_8_11_n_894, add_8_11_n_895, add_8_11_n_896;
  wire add_8_11_n_897, add_8_11_n_898, add_8_11_n_901, n_134, n_135,
       n_136, n_138, n_141;
  wire n_142, n_143, n_145, n_146, n_150, n_151, n_153, n_154;
  wire n_157, n_158, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177;
  DFFHQNx1_ASAP7_75t_L \oS_reg[31] (.CLK (iClk), .D (n_134), .QN
       (oS[31]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[30] (.CLK (iClk), .D (n_168), .QN
       (oS[30]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[28] (.CLK (iClk), .D (n_163), .QN
       (oS[28]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[24] (.CLK (iClk), .D (n_164), .QN
       (oS[24]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[16] (.CLK (iClk), .D (n_162), .QN
       (oS[16]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[0] (.CLK (iClk), .D (n_177), .QN
       (oS[0]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[15] (.CLK (iClk), .D (n_135), .QN
       (oS[15]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[23] (.CLK (iClk), .D (n_136), .QN
       (oS[23]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[14] (.CLK (iClk), .D (n_165), .QN
       (oS[14]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[13] (.CLK (iClk), .D (n_138), .QN
       (oS[13]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[27] (.CLK (iClk), .D (n_141), .QN
       (oS[27]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[22] (.CLK (iClk), .D (n_166), .QN
       (oS[22]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[12] (.CLK (iClk), .D (n_167), .QN
       (oS[12]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[11] (.CLK (iClk), .D (n_142), .QN
       (oS[11]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[21] (.CLK (iClk), .D (n_143), .QN
       (oS[21]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[10] (.CLK (iClk), .D (n_161), .QN
       (oS[10]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[9] (.CLK (iClk), .D (n_160), .QN
       (oS[9]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[29] (.CLK (iClk), .D (n_146), .QN
       (oS[29]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[26] (.CLK (iClk), .D (n_169), .QN
       (oS[26]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[20] (.CLK (iClk), .D (n_170), .QN
       (oS[20]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[8] (.CLK (iClk), .D (n_171), .QN
       (oS[8]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[7] (.CLK (iClk), .D (n_150), .QN
       (oS[7]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[19] (.CLK (iClk), .D (n_151), .QN
       (oS[19]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[6] (.CLK (iClk), .D (n_172), .QN
       (oS[6]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[5] (.CLK (iClk), .D (n_153), .QN
       (oS[5]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[25] (.CLK (iClk), .D (n_154), .QN
       (oS[25]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[18] (.CLK (iClk), .D (n_173), .QN
       (oS[18]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[4] (.CLK (iClk), .D (n_174), .QN
       (oS[4]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[3] (.CLK (iClk), .D (n_157), .QN
       (oS[3]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[17] (.CLK (iClk), .D (n_158), .QN
       (oS[17]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[2] (.CLK (iClk), .D (n_175), .QN
       (oS[2]));
  DFFHQNx1_ASAP7_75t_L \oS_reg[1] (.CLK (iClk), .D (n_145), .QN
       (oS[1]));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1031__5107(.A (add_8_11_n_677), .B
       (iB[30]), .C (iA[30]), .Y (add_8_11_n_674));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1033__4319(.A1 (add_8_11_n_850), .A2
       (add_8_11_n_680), .B (add_8_11_n_886), .Y (add_8_11_n_677));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1035__5526(.A (add_8_11_n_683), .B
       (iB[28]), .C (iA[28]), .Y (add_8_11_n_680));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1037__3680(.A1 (add_8_11_n_849), .A2
       (add_8_11_n_686), .B (add_8_11_n_897), .Y (add_8_11_n_683));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1039__2802(.A (add_8_11_n_689), .B
       (iB[26]), .C (iA[26]), .Y (add_8_11_n_686));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1041__5122(.A1 (add_8_11_n_880), .A2
       (add_8_11_n_692), .B (add_8_11_n_898), .Y (add_8_11_n_689));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1043__7098(.A (add_8_11_n_695), .B
       (iB[24]), .C (iA[24]), .Y (add_8_11_n_692));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1045__1881(.A1 (add_8_11_n_842), .A2
       (add_8_11_n_698), .B (add_8_11_n_895), .Y (add_8_11_n_695));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1047__7482(.A (add_8_11_n_701), .B
       (iB[22]), .C (iA[22]), .Y (add_8_11_n_698));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1049__6161(.A1 (add_8_11_n_841), .A2
       (add_8_11_n_704), .B (add_8_11_n_887), .Y (add_8_11_n_701));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1051__9945(.A (add_8_11_n_707), .B
       (iB[20]), .C (iA[20]), .Y (add_8_11_n_704));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1053__2346(.A1 (add_8_11_n_848), .A2
       (add_8_11_n_710), .B (add_8_11_n_894), .Y (add_8_11_n_707));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1055__7410(.A (add_8_11_n_713), .B
       (iB[18]), .C (iA[18]), .Y (add_8_11_n_710));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1057__5477(.A1 (add_8_11_n_844), .A2
       (add_8_11_n_716), .B (add_8_11_n_890), .Y (add_8_11_n_713));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1059__5107(.A (add_8_11_n_719), .B
       (iB[16]), .C (iA[16]), .Y (add_8_11_n_716));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1061__4319(.A1 (add_8_11_n_843), .A2
       (add_8_11_n_722), .B (add_8_11_n_861), .Y (add_8_11_n_719));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1063__5526(.A (add_8_11_n_725), .B
       (iB[14]), .C (iA[14]), .Y (add_8_11_n_722));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1065__3680(.A1 (add_8_11_n_845), .A2
       (add_8_11_n_728), .B (add_8_11_n_868), .Y (add_8_11_n_725));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1067__2802(.A (add_8_11_n_731), .B
       (iB[12]), .C (iA[12]), .Y (add_8_11_n_728));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1069__5122(.A1 (add_8_11_n_884), .A2
       (add_8_11_n_734), .B (add_8_11_n_858), .Y (add_8_11_n_731));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1071__7098(.A (add_8_11_n_737), .B
       (iB[10]), .C (iA[10]), .Y (add_8_11_n_734));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1073__1881(.A1 (add_8_11_n_883), .A2
       (add_8_11_n_740), .B (add_8_11_n_901), .Y (add_8_11_n_737));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1075__7482(.A (add_8_11_n_743), .B
       (iB[8]), .C (iA[8]), .Y (add_8_11_n_740));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1077__6161(.A1 (add_8_11_n_847), .A2
       (add_8_11_n_746), .B (add_8_11_n_896), .Y (add_8_11_n_743));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1079__9945(.A (add_8_11_n_749), .B
       (iB[6]), .C (iA[6]), .Y (add_8_11_n_746));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1081__2346(.A1 (add_8_11_n_881), .A2
       (add_8_11_n_752), .B (add_8_11_n_873), .Y (add_8_11_n_749));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1083__7410(.A (add_8_11_n_755), .B
       (iB[4]), .C (iA[4]), .Y (add_8_11_n_752));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1085__5477(.A1 (add_8_11_n_846), .A2
       (add_8_11_n_758), .B (add_8_11_n_851), .Y (add_8_11_n_755));
  MAJIxp5_ASAP7_75t_SRAM add_8_11_g1087__5107(.A (add_8_11_n_762), .B
       (iB[2]), .C (iA[2]), .Y (add_8_11_n_758));
  OAI21xp33_ASAP7_75t_SL add_8_11_g1090__8428(.A1 (add_8_11_n_882), .A2
       (n_176), .B (add_8_11_n_893), .Y (add_8_11_n_762));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1093__3680(.A1 (iA[15]), .A2
       (iB[15]), .B (add_8_11_n_843), .Y (add_8_11_n_770));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1094__1617(.A1 (iA[7]), .A2 (iB[7]),
       .B (add_8_11_n_847), .Y (add_8_11_n_772));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1095__2802(.A1 (iA[17]), .A2
       (iB[17]), .B (add_8_11_n_844), .Y (add_8_11_n_774));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1096__1705(.A1 (iA[5]), .A2 (iB[5]),
       .B (add_8_11_n_881), .Y (add_8_11_n_776));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1099__7098(.A1 (iA[9]), .A2 (iB[9]),
       .B (add_8_11_n_883), .Y (add_8_11_n_784));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1100__6131(.A1 (iA[1]), .A2 (iB[1]),
       .B (add_8_11_n_882), .Y (add_8_11_n_786));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1101__1881(.A1 (iA[29]), .A2
       (iB[29]), .B (add_8_11_n_850), .Y (add_8_11_n_788));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1102__5115(.A1 (iA[3]), .A2 (iB[3]),
       .B (add_8_11_n_846), .Y (add_8_11_n_790));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1105__6161(.A1 (iA[27]), .A2
       (iB[27]), .B (add_8_11_n_849), .Y (add_8_11_n_798));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1109__2346(.A1 (iA[25]), .A2
       (iB[25]), .B (add_8_11_n_880), .Y (add_8_11_n_807));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1111__7410(.A1 (iA[23]), .A2
       (iB[23]), .B (add_8_11_n_842), .Y (add_8_11_n_812));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1114__2398(.A1 (iA[11]), .A2
       (iB[11]), .B (add_8_11_n_884), .Y (add_8_11_n_820));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1115__5107(.A1 (iA[21]), .A2
       (iB[21]), .B (add_8_11_n_841), .Y (add_8_11_n_822));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1117__4319(.A1 (iA[13]), .A2
       (iB[13]), .B (add_8_11_n_845), .Y (add_8_11_n_827));
  AOI21xp33_ASAP7_75t_SL add_8_11_g1118__8428(.A1 (iA[19]), .A2
       (iB[19]), .B (add_8_11_n_848), .Y (add_8_11_n_829));
  XOR2xp5_ASAP7_75t_SRAM add_8_11_g1121__3680(.A (iB[31]), .B (iA[31]),
       .Y (add_8_11_n_837));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1123__2802(.A (iB[3]), .B (iA[3]),
       .Y (add_8_11_n_851));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1124__1705(.A (iB[21]), .B (iA[21]),
       .Y (add_8_11_n_841));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1125__5122(.A (iB[23]), .B (iA[23]),
       .Y (add_8_11_n_842));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1126__8246(.A (iB[11]), .B (iA[11]),
       .Y (add_8_11_n_858));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1127__7098(.A (iB[15]), .B (iA[15]),
       .Y (add_8_11_n_861));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1128__6131(.A (iB[15]), .B (iA[15]),
       .Y (add_8_11_n_843));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1129__1881(.A (iB[17]), .B (iA[17]),
       .Y (add_8_11_n_844));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1130__5115(.A (iB[13]), .B (iA[13]),
       .Y (add_8_11_n_845));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1131__7482(.A (iB[13]), .B (iA[13]),
       .Y (add_8_11_n_868));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1132__4733(.A (iB[3]), .B (iA[3]), .Y
       (add_8_11_n_846));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1133__6161(.A (iB[7]), .B (iA[7]), .Y
       (add_8_11_n_847));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1134__9315(.A (iB[19]), .B (iA[19]),
       .Y (add_8_11_n_848));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1135__9945(.A (iB[5]), .B (iA[5]),
       .Y (add_8_11_n_873));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1136__2883(.A (iB[27]), .B (iA[27]),
       .Y (add_8_11_n_849));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1137__2346(.A (iB[29]), .B (iA[29]),
       .Y (add_8_11_n_850));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1138__1666(.A (iB[29]), .B (iA[29]),
       .Y (add_8_11_n_886));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1139__7410(.A (iB[21]), .B (iA[21]),
       .Y (add_8_11_n_887));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1140__6417(.A (iB[25]), .B (iA[25]),
       .Y (add_8_11_n_880));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1141__5477(.A (iB[17]), .B (iA[17]),
       .Y (add_8_11_n_890));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1142__2398(.A (iB[5]), .B (iA[5]), .Y
       (add_8_11_n_881));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1143__5107(.A (iB[1]), .B (iA[1]), .Y
       (add_8_11_n_882));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1144__6260(.A (iB[1]), .B (iA[1]),
       .Y (add_8_11_n_893));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1145__4319(.A (iB[19]), .B (iA[19]),
       .Y (add_8_11_n_894));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1146__8428(.A (iB[23]), .B (iA[23]),
       .Y (add_8_11_n_895));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1147__5526(.A (iB[7]), .B (iA[7]),
       .Y (add_8_11_n_896));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1148__6783(.A (iB[27]), .B (iA[27]),
       .Y (add_8_11_n_897));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1149__3680(.A (iB[25]), .B (iA[25]),
       .Y (add_8_11_n_898));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1150__1617(.A (iB[9]), .B (iA[9]), .Y
       (add_8_11_n_883));
  NOR2xp33_ASAP7_75t_SL add_8_11_g1151__2802(.A (iB[11]), .B (iA[11]),
       .Y (add_8_11_n_884));
  NAND2xp33_ASAP7_75t_SL add_8_11_g1152__1705(.A (iB[9]), .B (iA[9]),
       .Y (add_8_11_n_901));
  XOR2xp5_ASAP7_75t_SL g1158(.A (add_8_11_n_837), .B (add_8_11_n_674),
       .Y (n_134));
  XOR2xp5_ASAP7_75t_SL g1159(.A (add_8_11_n_770), .B (add_8_11_n_722),
       .Y (n_135));
  XOR2xp5_ASAP7_75t_SL g1160(.A (add_8_11_n_812), .B (add_8_11_n_698),
       .Y (n_136));
  XOR2xp5_ASAP7_75t_SL g1162(.A (add_8_11_n_827), .B (add_8_11_n_728),
       .Y (n_138));
  XOR2xp5_ASAP7_75t_SL g1165(.A (add_8_11_n_798), .B (add_8_11_n_686),
       .Y (n_141));
  XOR2xp5_ASAP7_75t_SL g1166(.A (add_8_11_n_820), .B (add_8_11_n_734),
       .Y (n_142));
  XOR2xp5_ASAP7_75t_SL g1167(.A (add_8_11_n_822), .B (add_8_11_n_704),
       .Y (n_143));
  XOR2xp5_ASAP7_75t_SL g1169(.A (n_176), .B (add_8_11_n_786), .Y
       (n_145));
  XOR2xp5_ASAP7_75t_SL g1170(.A (add_8_11_n_788), .B (add_8_11_n_680),
       .Y (n_146));
  XOR2xp5_ASAP7_75t_SL g1174(.A (add_8_11_n_772), .B (add_8_11_n_746),
       .Y (n_150));
  XOR2xp5_ASAP7_75t_SL g1175(.A (add_8_11_n_829), .B (add_8_11_n_710),
       .Y (n_151));
  XOR2xp5_ASAP7_75t_SL g1177(.A (add_8_11_n_776), .B (add_8_11_n_752),
       .Y (n_153));
  XOR2xp5_ASAP7_75t_SL g1178(.A (add_8_11_n_807), .B (add_8_11_n_692),
       .Y (n_154));
  XOR2xp5_ASAP7_75t_SL g1181(.A (add_8_11_n_790), .B (add_8_11_n_758),
       .Y (n_157));
  XOR2xp5_ASAP7_75t_SL g1182(.A (add_8_11_n_774), .B (add_8_11_n_716),
       .Y (n_158));
  XOR2xp5_ASAP7_75t_SL g1184(.A (add_8_11_n_784), .B (add_8_11_n_740),
       .Y (n_160));
  FAx1_ASAP7_75t_SL g1185(.A (iB[10]), .B (iA[10]), .CI
       (add_8_11_n_737), .CON (UNCONNECTED), .SN (n_161));
  FAx1_ASAP7_75t_SL g2(.A (iB[16]), .B (iA[16]), .CI (add_8_11_n_719),
       .CON (UNCONNECTED0), .SN (n_162));
  FAx1_ASAP7_75t_SL g1186(.A (iB[28]), .B (iA[28]), .CI
       (add_8_11_n_683), .CON (UNCONNECTED1), .SN (n_163));
  FAx1_ASAP7_75t_SL g1187(.A (iB[24]), .B (iA[24]), .CI
       (add_8_11_n_695), .CON (UNCONNECTED2), .SN (n_164));
  FAx1_ASAP7_75t_SL g1188(.A (iB[14]), .B (iA[14]), .CI
       (add_8_11_n_725), .CON (UNCONNECTED3), .SN (n_165));
  FAx1_ASAP7_75t_SL g1189(.A (iB[22]), .B (iA[22]), .CI
       (add_8_11_n_701), .CON (UNCONNECTED4), .SN (n_166));
  FAx1_ASAP7_75t_SL g1190(.A (iB[12]), .B (iA[12]), .CI
       (add_8_11_n_731), .CON (UNCONNECTED5), .SN (n_167));
  FAx1_ASAP7_75t_SL g1191(.A (iB[30]), .B (iA[30]), .CI
       (add_8_11_n_677), .CON (UNCONNECTED6), .SN (n_168));
  FAx1_ASAP7_75t_SL g1192(.A (iB[26]), .B (iA[26]), .CI
       (add_8_11_n_689), .CON (UNCONNECTED7), .SN (n_169));
  FAx1_ASAP7_75t_SL g1193(.A (iB[20]), .B (iA[20]), .CI
       (add_8_11_n_707), .CON (UNCONNECTED8), .SN (n_170));
  FAx1_ASAP7_75t_SL g1194(.A (iB[8]), .B (iA[8]), .CI (add_8_11_n_743),
       .CON (UNCONNECTED9), .SN (n_171));
  FAx1_ASAP7_75t_SL g1195(.A (iB[6]), .B (iA[6]), .CI (add_8_11_n_749),
       .CON (UNCONNECTED10), .SN (n_172));
  FAx1_ASAP7_75t_SL g1196(.A (iB[18]), .B (iA[18]), .CI
       (add_8_11_n_713), .CON (UNCONNECTED11), .SN (n_173));
  FAx1_ASAP7_75t_SL g1197(.A (iB[4]), .B (iA[4]), .CI (add_8_11_n_755),
       .CON (UNCONNECTED12), .SN (n_174));
  FAx1_ASAP7_75t_SL g1198(.A (iB[2]), .B (iA[2]), .CI (add_8_11_n_762),
       .CON (UNCONNECTED13), .SN (n_175));
  HAxp5_ASAP7_75t_SL g1199(.A (iB[0]), .B (iA[0]), .CON (n_176), .SN
       (n_177));
endmodule

