###############################################################
#  Generated by:      Cadence Innovus 22.17-s086_1
#  OS:                Linux x86_64(Host ID vlsiktmt)
#  Generated on:      Mon Apr  6 10:22:21 2026
#  Design:            top_axi_ram
#  Command:           create_ccopt_clock_tree_spec -filename outputs/ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins were identified as implicit sinks
# The following pins are design outputs carrying SDC clocks
# These pins are ignore skew pins
set_ccopt_property sink_type -pin {s_axi_rdata[0]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[0]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[10]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[10]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[11]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[11]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[12]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[12]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[13]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[13]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[14]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[14]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[15]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[15]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[16]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[16]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[17]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[17]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[18]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[18]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[19]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[19]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[1]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[1]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[20]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[20]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[21]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[21]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[22]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[22]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[23]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[23]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[24]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[24]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[25]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[25]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[26]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[26]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[27]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[27]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[28]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[28]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[29]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[29]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[2]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[2]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[30]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[30]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[31]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[31]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[3]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[3]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[4]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[4]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[5]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[5]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[6]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[6]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[7]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[7]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[8]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[8]} {implicit design_io}
set_ccopt_property sink_type -pin {s_axi_rdata[9]} ignore
set_ccopt_property sink_type_reasons -pin {s_axi_rdata[9]} {implicit design_io}

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk 50.000
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 2000

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[17]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[17]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<1> -source {u_sram_macro_sram_banks[0].u_bank/dataout[17]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<1> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<1> 50.000
# Clock period setting for source pin of clk<1>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[17]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[18]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[18]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<2> -source {u_sram_macro_sram_banks[0].u_bank/dataout[18]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<2> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<2> 50.000
# Clock period setting for source pin of clk<2>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[18]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[19]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[19]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<3> -source {u_sram_macro_sram_banks[0].u_bank/dataout[19]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<3> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<3> 50.000
# Clock period setting for source pin of clk<3>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[19]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[20]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[20]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<4> -source {u_sram_macro_sram_banks[0].u_bank/dataout[20]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<4> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<4> 50.000
# Clock period setting for source pin of clk<4>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[20]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[21]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[21]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<5> -source {u_sram_macro_sram_banks[0].u_bank/dataout[21]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<5> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<5> 50.000
# Clock period setting for source pin of clk<5>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[21]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[22]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[22]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<6> -source {u_sram_macro_sram_banks[0].u_bank/dataout[22]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<6> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<6> 50.000
# Clock period setting for source pin of clk<6>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[22]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[23]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[23]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<7> -source {u_sram_macro_sram_banks[0].u_bank/dataout[23]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<7> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<7> 50.000
# Clock period setting for source pin of clk<7>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[23]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[24]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[24]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<8> -source {u_sram_macro_sram_banks[0].u_bank/dataout[24]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<8> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<8> 50.000
# Clock period setting for source pin of clk<8>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[24]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[25]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[25]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<9> -source {u_sram_macro_sram_banks[0].u_bank/dataout[25]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<9> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<9> 50.000
# Clock period setting for source pin of clk<9>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[25]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[26]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[26]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<10> -source {u_sram_macro_sram_banks[0].u_bank/dataout[26]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<10> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<10> 50.000
# Clock period setting for source pin of clk<10>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[26]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[27]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[27]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<11> -source {u_sram_macro_sram_banks[0].u_bank/dataout[27]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<11> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<11> 50.000
# Clock period setting for source pin of clk<11>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[27]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[28]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[28]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<12> -source {u_sram_macro_sram_banks[0].u_bank/dataout[28]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<12> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<12> 50.000
# Clock period setting for source pin of clk<12>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[28]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[29]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[29]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<13> -source {u_sram_macro_sram_banks[0].u_bank/dataout[29]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<13> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<13> 50.000
# Clock period setting for source pin of clk<13>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[29]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[30]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[30]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<14> -source {u_sram_macro_sram_banks[0].u_bank/dataout[30]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<14> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<14> 50.000
# Clock period setting for source pin of clk<14>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[30]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[31]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[31]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<15> -source {u_sram_macro_sram_banks[0].u_bank/dataout[31]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<15> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<15> 50.000
# Clock period setting for source pin of clk<15>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[31]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[7]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[7]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<16> -source {u_sram_macro_sram_banks[0].u_bank/dataout[7]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<16> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<16> 50.000
# Clock period setting for source pin of clk<16>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[7]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[15]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[15]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<17> -source {u_sram_macro_sram_banks[0].u_bank/dataout[15]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<17> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<17> 50.000
# Clock period setting for source pin of clk<17>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[15]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[14]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[14]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<18> -source {u_sram_macro_sram_banks[0].u_bank/dataout[14]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<18> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<18> 50.000
# Clock period setting for source pin of clk<18>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[14]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[13]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[13]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<19> -source {u_sram_macro_sram_banks[0].u_bank/dataout[13]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<19> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<19> 50.000
# Clock period setting for source pin of clk<19>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[13]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[12]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[12]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<20> -source {u_sram_macro_sram_banks[0].u_bank/dataout[12]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<20> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<20> 50.000
# Clock period setting for source pin of clk<20>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[12]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[11]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[11]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<21> -source {u_sram_macro_sram_banks[0].u_bank/dataout[11]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<21> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<21> 50.000
# Clock period setting for source pin of clk<21>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[11]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[10]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[10]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<22> -source {u_sram_macro_sram_banks[0].u_bank/dataout[10]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<22> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<22> 50.000
# Clock period setting for source pin of clk<22>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[10]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[9]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[9]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<23> -source {u_sram_macro_sram_banks[0].u_bank/dataout[9]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<23> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<23> 50.000
# Clock period setting for source pin of clk<23>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[9]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[8]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[8]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<24> -source {u_sram_macro_sram_banks[0].u_bank/dataout[8]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<24> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<24> 50.000
# Clock period setting for source pin of clk<24>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[8]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[16]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[16]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<25> -source {u_sram_macro_sram_banks[0].u_bank/dataout[16]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<25> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<25> 50.000
# Clock period setting for source pin of clk<25>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[16]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[6]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[6]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<26> -source {u_sram_macro_sram_banks[0].u_bank/dataout[6]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<26> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<26> 50.000
# Clock period setting for source pin of clk<26>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[6]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[5]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[5]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<27> -source {u_sram_macro_sram_banks[0].u_bank/dataout[5]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<27> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<27> 50.000
# Clock period setting for source pin of clk<27>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[5]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[4]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[4]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<28> -source {u_sram_macro_sram_banks[0].u_bank/dataout[4]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<28> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<28> 50.000
# Clock period setting for source pin of clk<28>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[4]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[3]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[3]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<29> -source {u_sram_macro_sram_banks[0].u_bank/dataout[3]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<29> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<29> 50.000
# Clock period setting for source pin of clk<29>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[3]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[2]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[2]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<30> -source {u_sram_macro_sram_banks[0].u_bank/dataout[2]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<30> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<30> 50.000
# Clock period setting for source pin of clk<30>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[2]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[1]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[1]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<31> -source {u_sram_macro_sram_banks[0].u_bank/dataout[1]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<31> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<31> 50.000
# Clock period setting for source pin of clk<31>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[1]} auto

# Clocks present at pin u_sram_macro_sram_banks[0].u_bank/dataout[0]
#   clk (period 2000.000ns) in timing_config constraint_typical([outputs/synthesis.sdc])
# A generated clock tree is being used, even though the primary clock present is defined as non-generated in the SDC.
# This is to ensure that the arcs from
#   pin u_sram_macro_sram_banks[0].u_bank/clk
# to 
#   pin u_sram_macro_sram_banks[0].u_bank/dataout[0]
# are contained within the clock tree network for other clocks.
create_ccopt_generated_clock_tree -name clk<32> -source {u_sram_macro_sram_banks[0].u_bank/dataout[0]} -generated_by {{u_sram_macro_sram_banks[0].u_bank/clk}}
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree clk<32> 50.000
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree clk<32> 50.000
# Clock period setting for source pin of clk<32>
set_ccopt_property clock_period -pin {u_sram_macro_sram_banks[0].u_bank/dataout[0]} auto

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:constraint_typical (sdc outputs/synthesis.sdc)
create_ccopt_skew_group -name clk/constraint_typical -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/constraint_typical true
set_ccopt_property extracted_from_clock_name -skew_group clk/constraint_typical clk
set_ccopt_property extracted_from_constraint_mode_names -skew_group clk/constraint_typical {constraint_typical  }
set_ccopt_property extracted_from_delay_corners -skew_group clk/constraint_typical delay_corner_typical


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

