
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Apr  5 2026 10:35:06 +07 (Apr  5 2026 03:35:06 UTC)

// Verification Directory fv/top_axi_ram 

module
     axi_ctrl_ADDR_WIDTH32_DATA_WIDTH32_ID_WIDTH5_ADDR_MASK32h0000ffff(clk,
     rst_n, s_axi_awid, s_axi_awaddr, s_axi_awlen, s_axi_awsize,
     s_axi_awburst, s_axi_awlock, s_axi_awcache, s_axi_awprot,
     s_axi_awqos, s_axi_awregion, s_axi_awvalid, s_axi_awready,
     s_axi_wdata, s_axi_wstrb, s_axi_wlast, s_axi_wvalid, s_axi_wready,
     s_axi_bid, s_axi_bresp, s_axi_bvalid, s_axi_bready, s_axi_arid,
     s_axi_araddr, s_axi_arlen, s_axi_arsize, s_axi_arburst,
     s_axi_arlock, s_axi_arcache, s_axi_arprot, s_axi_arqos,
     s_axi_arregion, s_axi_arvalid, s_axi_arready, s_axi_rid,
     s_axi_rdata, s_axi_rresp, s_axi_rlast, s_axi_rvalid, s_axi_rready,
     bram_we, bram_waddr, bram_wdata, bram_wstrb, bram_re, bram_raddr,
     bram_rdata_in);
  input clk, rst_n, s_axi_awlock, s_axi_awvalid, s_axi_wlast,
       s_axi_wvalid, s_axi_bready, s_axi_arlock, s_axi_arvalid,
       s_axi_rready;
  input [4:0] s_axi_awid, s_axi_arid;
  input [31:0] s_axi_awaddr, s_axi_wdata, s_axi_araddr, bram_rdata_in;
  input [7:0] s_axi_awlen, s_axi_arlen;
  input [2:0] s_axi_awsize, s_axi_awprot, s_axi_arsize, s_axi_arprot;
  input [1:0] s_axi_awburst, s_axi_arburst;
  input [3:0] s_axi_awcache, s_axi_awqos, s_axi_awregion, s_axi_wstrb,
       s_axi_arcache, s_axi_arqos, s_axi_arregion;
  output s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready,
       s_axi_rlast, s_axi_rvalid, bram_we, bram_re;
  output [4:0] s_axi_bid, s_axi_rid;
  output [1:0] s_axi_bresp, s_axi_rresp;
  output [31:0] s_axi_rdata, bram_waddr, bram_wdata, bram_raddr;
  output [3:0] bram_wstrb;
  wire clk, rst_n, s_axi_awlock, s_axi_awvalid, s_axi_wlast,
       s_axi_wvalid, s_axi_bready, s_axi_arlock, s_axi_arvalid,
       s_axi_rready;
  wire [4:0] s_axi_awid, s_axi_arid;
  wire [31:0] s_axi_awaddr, s_axi_wdata, s_axi_araddr, bram_rdata_in;
  wire [7:0] s_axi_awlen, s_axi_arlen;
  wire [2:0] s_axi_awsize, s_axi_awprot, s_axi_arsize, s_axi_arprot;
  wire [1:0] s_axi_awburst, s_axi_arburst;
  wire [3:0] s_axi_awcache, s_axi_awqos, s_axi_awregion, s_axi_wstrb,
       s_axi_arcache, s_axi_arqos, s_axi_arregion;
  wire s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready,
       s_axi_rlast, s_axi_rvalid, bram_we, bram_re;
  wire [4:0] s_axi_bid, s_axi_rid;
  wire [1:0] s_axi_bresp, s_axi_rresp;
  wire [31:0] s_axi_rdata, bram_waddr, bram_wdata, bram_raddr;
  wire [3:0] bram_wstrb;
  wire [1:0] w_state;
  wire [31:0] ar_addr_reg;
  wire [2:0] ar_size_reg;
  wire [1:0] r_state;
  wire [7:0] ar_len_reg;
  wire [31:0] aw_addr_reg;
  wire [2:0] aw_size_reg;
  wire [7:0] r_count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_138, n_139, n_140, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_246, n_247, n_248, n_249, n_250, n_251, n_252, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_273, n_274, n_275, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_301, n_302, n_304, n_305;
  wire n_306, n_307, n_308, n_309, n_310, n_311, n_312, n_313;
  wire n_314, n_315, n_316, n_317, n_318, n_319, n_320, n_321;
  wire n_406, n_488, n_489, n_490, n_515, n_517, n_518, n_519;
  INVxp33_ASAP7_75t_R g4619(.A (n_489), .Y (bram_we));
  INVx1_ASAP7_75t_R g4618(.A (n_406), .Y (n_298));
  INVx1_ASAP7_75t_R g4617(.A (s_axi_wlast), .Y (n_297));
  INVx1_ASAP7_75t_R g4620(.A (w_state[1]), .Y (n_296));
  AO22x1_ASAP7_75t_R g5522__2398(.A1 (n_515), .A2 (n_319), .B1
       (s_axi_araddr[15]), .B2 (n_241), .Y (bram_raddr[13]));
  AO22x1_ASAP7_75t_R g5523__5107(.A1 (n_515), .A2 (n_304), .B1
       (s_axi_araddr[14]), .B2 (n_241), .Y (bram_raddr[12]));
  AO22x1_ASAP7_75t_R g5524__6260(.A1 (n_488), .A2 (n_318), .B1
       (s_axi_araddr[13]), .B2 (n_241), .Y (bram_raddr[11]));
  XNOR2xp5_ASAP7_75t_R g5525__4319(.A (ar_addr_reg[15]), .B (n_295), .Y
       (n_319));
  AO22x1_ASAP7_75t_R g5526__8428(.A1 (n_488), .A2 (n_305), .B1
       (s_axi_araddr[12]), .B2 (n_241), .Y (bram_raddr[10]));
  XNOR2xp5_ASAP7_75t_R g5527__5526(.A (ar_addr_reg[14]), .B (n_294), .Y
       (n_304));
  NAND2xp5_ASAP7_75t_R g5528__6783(.A (ar_addr_reg[14]), .B (n_293), .Y
       (n_295));
  AO22x1_ASAP7_75t_R g5529__3680(.A1 (n_488), .A2 (n_317), .B1
       (s_axi_araddr[11]), .B2 (n_241), .Y (bram_raddr[9]));
  OA21x2_ASAP7_75t_R g5530__1617(.A1 (ar_addr_reg[13]), .A2 (n_292), .B
       (n_294), .Y (n_318));
  INVx1_ASAP7_75t_R g5531(.A (n_294), .Y (n_293));
  NAND2xp5_ASAP7_75t_R g5532__2802(.A (ar_addr_reg[13]), .B (n_292), .Y
       (n_294));
  AO22x1_ASAP7_75t_R g5533__1705(.A1 (n_488), .A2 (n_309), .B1
       (s_axi_araddr[10]), .B2 (n_241), .Y (bram_raddr[8]));
  XNOR2xp5_ASAP7_75t_R g5534__5122(.A (ar_addr_reg[12]), .B (n_291), .Y
       (n_305));
  NOR2xp33_ASAP7_75t_R g5535__8246(.A (n_244), .B (n_291), .Y (n_292));
  AO22x1_ASAP7_75t_R g5536__7098(.A1 (n_488), .A2 (n_316), .B1
       (s_axi_araddr[9]), .B2 (n_241), .Y (bram_raddr[7]));
  OA21x2_ASAP7_75t_R g5537__6131(.A1 (ar_addr_reg[11]), .A2 (n_290), .B
       (n_291), .Y (n_317));
  NAND2xp5_ASAP7_75t_R g5538__1881(.A (ar_addr_reg[11]), .B (n_290), .Y
       (n_291));
  AO22x1_ASAP7_75t_R g5539__5115(.A1 (n_515), .A2 (n_307), .B1
       (s_axi_araddr[8]), .B2 (n_241), .Y (bram_raddr[6]));
  AOI21xp5_ASAP7_75t_R g5540__7482(.A1 (n_289), .A2 (n_248), .B
       (n_290), .Y (n_309));
  NOR2xp33_ASAP7_75t_R g5541__4733(.A (n_248), .B (n_289), .Y (n_290));
  OA21x2_ASAP7_75t_R g5542__6161(.A1 (ar_addr_reg[9]), .A2 (n_288), .B
       (n_289), .Y (n_316));
  NAND2xp5_ASAP7_75t_R g5543__9315(.A (ar_addr_reg[9]), .B (n_288), .Y
       (n_289));
  AO22x1_ASAP7_75t_R g5544__9945(.A1 (n_515), .A2 (n_308), .B1
       (s_axi_araddr[7]), .B2 (n_241), .Y (bram_raddr[5]));
  AOI21xp5_ASAP7_75t_R g5545__2883(.A1 (n_287), .A2 (n_246), .B
       (n_288), .Y (n_307));
  NOR2xp33_ASAP7_75t_R g5546__2346(.A (n_246), .B (n_287), .Y (n_288));
  OAI21xp5_ASAP7_75t_R g5547__1666(.A1 (n_254), .A2 (n_286), .B
       (ar_addr_reg[7]), .Y (n_287));
  AO22x1_ASAP7_75t_R g5548__7410(.A1 (n_515), .A2 (n_310), .B1
       (s_axi_araddr[6]), .B2 (n_241), .Y (bram_raddr[4]));
  XNOR2xp5_ASAP7_75t_R g5549__6417(.A (n_276), .B (n_286), .Y (n_308));
  OAI21xp5_ASAP7_75t_R g5550__5477(.A1 (n_269), .A2 (n_285), .B
       (n_270), .Y (n_286));
  AO22x1_ASAP7_75t_R g5551__2398(.A1 (n_311), .A2 (n_515), .B1
       (s_axi_araddr[5]), .B2 (n_241), .Y (bram_raddr[3]));
  XNOR2xp5_ASAP7_75t_R g5552__5107(.A (n_280), .B (n_285), .Y (n_310));
  OA21x2_ASAP7_75t_R g5553__6260(.A1 (n_266), .A2 (n_284), .B (n_267),
       .Y (n_285));
  AO22x1_ASAP7_75t_R g5554__4319(.A1 (n_313), .A2 (n_488), .B1
       (s_axi_araddr[4]), .B2 (n_241), .Y (bram_raddr[2]));
  XNOR2xp5_ASAP7_75t_R g5555__8428(.A (n_279), .B (n_284), .Y (n_311));
  OA21x2_ASAP7_75t_R g5556__5526(.A1 (n_265), .A2 (n_283), .B (n_263),
       .Y (n_284));
  AO22x1_ASAP7_75t_R g5557__6783(.A1 (n_306), .A2 (n_515), .B1
       (s_axi_araddr[3]), .B2 (n_241), .Y (bram_raddr[1]));
  XNOR2xp5_ASAP7_75t_R g5558__3680(.A (n_277), .B (n_283), .Y (n_313));
  OA21x2_ASAP7_75t_R g5559__1617(.A1 (n_272), .A2 (n_282), .B (n_273),
       .Y (n_283));
  AO22x1_ASAP7_75t_R g5560__2802(.A1 (n_315), .A2 (n_488), .B1
       (s_axi_araddr[2]), .B2 (n_241), .Y (bram_raddr[0]));
  XNOR2xp5_ASAP7_75t_R g5561__1705(.A (n_278), .B (n_282), .Y (n_306));
  OAI21xp5_ASAP7_75t_R g5562__5122(.A1 (n_259), .A2 (n_281), .B
       (ar_addr_reg[2]), .Y (n_282));
  XNOR2xp5_ASAP7_75t_R g5563__8246(.A (n_275), .B (n_281), .Y (n_315));
  OAI21xp5_ASAP7_75t_R g5564__7098(.A1 (n_262), .A2 (n_312), .B
       (n_301), .Y (n_281));
  OAI21xp5_ASAP7_75t_R g5565__6131(.A1 (s_axi_rlast), .A2 (n_321), .B
       (n_515), .Y (bram_re));
  NOR2xp33_ASAP7_75t_R g5566__1881(.A (n_271), .B (n_269), .Y (n_280));
  NOR2xp33_ASAP7_75t_R g5567__5115(.A (n_268), .B (n_266), .Y (n_279));
  NOR2xp33_ASAP7_75t_R g5568__7482(.A (n_274), .B (n_272), .Y (n_278));
  NOR2xp33_ASAP7_75t_R g5569__4733(.A (n_265), .B (n_264), .Y (n_277));
  XNOR2xp5_ASAP7_75t_R g5570__6161(.A (ar_addr_reg[7]), .B (n_254), .Y
       (n_276));
  XNOR2xp5_ASAP7_75t_R g5571__9315(.A (ar_addr_reg[2]), .B (n_259), .Y
       (n_275));
  INVx1_ASAP7_75t_R g5572(.A (n_273), .Y (n_274));
  INVx1_ASAP7_75t_R g5573(.A (n_270), .Y (n_271));
  NAND2xp5_ASAP7_75t_R g5574__9945(.A (ar_addr_reg[3]), .B (n_257), .Y
       (n_273));
  NOR2xp33_ASAP7_75t_R g5575__2883(.A (ar_addr_reg[3]), .B (n_257), .Y
       (n_272));
  NAND2xp5_ASAP7_75t_R g5576__2346(.A (ar_addr_reg[6]), .B (n_258), .Y
       (n_270));
  NOR2xp33_ASAP7_75t_R g5577__1666(.A (ar_addr_reg[6]), .B (n_258), .Y
       (n_269));
  NAND2xp5_ASAP7_75t_R g5578__7410(.A (ar_addr_reg[0]), .B (n_261), .Y
       (n_312));
  NAND2xp5_ASAP7_75t_R g5579__6417(.A (ar_addr_reg[1]), .B (n_255), .Y
       (n_301));
  INVx1_ASAP7_75t_R g5580(.A (n_267), .Y (n_268));
  INVx1_ASAP7_75t_R g5581(.A (n_263), .Y (n_264));
  INVx1_ASAP7_75t_R g5582(.A (n_262), .Y (n_302));
  NAND4xp25_ASAP7_75t_R g5583__5477(.A (s_axi_wvalid), .B (n_296), .C
       (s_axi_wready), .D (w_state[0]), .Y (n_489));
  NAND2xp5_ASAP7_75t_R g5584__2398(.A (ar_addr_reg[5]), .B (n_260), .Y
       (n_267));
  NOR2xp33_ASAP7_75t_R g5585__5107(.A (ar_addr_reg[5]), .B (n_260), .Y
       (n_266));
  NOR2xp33_ASAP7_75t_R g5586__6260(.A (ar_addr_reg[4]), .B (n_256), .Y
       (n_265));
  NAND2xp5_ASAP7_75t_R g5587__4319(.A (ar_addr_reg[4]), .B (n_256), .Y
       (n_263));
  NAND3xp33_ASAP7_75t_R g5588__8428(.A (s_axi_rready), .B (n_8), .C
       (s_axi_rvalid), .Y (n_321));
  NOR2xp33_ASAP7_75t_R g5589__5526(.A (ar_addr_reg[1]), .B (n_255), .Y
       (n_262));
  INVx1_ASAP7_75t_R g5590(.A (n_320), .Y (n_261));
  INVx1_ASAP7_75t_R g5597(.A (n_241), .Y (n_488));
  NAND2xp5_ASAP7_75t_R g5600__6783(.A (n_242), .B (n_249), .Y (n_320));
  NOR2xp33_ASAP7_75t_R g5601__3680(.A (ar_size_reg[1]), .B (n_250), .Y
       (n_260));
  AND2x2_ASAP7_75t_R g5602__1617(.A (ar_size_reg[1]), .B (n_249), .Y
       (n_259));
  NOR2x1_ASAP7_75t_R g5603__2802(.A (n_314), .B (n_406), .Y (n_241));
  NOR2xp33_ASAP7_75t_R g5604__1705(.A (n_242), .B (n_251), .Y (n_258));
  NOR2xp33_ASAP7_75t_R g5605__5122(.A (n_242), .B (n_252), .Y (n_257));
  NOR2xp33_ASAP7_75t_R g5606__8246(.A (ar_size_reg[1]), .B (n_251), .Y
       (n_256));
  NOR2xp33_ASAP7_75t_R g5607__7098(.A (ar_size_reg[1]), .B (n_252), .Y
       (n_255));
  NOR2xp33_ASAP7_75t_R g5608__6131(.A (n_242), .B (n_250), .Y (n_254));
  NOR2xp33_ASAP7_75t_R g5610__1881(.A (r_state[0]), .B (n_28), .Y
       (n_8));
  NAND2xp5_ASAP7_75t_R g5611__5115(.A (ar_size_reg[0]), .B (n_243), .Y
       (n_252));
  NAND2xp5_ASAP7_75t_R g5612__7482(.A (ar_size_reg[2]), .B (n_247), .Y
       (n_251));
  NAND2xp5_ASAP7_75t_R g5613__4733(.A (ar_size_reg[2]), .B
       (ar_size_reg[0]), .Y (n_250));
  NAND2xp5_ASAP7_75t_R g5614__6161(.A (s_axi_arready), .B
       (s_axi_arvalid), .Y (n_406));
  OR2x2_ASAP7_75t_R g5615__9315(.A (r_state[0]), .B (r_state[1]), .Y
       (n_314));
  NOR2xp33_ASAP7_75t_R g5616__9945(.A (ar_size_reg[0]), .B
       (ar_size_reg[2]), .Y (n_249));
  INVx1_ASAP7_75t_R g5617(.A (ar_addr_reg[10]), .Y (n_248));
  INVx1_ASAP7_75t_R g5618(.A (ar_size_reg[0]), .Y (n_247));
  INVx1_ASAP7_75t_R g5619(.A (ar_addr_reg[8]), .Y (n_246));
  INVx1_ASAP7_75t_R g5621(.A (ar_addr_reg[12]), .Y (n_244));
  INVx1_ASAP7_75t_R g5622(.A (ar_size_reg[2]), .Y (n_243));
  INVx1_ASAP7_75t_R g5623(.A (ar_size_reg[1]), .Y (n_242));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[0] (.CLK (clk), .D (n_169), .QN
       (ar_addr_reg[0]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[1] (.CLK (clk), .D (n_179), .QN
       (ar_addr_reg[1]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[2] (.CLK (clk), .D (n_168), .QN
       (ar_addr_reg[2]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[3] (.CLK (clk), .D (n_170), .QN
       (ar_addr_reg[3]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[4] (.CLK (clk), .D (n_167), .QN
       (ar_addr_reg[4]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[5] (.CLK (clk), .D (n_156), .QN
       (ar_addr_reg[5]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[6] (.CLK (clk), .D (n_166), .QN
       (ar_addr_reg[6]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[7] (.CLK (clk), .D (n_165), .QN
       (ar_addr_reg[7]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[8] (.CLK (clk), .D (n_164), .QN
       (ar_addr_reg[8]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[9] (.CLK (clk), .D (n_163), .QN
       (ar_addr_reg[9]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[10] (.CLK (clk), .D (n_162),
       .QN (ar_addr_reg[10]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[11] (.CLK (clk), .D (n_161),
       .QN (ar_addr_reg[11]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[12] (.CLK (clk), .D (n_159),
       .QN (ar_addr_reg[12]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[13] (.CLK (clk), .D (n_160),
       .QN (ar_addr_reg[13]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[14] (.CLK (clk), .D (n_158),
       .QN (ar_addr_reg[14]));
  DFFHQNx1_ASAP7_75t_R \ar_addr_reg_reg[15] (.CLK (clk), .D (n_157),
       .QN (ar_addr_reg[15]));
  DFFHQNx1_ASAP7_75t_R \ar_len_reg_reg[0] (.CLK (clk), .D (n_109), .QN
       (ar_len_reg[0]));
  DFFHQNx1_ASAP7_75t_R \ar_len_reg_reg[1] (.CLK (clk), .D (n_99), .QN
       (ar_len_reg[1]));
  DFFHQNx1_ASAP7_75t_R \ar_len_reg_reg[2] (.CLK (clk), .D (n_117), .QN
       (ar_len_reg[2]));
  DFFHQNx1_ASAP7_75t_R \ar_len_reg_reg[3] (.CLK (clk), .D (n_114), .QN
       (ar_len_reg[3]));
  DFFHQNx1_ASAP7_75t_R \ar_len_reg_reg[4] (.CLK (clk), .D (n_120), .QN
       (ar_len_reg[4]));
  DFFHQNx1_ASAP7_75t_R \ar_len_reg_reg[5] (.CLK (clk), .D (n_121), .QN
       (ar_len_reg[5]));
  DFFHQNx1_ASAP7_75t_R \ar_len_reg_reg[6] (.CLK (clk), .D (n_122), .QN
       (ar_len_reg[6]));
  DFFHQNx1_ASAP7_75t_R \ar_len_reg_reg[7] (.CLK (clk), .D (n_100), .QN
       (ar_len_reg[7]));
  DFFHQNx1_ASAP7_75t_R \ar_size_reg_reg[0] (.CLK (clk), .D (n_107), .QN
       (ar_size_reg[0]));
  DFFHQNx1_ASAP7_75t_R \ar_size_reg_reg[1] (.CLK (clk), .D (n_108), .QN
       (ar_size_reg[1]));
  DFFHQNx1_ASAP7_75t_R \ar_size_reg_reg[2] (.CLK (clk), .D (n_106), .QN
       (ar_size_reg[2]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[0] (.CLK (clk), .D (n_191), .QN
       (aw_addr_reg[0]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[1] (.CLK (clk), .D (n_200), .QN
       (aw_addr_reg[1]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[2] (.CLK (clk), .D (n_204), .QN
       (bram_waddr[0]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[3] (.CLK (clk), .D (n_208), .QN
       (bram_waddr[1]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[4] (.CLK (clk), .D (n_211), .QN
       (bram_waddr[2]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[5] (.CLK (clk), .D (n_214), .QN
       (bram_waddr[3]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[6] (.CLK (clk), .D (n_217), .QN
       (bram_waddr[4]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[7] (.CLK (clk), .D (n_222), .QN
       (bram_waddr[5]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[8] (.CLK (clk), .D (n_228), .QN
       (bram_waddr[6]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[9] (.CLK (clk), .D (n_232), .QN
       (bram_waddr[7]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[10] (.CLK (clk), .D (n_231),
       .QN (bram_waddr[8]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[11] (.CLK (clk), .D (n_235),
       .QN (bram_waddr[9]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[12] (.CLK (clk), .D (n_237),
       .QN (bram_waddr[10]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[13] (.CLK (clk), .D (n_238),
       .QN (bram_waddr[11]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[14] (.CLK (clk), .D (n_239),
       .QN (bram_waddr[12]));
  DFFHQNx1_ASAP7_75t_R \aw_addr_reg_reg[15] (.CLK (clk), .D (n_240),
       .QN (bram_waddr[13]));
  DFFHQNx1_ASAP7_75t_R \aw_size_reg_reg[0] (.CLK (clk), .D (n_177), .QN
       (aw_size_reg[0]));
  DFFHQNx1_ASAP7_75t_R \aw_size_reg_reg[1] (.CLK (clk), .D (n_174), .QN
       (aw_size_reg[1]));
  DFFHQNx1_ASAP7_75t_R \aw_size_reg_reg[2] (.CLK (clk), .D (n_176), .QN
       (aw_size_reg[2]));
  SDFHx1_ASAP7_75t_R \r_count_reg[0] (.CLK (clk), .D (n_6), .SE
       (r_count[0]), .SI (n_5), .QN (r_count[0]));
  DFFHQNx1_ASAP7_75t_R \r_count_reg[1] (.CLK (clk), .D (n_146), .QN
       (r_count[1]));
  DFFHQNx1_ASAP7_75t_R \r_count_reg[2] (.CLK (clk), .D (n_155), .QN
       (r_count[2]));
  DFFHQNx1_ASAP7_75t_R \r_count_reg[3] (.CLK (clk), .D (n_187), .QN
       (r_count[3]));
  DFFHQNx1_ASAP7_75t_R \r_count_reg[4] (.CLK (clk), .D (n_192), .QN
       (r_count[4]));
  DFFHQNx1_ASAP7_75t_R \r_count_reg[5] (.CLK (clk), .D (n_196), .QN
       (r_count[5]));
  DFFHQNx1_ASAP7_75t_R \r_count_reg[6] (.CLK (clk), .D (n_199), .QN
       (r_count[6]));
  DFFHQNx1_ASAP7_75t_R \r_count_reg[7] (.CLK (clk), .D (n_203), .QN
       (r_count[7]));
  DFFHQNx1_ASAP7_75t_R \r_state_reg[0] (.CLK (clk), .D (n_40), .QN
       (r_state[0]));
  DFFHQNx1_ASAP7_75t_R \r_state_reg[1] (.CLK (clk), .D (n_93), .QN
       (r_state[1]));
  DFFHQNx3_ASAP7_75t_R s_axi_arready_reg(.CLK (clk), .D (n_97), .QN
       (s_axi_arready));
  DFFHQNx3_ASAP7_75t_R s_axi_awready_reg(.CLK (clk), .D (n_144), .QN
       (s_axi_awready));
  DFFHQNx3_ASAP7_75t_R \s_axi_bid_reg[0] (.CLK (clk), .D (n_175), .QN
       (s_axi_bid[0]));
  DFFHQNx3_ASAP7_75t_R \s_axi_bid_reg[1] (.CLK (clk), .D (n_181), .QN
       (s_axi_bid[1]));
  DFFHQNx3_ASAP7_75t_R \s_axi_bid_reg[2] (.CLK (clk), .D (n_173), .QN
       (s_axi_bid[2]));
  DFFHQNx3_ASAP7_75t_R \s_axi_bid_reg[3] (.CLK (clk), .D (n_172), .QN
       (s_axi_bid[3]));
  DFFHQNx3_ASAP7_75t_R \s_axi_bid_reg[4] (.CLK (clk), .D (n_171), .QN
       (s_axi_bid[4]));
  SDFHx3_ASAP7_75t_R s_axi_bvalid_reg(.CLK (clk), .D (n_37), .SE
       (n_110), .SI (n_34), .QN (s_axi_bvalid));
  DFFHQNx3_ASAP7_75t_R \s_axi_rid_reg[0] (.CLK (clk), .D (n_105), .QN
       (s_axi_rid[0]));
  DFFHQNx3_ASAP7_75t_R \s_axi_rid_reg[1] (.CLK (clk), .D (n_104), .QN
       (s_axi_rid[1]));
  DFFHQNx3_ASAP7_75t_R \s_axi_rid_reg[2] (.CLK (clk), .D (n_103), .QN
       (s_axi_rid[2]));
  DFFHQNx3_ASAP7_75t_R \s_axi_rid_reg[3] (.CLK (clk), .D (n_102), .QN
       (s_axi_rid[3]));
  DFFHQNx3_ASAP7_75t_R \s_axi_rid_reg[4] (.CLK (clk), .D (n_101), .QN
       (s_axi_rid[4]));
  DFFHQNx3_ASAP7_75t_R s_axi_rlast_reg(.CLK (clk), .D (n_205), .QN
       (s_axi_rlast));
  DFFHQNx3_ASAP7_75t_R s_axi_rvalid_reg(.CLK (clk), .D (n_95), .QN
       (s_axi_rvalid));
  DFFHQNx3_ASAP7_75t_R s_axi_wready_reg(.CLK (clk), .D (n_145), .QN
       (s_axi_wready));
  DFFHQNx1_ASAP7_75t_R \w_state_reg[0] (.CLK (clk), .D (n_185), .QN
       (w_state[0]));
  DFFHQNx1_ASAP7_75t_R \w_state_reg[1] (.CLK (clk), .D (n_186), .QN
       (w_state[1]));
  AOI222xp33_ASAP7_75t_R g7216__2883(.A1 (n_236), .A2 (n_148), .B1
       (n_151), .B2 (bram_waddr[13]), .C1 (n_149), .C2
       (s_axi_awaddr[15]), .Y (n_240));
  AOI222xp33_ASAP7_75t_R g7218__2346(.A1 (n_234), .A2 (n_148), .B1
       (n_151), .B2 (bram_waddr[12]), .C1 (n_149), .C2
       (s_axi_awaddr[14]), .Y (n_239));
  AOI222xp33_ASAP7_75t_R g7220__1666(.A1 (n_230), .A2 (n_148), .B1
       (n_151), .B2 (bram_waddr[11]), .C1 (n_149), .C2
       (s_axi_awaddr[13]), .Y (n_238));
  AOI222xp33_ASAP7_75t_R g7222__7410(.A1 (n_227), .A2 (n_148), .B1
       (n_151), .B2 (bram_waddr[10]), .C1 (n_149), .C2
       (s_axi_awaddr[12]), .Y (n_237));
  XNOR2xp5_ASAP7_75t_R g7223__6417(.A (bram_waddr[13]), .B (n_233), .Y
       (n_236));
  AOI222xp33_ASAP7_75t_R g7226__5477(.A1 (n_225), .A2 (bram_waddr[9]),
       .B1 (n_224), .B2 (n_148), .C1 (n_149), .C2 (s_axi_awaddr[11]),
       .Y (n_235));
  XNOR2xp5_ASAP7_75t_R g7227__2398(.A (bram_waddr[12]), .B (n_229), .Y
       (n_234));
  OR2x2_ASAP7_75t_R g7228__5107(.A (n_26), .B (n_229), .Y (n_233));
  AOI222xp33_ASAP7_75t_R g7230__6260(.A1 (n_221), .A2 (n_148), .B1
       (n_151), .B2 (bram_waddr[7]), .C1 (n_149), .C2
       (s_axi_awaddr[9]), .Y (n_232));
  AOI322xp5_ASAP7_75t_R g7231__4319(.A1 (n_220), .A2 (n_148), .A3
       (n_10), .B1 (s_axi_awaddr[10]), .B2 (n_149), .C1 (n_225), .C2
       (bram_waddr[8]), .Y (n_231));
  XNOR2xp5_ASAP7_75t_R g7232__8428(.A (bram_waddr[11]), .B (n_226), .Y
       (n_230));
  OR2x2_ASAP7_75t_R g7233__5526(.A (n_24), .B (n_226), .Y (n_229));
  AOI222xp33_ASAP7_75t_R g7234__6783(.A1 (n_219), .A2 (n_148), .B1
       (n_151), .B2 (bram_waddr[6]), .C1 (n_149), .C2
       (s_axi_awaddr[8]), .Y (n_228));
  XNOR2xp5_ASAP7_75t_R g7235__3680(.A (bram_waddr[10]), .B (n_223), .Y
       (n_227));
  OR2x2_ASAP7_75t_R g7236__1617(.A (n_25), .B (n_223), .Y (n_226));
  AO32x1_ASAP7_75t_R g7238__2802(.A1 (n_220), .A2 (n_18), .A3
       (bram_waddr[8]), .B1 (n_10), .B2 (bram_waddr[9]), .Y (n_224));
  OAI21xp5_ASAP7_75t_R g7239__1705(.A1 (n_147), .A2 (n_220), .B
       (n_150), .Y (n_225));
  NAND3xp33_ASAP7_75t_R g7240__5122(.A (n_220), .B (bram_waddr[9]), .C
       (bram_waddr[8]), .Y (n_223));
  AOI222xp33_ASAP7_75t_R g7241__8246(.A1 (n_148), .A2 (n_215), .B1
       (n_151), .B2 (bram_waddr[5]), .C1 (n_149), .C2
       (s_axi_awaddr[7]), .Y (n_222));
  XNOR2xp5_ASAP7_75t_R g7242__7098(.A (bram_waddr[7]), .B (n_218), .Y
       (n_221));
  XNOR2xp5_ASAP7_75t_R g7244__6131(.A (bram_waddr[6]), .B (n_216), .Y
       (n_219));
  NOR2xp33_ASAP7_75t_R g7245__1881(.A (n_21), .B (n_218), .Y (n_220));
  OR2x2_ASAP7_75t_R g7246__5115(.A (n_16), .B (n_216), .Y (n_218));
  AOI222xp33_ASAP7_75t_R g7247__7482(.A1 (n_148), .A2 (n_517), .B1
       (n_151), .B2 (bram_waddr[4]), .C1 (n_149), .C2
       (s_axi_awaddr[6]), .Y (n_217));
  XOR2xp5_ASAP7_75t_R g7249__4733(.A (n_140), .B (n_213), .Y (n_215));
  OAI21xp5_ASAP7_75t_R g7250__6161(.A1 (n_90), .A2 (n_213), .B
       (bram_waddr[5]), .Y (n_216));
  AOI222xp33_ASAP7_75t_R g7251__9315(.A1 (n_148), .A2 (n_209), .B1
       (n_151), .B2 (bram_waddr[3]), .C1 (n_149), .C2
       (s_axi_awaddr[5]), .Y (n_214));
  AOI21xp5_ASAP7_75t_R g7254__2883(.A1 (n_210), .A2 (n_76), .B (n_22),
       .Y (n_213));
  AOI222xp33_ASAP7_75t_R g7255__2346(.A1 (n_148), .A2 (n_206), .B1
       (n_151), .B2 (bram_waddr[2]), .C1 (n_149), .C2
       (s_axi_awaddr[4]), .Y (n_211));
  XOR2xp5_ASAP7_75t_R g7257__1666(.A (n_135), .B (n_207), .Y (n_209));
  OAI21xp5_ASAP7_75t_R g7258__7410(.A1 (n_88), .A2 (n_207), .B
       (bram_waddr[3]), .Y (n_210));
  AOI222xp33_ASAP7_75t_R g7259__6417(.A1 (n_148), .A2 (n_198), .B1
       (n_151), .B2 (bram_waddr[1]), .C1 (n_149), .C2
       (s_axi_awaddr[3]), .Y (n_208));
  XOR2xp5_ASAP7_75t_R g7262__5477(.A (n_138), .B (n_201), .Y (n_206));
  OAI21xp5_ASAP7_75t_R g7263__2398(.A1 (n_133), .A2 (n_202), .B
       (n_129), .Y (n_207));
  A2O1A1Ixp33_ASAP7_75t_R g7267__5107(.A1 (s_axi_rlast), .A2 (n_91), .B
       (n_490), .C (n_2), .Y (n_205));
  AOI222xp33_ASAP7_75t_R g7268__6260(.A1 (n_148), .A2 (n_518), .B1
       (n_151), .B2 (bram_waddr[0]), .C1 (n_149), .C2
       (s_axi_awaddr[2]), .Y (n_204));
  AOI22xp5_ASAP7_75t_R g7269__4319(.A1 (n_195), .A2 (n_80), .B1
       (r_count[7]), .B2 (n_35), .Y (n_203));
  INVx1_ASAP7_75t_R g7270(.A (n_201), .Y (n_202));
  OAI21xp5_ASAP7_75t_R g7271__8428(.A1 (n_131), .A2 (n_194), .B
       (n_134), .Y (n_201));
  AOI222xp33_ASAP7_75t_R g7273__5526(.A1 (n_148), .A2 (n_519), .B1
       (n_151), .B2 (aw_addr_reg[1]), .C1 (n_149), .C2
       (s_axi_awaddr[1]), .Y (n_200));
  AOI22xp5_ASAP7_75t_R g7274__6783(.A1 (n_193), .A2 (n_0), .B1
       (r_count[6]), .B2 (n_1), .Y (n_199));
  XOR2xp5_ASAP7_75t_R g7275__3680(.A (n_139), .B (n_194), .Y (n_198));
  AOI22xp5_ASAP7_75t_R g7279__2802(.A1 (n_188), .A2 (n_80), .B1
       (r_count[5]), .B2 (n_35), .Y (n_196));
  XNOR2xp5_ASAP7_75t_R g7280__1705(.A (r_count[7]), .B (n_184), .Y
       (n_195));
  AO21x1_ASAP7_75t_R g7281__5122(.A1 (n_84), .A2 (n_183), .B (n_23), .Y
       (n_194));
  XNOR2xp5_ASAP7_75t_R g7285__8246(.A (r_count[6]), .B (n_182), .Y
       (n_193));
  AOI22xp5_ASAP7_75t_R g7286__7098(.A1 (n_154), .A2 (n_80), .B1
       (r_count[4]), .B2 (n_35), .Y (n_192));
  AOI222xp33_ASAP7_75t_R g7287__6131(.A1 (n_148), .A2 (n_142), .B1
       (n_151), .B2 (aw_addr_reg[0]), .C1 (n_149), .C2
       (s_axi_awaddr[0]), .Y (n_191));
  XNOR2xp5_ASAP7_75t_R g7306__7482(.A (r_count[5]), .B (n_152), .Y
       (n_188));
  AOI22xp5_ASAP7_75t_R g7307__4733(.A1 (n_143), .A2 (n_0), .B1
       (r_count[3]), .B2 (n_1), .Y (n_187));
  AOI31xp33_ASAP7_75t_R g7308__6161(.A1 (n_153), .A2 (n_2), .A3
       (w_state[1]), .B (n_178), .Y (n_186));
  AOI21xp5_ASAP7_75t_R g7309__9315(.A1 (n_153), .A2 (n_36), .B (n_149),
       .Y (n_185));
  OR2x2_ASAP7_75t_R g7314__9945(.A (n_13), .B (n_182), .Y (n_184));
  A2O1A1Ixp33_ASAP7_75t_R g7321__2883(.A1 (s_axi_awid[1]), .A2 (n_82),
       .B (n_116), .C (rst_n), .Y (n_181));
  NAND5xp2_ASAP7_75t_R g7322__2346(.A (n_94), .B (n_75), .C (n_69), .D
       (n_67), .E (n_72), .Y (n_180));
  AOI222xp33_ASAP7_75t_R g7323__1666(.A1 (n_0), .A2 (n_96), .B1 (n_83),
       .B2 (s_axi_araddr[1]), .C1 (n_35), .C2 (ar_addr_reg[1]), .Y
       (n_179));
  NOR3xp33_ASAP7_75t_R g7324__7410(.A (n_153), .B (n_37), .C
       (w_state[1]), .Y (n_178));
  A2O1A1Ixp33_ASAP7_75t_R g7325__6417(.A1 (s_axi_awsize[0]), .A2
       (n_82), .B (n_119), .C (n_2), .Y (n_177));
  A2O1A1Ixp33_ASAP7_75t_R g7326__5477(.A1 (s_axi_awsize[2]), .A2
       (n_82), .B (n_118), .C (rst_n), .Y (n_176));
  A2O1A1Ixp33_ASAP7_75t_R g7327__2398(.A1 (s_axi_awid[0]), .A2 (n_82),
       .B (n_115), .C (n_2), .Y (n_175));
  A2O1A1Ixp33_ASAP7_75t_R g7328__5107(.A1 (s_axi_awsize[1]), .A2
       (n_82), .B (n_98), .C (rst_n), .Y (n_174));
  A2O1A1Ixp33_ASAP7_75t_R g7329__6260(.A1 (s_axi_awid[2]), .A2 (n_82),
       .B (n_112), .C (n_2), .Y (n_173));
  A2O1A1Ixp33_ASAP7_75t_R g7330__4319(.A1 (s_axi_awid[3]), .A2 (n_82),
       .B (n_123), .C (rst_n), .Y (n_172));
  A2O1A1Ixp33_ASAP7_75t_R g7331__8428(.A1 (s_axi_awid[4]), .A2 (n_82),
       .B (n_113), .C (n_2), .Y (n_171));
  OAI21xp5_ASAP7_75t_R g7334__5526(.A1 (n_85), .A2 (n_128), .B
       (aw_addr_reg[1]), .Y (n_183));
  OR2x2_ASAP7_75t_R g7335__6783(.A (n_14), .B (n_152), .Y (n_182));
  AOI222xp33_ASAP7_75t_R g7338__3680(.A1 (n_0), .A2 (n_306), .B1
       (n_83), .B2 (s_axi_araddr[3]), .C1 (n_1), .C2 (ar_addr_reg[3]),
       .Y (n_170));
  AOI222xp33_ASAP7_75t_R g7339__1617(.A1 (n_80), .A2 (n_74), .B1
       (n_83), .B2 (s_axi_araddr[0]), .C1 (n_35), .C2 (ar_addr_reg[0]),
       .Y (n_169));
  AOI222xp33_ASAP7_75t_R g7340__2802(.A1 (n_80), .A2 (n_315), .B1
       (n_83), .B2 (s_axi_araddr[2]), .C1 (n_35), .C2 (ar_addr_reg[2]),
       .Y (n_168));
  AOI222xp33_ASAP7_75t_R g7341__1705(.A1 (n_0), .A2 (n_313), .B1
       (n_83), .B2 (s_axi_araddr[4]), .C1 (n_35), .C2 (ar_addr_reg[4]),
       .Y (n_167));
  AOI222xp33_ASAP7_75t_R g7342__5122(.A1 (n_80), .A2 (n_310), .B1
       (n_83), .B2 (s_axi_araddr[6]), .C1 (n_35), .C2 (ar_addr_reg[6]),
       .Y (n_166));
  AOI222xp33_ASAP7_75t_R g7343__8246(.A1 (n_80), .A2 (n_308), .B1
       (n_83), .B2 (s_axi_araddr[7]), .C1 (n_1), .C2 (ar_addr_reg[7]),
       .Y (n_165));
  AOI222xp33_ASAP7_75t_R g7344__7098(.A1 (n_307), .A2 (n_80), .B1
       (n_83), .B2 (s_axi_araddr[8]), .C1 (n_35), .C2 (ar_addr_reg[8]),
       .Y (n_164));
  AOI222xp33_ASAP7_75t_R g7345__6131(.A1 (n_316), .A2 (n_0), .B1
       (n_83), .B2 (s_axi_araddr[9]), .C1 (n_1), .C2 (ar_addr_reg[9]),
       .Y (n_163));
  AOI222xp33_ASAP7_75t_R g7346__1881(.A1 (n_309), .A2 (n_0), .B1
       (n_83), .B2 (s_axi_araddr[10]), .C1 (n_1), .C2
       (ar_addr_reg[10]), .Y (n_162));
  AOI222xp33_ASAP7_75t_R g7347__5115(.A1 (n_317), .A2 (n_80), .B1
       (n_83), .B2 (s_axi_araddr[11]), .C1 (n_1), .C2
       (ar_addr_reg[11]), .Y (n_161));
  AOI222xp33_ASAP7_75t_R g7348__7482(.A1 (n_318), .A2 (n_0), .B1
       (n_83), .B2 (s_axi_araddr[13]), .C1 (n_35), .C2
       (ar_addr_reg[13]), .Y (n_160));
  AOI222xp33_ASAP7_75t_R g7349__4733(.A1 (n_305), .A2 (n_0), .B1
       (n_83), .B2 (s_axi_araddr[12]), .C1 (n_35), .C2
       (ar_addr_reg[12]), .Y (n_159));
  AOI222xp33_ASAP7_75t_R g7350__6161(.A1 (n_304), .A2 (n_80), .B1
       (n_83), .B2 (s_axi_araddr[14]), .C1 (n_1), .C2
       (ar_addr_reg[14]), .Y (n_158));
  AOI222xp33_ASAP7_75t_R g7351__9315(.A1 (n_319), .A2 (n_80), .B1
       (n_83), .B2 (s_axi_araddr[15]), .C1 (n_1), .C2
       (ar_addr_reg[15]), .Y (n_157));
  AOI222xp33_ASAP7_75t_R g7352__9945(.A1 (n_0), .A2 (n_311), .B1
       (n_83), .B2 (s_axi_araddr[5]), .C1 (n_1), .C2 (ar_addr_reg[5]),
       .Y (n_156));
  AOI22xp5_ASAP7_75t_R g7353__2883(.A1 (n_92), .A2 (n_0), .B1
       (r_count[2]), .B2 (n_1), .Y (n_155));
  XNOR2xp5_ASAP7_75t_R g7354__2346(.A (r_count[4]), .B (n_126), .Y
       (n_154));
  INVx1_ASAP7_75t_R g7373(.A (n_151), .Y (n_150));
  INVx1_ASAP7_75t_R g7374(.A (n_147), .Y (n_148));
  AOI22xp5_ASAP7_75t_R g7375__1666(.A1 (n_70), .A2 (n_80), .B1
       (r_count[1]), .B2 (n_35), .Y (n_146));
  A2O1A1Ixp33_ASAP7_75t_R g7376__7410(.A1 (s_axi_wready), .A2 (n_65),
       .B (n_82), .C (rst_n), .Y (n_145));
  A2O1A1Ixp33_ASAP7_75t_R g7377__6417(.A1 (n_41), .A2 (n_42), .B
       (n_79), .C (n_2), .Y (n_144));
  XNOR2xp5_ASAP7_75t_R g7378__5477(.A (r_count[3]), .B (n_89), .Y
       (n_143));
  XNOR2xp5_ASAP7_75t_R g7379__2398(.A (aw_addr_reg[0]), .B (n_86), .Y
       (n_142));
  XOR2xp5_ASAP7_75t_R g7381__6260(.A (bram_waddr[5]), .B (n_90), .Y
       (n_140));
  NAND2xp5_ASAP7_75t_R g7383__4319(.A (n_134), .B (n_132), .Y (n_139));
  NOR2xp33_ASAP7_75t_R g7384__8428(.A (n_133), .B (n_130), .Y (n_138));
  XOR2xp5_ASAP7_75t_R g7387__3680(.A (bram_waddr[3]), .B (n_88), .Y
       (n_135));
  AOI21xp5_ASAP7_75t_R g7388__1617(.A1 (w_state[0]), .A2 (w_state[1]),
       .B (n_111), .Y (n_153));
  OR2x2_ASAP7_75t_R g7389__2802(.A (n_15), .B (n_126), .Y (n_152));
  AND2x2_ASAP7_75t_R g7390__1705(.A (n_2), .B (n_124), .Y (n_151));
  AND3x1_ASAP7_75t_R g7391__5122(.A (n_125), .B (rst_n), .C (n_17), .Y
       (n_149));
  NAND2xp5_ASAP7_75t_R g7392__8246(.A (n_36), .B (n_125), .Y (n_147));
  INVx1_ASAP7_75t_R g7393(.A (n_131), .Y (n_132));
  INVx1_ASAP7_75t_R g7394(.A (n_129), .Y (n_130));
  INVx1_ASAP7_75t_R g7395(.A (n_127), .Y (n_128));
  INVx1_ASAP7_75t_R g7396(.A (n_125), .Y (n_124));
  AND2x2_ASAP7_75t_R g7397__7098(.A (s_axi_bid[3]), .B (n_81), .Y
       (n_123));
  A2O1A1Ixp33_ASAP7_75t_R g7398__6131(.A1 (ar_len_reg[6]), .A2 (n_488),
       .B (n_50), .C (rst_n), .Y (n_122));
  A2O1A1Ixp33_ASAP7_75t_R g7399__1881(.A1 (ar_len_reg[5]), .A2 (n_515),
       .B (n_57), .C (rst_n), .Y (n_121));
  A2O1A1Ixp33_ASAP7_75t_R g7400__5115(.A1 (ar_len_reg[4]), .A2 (n_515),
       .B (n_32), .C (rst_n), .Y (n_120));
  NOR2xp33_ASAP7_75t_R g7401__7482(.A (n_20), .B (n_82), .Y (n_119));
  NOR2xp33_ASAP7_75t_R g7402__4733(.A (n_19), .B (n_82), .Y (n_118));
  A2O1A1Ixp33_ASAP7_75t_R g7403__6161(.A1 (ar_len_reg[2]), .A2 (n_488),
       .B (n_31), .C (n_2), .Y (n_117));
  AND2x2_ASAP7_75t_R g7404__9315(.A (s_axi_bid[1]), .B (n_81), .Y
       (n_116));
  AND2x2_ASAP7_75t_R g7405__9945(.A (s_axi_bid[0]), .B (n_81), .Y
       (n_115));
  A2O1A1Ixp33_ASAP7_75t_R g7406__2883(.A1 (ar_len_reg[3]), .A2 (n_515),
       .B (n_30), .C (rst_n), .Y (n_114));
  AND2x2_ASAP7_75t_R g7407__2346(.A (s_axi_bid[4]), .B (n_81), .Y
       (n_113));
  AND2x2_ASAP7_75t_R g7408__1666(.A (s_axi_bid[2]), .B (n_81), .Y
       (n_112));
  NAND2xp5_ASAP7_75t_R g7409__7410(.A (bram_waddr[1]), .B (n_78), .Y
       (n_134));
  NOR2xp33_ASAP7_75t_R g7410__6417(.A (bram_waddr[2]), .B (n_77), .Y
       (n_133));
  NOR2xp33_ASAP7_75t_R g7411__5477(.A (bram_waddr[1]), .B (n_78), .Y
       (n_131));
  NAND2xp5_ASAP7_75t_R g7412__2398(.A (bram_waddr[2]), .B (n_77), .Y
       (n_129));
  NAND2xp5_ASAP7_75t_R g7413__5107(.A (aw_addr_reg[0]), .B (n_87), .Y
       (n_127));
  OR2x2_ASAP7_75t_R g7414__6260(.A (n_11), .B (n_89), .Y (n_126));
  NAND2xp5_ASAP7_75t_R g7415__4319(.A (n_489), .B (n_81), .Y (n_125));
  INVx1_ASAP7_75t_R g7416(.A (n_110), .Y (n_111));
  A2O1A1Ixp33_ASAP7_75t_R g7417__8428(.A1 (ar_len_reg[0]), .A2 (n_488),
       .B (n_49), .C (n_2), .Y (n_109));
  A2O1A1Ixp33_ASAP7_75t_R g7418__5526(.A1 (ar_size_reg[1]), .A2
       (n_515), .B (n_56), .C (rst_n), .Y (n_108));
  A2O1A1Ixp33_ASAP7_75t_R g7419__6783(.A1 (ar_size_reg[0]), .A2
       (n_488), .B (n_55), .C (n_2), .Y (n_107));
  A2O1A1Ixp33_ASAP7_75t_R g7420__3680(.A1 (ar_size_reg[2]), .A2
       (n_515), .B (n_54), .C (rst_n), .Y (n_106));
  A2O1A1Ixp33_ASAP7_75t_R g7421__1617(.A1 (s_axi_rid[0]), .A2 (n_488),
       .B (n_53), .C (n_2), .Y (n_105));
  A2O1A1Ixp33_ASAP7_75t_R g7422__2802(.A1 (s_axi_rid[1]), .A2 (n_515),
       .B (n_52), .C (rst_n), .Y (n_104));
  A2O1A1Ixp33_ASAP7_75t_R g7423__1705(.A1 (s_axi_rid[2]), .A2 (n_488),
       .B (n_33), .C (n_2), .Y (n_103));
  A2O1A1Ixp33_ASAP7_75t_R g7424__5122(.A1 (s_axi_rid[3]), .A2 (n_515),
       .B (n_51), .C (rst_n), .Y (n_102));
  A2O1A1Ixp33_ASAP7_75t_R g7425__8246(.A1 (s_axi_rid[4]), .A2 (n_488),
       .B (n_61), .C (n_2), .Y (n_101));
  A2O1A1Ixp33_ASAP7_75t_R g7426__7098(.A1 (ar_len_reg[7]), .A2 (n_515),
       .B (n_59), .C (rst_n), .Y (n_100));
  A2O1A1Ixp33_ASAP7_75t_R g7427__6131(.A1 (ar_len_reg[1]), .A2 (n_488),
       .B (n_58), .C (n_2), .Y (n_99));
  NOR2xp33_ASAP7_75t_R g7428__1881(.A (n_9), .B (n_82), .Y (n_98));
  A2O1A1Ixp33_ASAP7_75t_R g7429__5115(.A1 (s_axi_arready), .A2 (n_314),
       .B (n_60), .C (rst_n), .Y (n_97));
  XOR2xp5_ASAP7_75t_R g7430__7482(.A (n_312), .B (n_29), .Y (n_96));
  A2O1A1Ixp33_ASAP7_75t_R g7431__4733(.A1 (s_axi_rvalid), .A2 (n_321),
       .B (n_62), .C (n_2), .Y (n_95));
  NOR2xp33_ASAP7_75t_R g7432__6161(.A (n_68), .B (n_66), .Y (n_94));
  A2O1A1Ixp33_ASAP7_75t_R g7433__9315(.A1 (n_8), .A2 (n_321), .B
       (n_62), .C (rst_n), .Y (n_93));
  XNOR2xp5_ASAP7_75t_R g7434__9945(.A (r_count[2]), .B (n_38), .Y
       (n_92));
  AOI31xp33_ASAP7_75t_R g7435__2883(.A1 (s_axi_bready), .A2
       (w_state[1]), .A3 (s_axi_bvalid), .B (n_64), .Y (n_110));
  INVx1_ASAP7_75t_R g7436(.A (n_86), .Y (n_87));
  INVx1_ASAP7_75t_R g7437(.A (n_82), .Y (n_81));
  NOR2xp33_ASAP7_75t_R g7439__2346(.A (n_27), .B (n_41), .Y (n_79));
  AND2x2_ASAP7_75t_R g7441__1666(.A (n_63), .B (n_321), .Y (n_91));
  NOR2xp33_ASAP7_75t_R g7442__7410(.A (n_9), .B (n_45), .Y (n_90));
  OR2x2_ASAP7_75t_R g7443__6417(.A (n_12), .B (n_38), .Y (n_89));
  NOR2xp33_ASAP7_75t_R g7444__5477(.A (aw_size_reg[1]), .B (n_45), .Y
       (n_88));
  NAND2xp5_ASAP7_75t_R g7445__2398(.A (n_9), .B (n_44), .Y (n_86));
  NOR2xp33_ASAP7_75t_R g7446__5107(.A (aw_size_reg[1]), .B (n_46), .Y
       (n_85));
  NAND2xp5_ASAP7_75t_R g7447__6260(.A (aw_size_reg[1]), .B (n_44), .Y
       (n_84));
  NOR2x1_ASAP7_75t_R g7448__4319(.A (r_state[1]), .B (n_40), .Y (n_83));
  AND2x2_ASAP7_75t_R g7449__8428(.A (n_41), .B (n_43), .Y (n_82));
  AND2x2_ASAP7_75t_R g7450__5526(.A (n_8), .B (n_39), .Y (n_80));
  XNOR2xp5_ASAP7_75t_R g7451__6783(.A (ar_len_reg[7]), .B (r_count[7]),
       .Y (n_75));
  XNOR2xp5_ASAP7_75t_R g7452__3680(.A (ar_addr_reg[0]), .B (n_320), .Y
       (n_74));
  XOR2xp5_ASAP7_75t_R g7453__1617(.A (ar_len_reg[5]), .B (r_count[5]),
       .Y (n_73));
  XNOR2xp5_ASAP7_75t_R g7454__2802(.A (ar_len_reg[0]), .B (r_count[0]),
       .Y (n_72));
  XOR2xp5_ASAP7_75t_R g7455__1705(.A (ar_len_reg[4]), .B (r_count[4]),
       .Y (n_71));
  XOR2xp5_ASAP7_75t_R g7456__5122(.A (r_count[0]), .B (r_count[1]), .Y
       (n_70));
  XNOR2xp5_ASAP7_75t_R g7457__8246(.A (ar_len_reg[6]), .B (r_count[6]),
       .Y (n_69));
  XOR2xp5_ASAP7_75t_R g7458__7098(.A (ar_len_reg[3]), .B (r_count[3]),
       .Y (n_68));
  XNOR2xp5_ASAP7_75t_R g7459__6131(.A (ar_len_reg[1]), .B (r_count[1]),
       .Y (n_67));
  XOR2xp5_ASAP7_75t_R g7460__1881(.A (ar_len_reg[2]), .B (r_count[2]),
       .Y (n_66));
  NOR2xp33_ASAP7_75t_R g7461__5115(.A (n_9), .B (n_46), .Y (n_78));
  NOR2xp33_ASAP7_75t_R g7462__7482(.A (aw_size_reg[1]), .B (n_47), .Y
       (n_77));
  NAND2xp5_ASAP7_75t_R g7463__4733(.A (aw_size_reg[1]), .B (n_48), .Y
       (n_76));
  INVx1_ASAP7_75t_R g7464(.A (n_64), .Y (n_65));
  INVx1_ASAP7_75t_R g7465(.A (n_63), .Y (n_62));
  AND2x2_ASAP7_75t_R g7466__6161(.A (s_axi_arid[4]), .B (n_7), .Y
       (n_61));
  NOR2xp33_ASAP7_75t_R g7467__9315(.A (n_314), .B (n_298), .Y (n_60));
  AND2x2_ASAP7_75t_R g7468__9945(.A (s_axi_arlen[7]), .B (n_7), .Y
       (n_59));
  AND2x2_ASAP7_75t_R g7469__2883(.A (s_axi_arlen[1]), .B (n_7), .Y
       (n_58));
  AND2x2_ASAP7_75t_R g7470__2346(.A (s_axi_arlen[5]), .B (n_7), .Y
       (n_57));
  AND2x2_ASAP7_75t_R g7471__1666(.A (s_axi_arsize[1]), .B (n_7), .Y
       (n_56));
  AND2x2_ASAP7_75t_R g7472__7410(.A (s_axi_arsize[0]), .B (n_7), .Y
       (n_55));
  AND2x2_ASAP7_75t_R g7473__6417(.A (s_axi_arsize[2]), .B (n_7), .Y
       (n_54));
  AND2x2_ASAP7_75t_R g7474__5477(.A (s_axi_arid[0]), .B (n_7), .Y
       (n_53));
  AND2x2_ASAP7_75t_R g7475__2398(.A (s_axi_arid[1]), .B (n_7), .Y
       (n_52));
  AND2x2_ASAP7_75t_R g7476__5107(.A (s_axi_arid[3]), .B (n_7), .Y
       (n_51));
  AND2x2_ASAP7_75t_R g7477__6260(.A (s_axi_arlen[6]), .B (n_7), .Y
       (n_50));
  AND2x2_ASAP7_75t_R g7478__4319(.A (s_axi_arlen[0]), .B (n_7), .Y
       (n_49));
  NOR2xp33_ASAP7_75t_R g7479__8428(.A (n_297), .B (n_489), .Y (n_64));
  NAND2xp5_ASAP7_75t_R g7480__5526(.A (r_state[0]), .B (n_28), .Y
       (n_63));
  INVx1_ASAP7_75t_R g7481(.A (n_47), .Y (n_48));
  INVx1_ASAP7_75t_R g7482(.A (n_42), .Y (n_43));
  INVx1_ASAP7_75t_R g7483(.A (n_40), .Y (n_39));
  INVx1_ASAP7_75t_R g7484(.A (n_37), .Y (n_36));
  NAND2xp5_ASAP7_75t_R g7486__6783(.A (s_axi_bvalid), .B (n_2), .Y
       (n_34));
  AND2x2_ASAP7_75t_R g7487__3680(.A (s_axi_arid[2]), .B (n_7), .Y
       (n_33));
  AND2x2_ASAP7_75t_R g7488__1617(.A (s_axi_arlen[4]), .B (n_7), .Y
       (n_32));
  AND2x2_ASAP7_75t_R g7489__2802(.A (s_axi_arlen[2]), .B (n_7), .Y
       (n_31));
  AND2x2_ASAP7_75t_R g7490__1705(.A (s_axi_arlen[3]), .B (n_7), .Y
       (n_30));
  NAND2xp5_ASAP7_75t_R g7491__5122(.A (aw_size_reg[2]), .B (n_20), .Y
       (n_47));
  NAND2xp5_ASAP7_75t_R g7492__8246(.A (aw_size_reg[0]), .B (n_19), .Y
       (n_46));
  NAND2xp5_ASAP7_75t_R g7493__7098(.A (n_302), .B (n_301), .Y (n_29));
  NAND2xp5_ASAP7_75t_R g7494__6131(.A (aw_size_reg[2]), .B
       (aw_size_reg[0]), .Y (n_45));
  NOR2xp33_ASAP7_75t_R g7495__1881(.A (aw_size_reg[2]), .B
       (aw_size_reg[0]), .Y (n_44));
  NAND2xp5_ASAP7_75t_R g7496__5115(.A (s_axi_awready), .B
       (s_axi_awvalid), .Y (n_42));
  NOR2xp33_ASAP7_75t_R g7497__7482(.A (w_state[1]), .B (w_state[0]), .Y
       (n_41));
  NAND2xp5_ASAP7_75t_R g7498__4733(.A (rst_n), .B (bram_re), .Y (n_40));
  NAND2xp5_ASAP7_75t_R g7499__6161(.A (r_count[0]), .B (r_count[1]), .Y
       (n_38));
  NAND2xp5_ASAP7_75t_R g7500__9315(.A (w_state[0]), .B (n_2), .Y
       (n_37));
  NOR2x1_ASAP7_75t_R g7501__9945(.A (n_4), .B (bram_re), .Y (n_35));
  INVx1_ASAP7_75t_R g7504(.A (r_state[1]), .Y (n_28));
  INVx1_ASAP7_75t_R g7506(.A (s_axi_awready), .Y (n_27));
  INVx1_ASAP7_75t_R g7509(.A (bram_waddr[12]), .Y (n_26));
  INVx1_ASAP7_75t_R g7510(.A (bram_waddr[10]), .Y (n_25));
  INVx1_ASAP7_75t_R g7511(.A (bram_waddr[11]), .Y (n_24));
  INVx1_ASAP7_75t_R g7512(.A (bram_waddr[0]), .Y (n_23));
  INVx1_ASAP7_75t_R g7513(.A (bram_waddr[4]), .Y (n_22));
  INVx1_ASAP7_75t_R g7514(.A (bram_waddr[7]), .Y (n_21));
  INVx1_ASAP7_75t_R g7515(.A (aw_size_reg[0]), .Y (n_20));
  INVx1_ASAP7_75t_R g7516(.A (aw_size_reg[2]), .Y (n_19));
  INVx1_ASAP7_75t_R g7517(.A (bram_waddr[9]), .Y (n_18));
  INVx1_ASAP7_75t_R g7518(.A (w_state[0]), .Y (n_17));
  INVx1_ASAP7_75t_R g7522(.A (bram_waddr[6]), .Y (n_16));
  INVx1_ASAP7_75t_R g7523(.A (r_count[4]), .Y (n_15));
  INVx1_ASAP7_75t_R g7524(.A (r_count[5]), .Y (n_14));
  INVx1_ASAP7_75t_R g7529(.A (r_count[6]), .Y (n_13));
  INVx1_ASAP7_75t_R g7530(.A (r_count[2]), .Y (n_12));
  INVx1_ASAP7_75t_R g7531(.A (r_count[3]), .Y (n_11));
  INVx1_ASAP7_75t_R g7532(.A (bram_waddr[8]), .Y (n_10));
  INVx1_ASAP7_75t_R g7533(.A (aw_size_reg[1]), .Y (n_9));
  INVx1_ASAP7_75t_R g7536(.A (n_488), .Y (n_7));
  INVx2_ASAP7_75t_R drc_bufs7542(.A (n_4), .Y (n_2));
  INVx1_ASAP7_75t_R drc_bufs7543(.A (rst_n), .Y (n_4));
  INVx1_ASAP7_75t_R drc_bufs7549(.A (n_5), .Y (n_1));
  INVx1_ASAP7_75t_R drc_bufs7550(.A (n_35), .Y (n_5));
  INVx1_ASAP7_75t_R drc_bufs7556(.A (n_6), .Y (n_0));
  INVx1_ASAP7_75t_R drc_bufs7557(.A (n_80), .Y (n_6));
  NOR4xp25_ASAP7_75t_R g2(.A (n_180), .B (n_63), .C (n_73), .D (n_71),
       .Y (n_490));
  BUFx2_ASAP7_75t_R drc_buf_sp7581(.A (n_488), .Y (n_515));
  FAx1_ASAP7_75t_R g7583(.A (n_22), .B (n_76), .CI (n_210), .CON
       (UNCONNECTED), .SN (n_517));
  FAx1_ASAP7_75t_R g7584(.A (n_23), .B (n_84), .CI (n_183), .CON
       (UNCONNECTED0), .SN (n_518));
  FAx1_ASAP7_75t_R g7585(.A (n_127), .B (aw_addr_reg[1]), .CI (n_85),
       .CON (UNCONNECTED1), .SN (n_519));
endmodule

module
     sram_macro_DATA_WIDTH32_ADDR_WIDTH32_MEM_DEPTH16384_INIT_FILE8h00(clk,
     bram_we, bram_waddr, bram_wdata, bram_wstrb, bram_re, bram_raddr,
     bram_rdata_out);
  input clk, bram_we, bram_re;
  input [31:0] bram_waddr, bram_wdata, bram_raddr;
  input [3:0] bram_wstrb;
  output [31:0] bram_rdata_out;
  wire clk, bram_we, bram_re;
  wire [31:0] bram_waddr, bram_wdata, bram_raddr;
  wire [3:0] bram_wstrb;
  wire [31:0] bram_rdata_out;
endmodule

module top_axi_ram(clk, rst_n, s_axi_awid, s_axi_awaddr, s_axi_awlen,
     s_axi_awsize, s_axi_awburst, s_axi_awlock, s_axi_awcache,
     s_axi_awprot, s_axi_awqos, s_axi_awregion, s_axi_awvalid,
     s_axi_awready, s_axi_wdata, s_axi_wstrb, s_axi_wlast,
     s_axi_wvalid, s_axi_wready, s_axi_bid, s_axi_bresp, s_axi_bvalid,
     s_axi_bready, s_axi_arid, s_axi_araddr, s_axi_arlen, s_axi_arsize,
     s_axi_arburst, s_axi_arlock, s_axi_arcache, s_axi_arprot,
     s_axi_arqos, s_axi_arregion, s_axi_arvalid, s_axi_arready,
     s_axi_rid, s_axi_rdata, s_axi_rresp, s_axi_rlast, s_axi_rvalid,
     s_axi_rready);
  input clk, rst_n, s_axi_awlock, s_axi_awvalid, s_axi_wlast,
       s_axi_wvalid, s_axi_bready, s_axi_arlock, s_axi_arvalid,
       s_axi_rready;
  input [4:0] s_axi_awid, s_axi_arid;
  input [31:0] s_axi_awaddr, s_axi_wdata, s_axi_araddr;
  input [7:0] s_axi_awlen, s_axi_arlen;
  input [2:0] s_axi_awsize, s_axi_awprot, s_axi_arsize, s_axi_arprot;
  input [1:0] s_axi_awburst, s_axi_arburst;
  input [3:0] s_axi_awcache, s_axi_awqos, s_axi_awregion, s_axi_wstrb,
       s_axi_arcache, s_axi_arqos, s_axi_arregion;
  output s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready,
       s_axi_rlast, s_axi_rvalid;
  output [4:0] s_axi_bid, s_axi_rid;
  output [1:0] s_axi_bresp, s_axi_rresp;
  output [31:0] s_axi_rdata;
  wire clk, rst_n, s_axi_awlock, s_axi_awvalid, s_axi_wlast,
       s_axi_wvalid, s_axi_bready, s_axi_arlock, s_axi_arvalid,
       s_axi_rready;
  wire [4:0] s_axi_awid, s_axi_arid;
  wire [31:0] s_axi_awaddr, s_axi_wdata, s_axi_araddr;
  wire [7:0] s_axi_awlen, s_axi_arlen;
  wire [2:0] s_axi_awsize, s_axi_awprot, s_axi_arsize, s_axi_arprot;
  wire [1:0] s_axi_awburst, s_axi_arburst;
  wire [3:0] s_axi_awcache, s_axi_awqos, s_axi_awregion, s_axi_wstrb,
       s_axi_arcache, s_axi_arqos, s_axi_arregion;
  wire s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready,
       s_axi_rlast, s_axi_rvalid;
  wire [4:0] s_axi_bid, s_axi_rid;
  wire [1:0] s_axi_bresp, s_axi_rresp;
  wire [31:0] s_axi_rdata;
  wire [31:0] bram_waddr_wire;
  wire [31:0] bram_raddr_wire;
  wire UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5,
       UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9;
  wire UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13,
       UNCONNECTED14, UNCONNECTED15, UNCONNECTED16, UNCONNECTED17;
  wire UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25;
  wire UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, UNCONNECTED29,
       UNCONNECTED30, UNCONNECTED31, UNCONNECTED32, UNCONNECTED33;
  wire UNCONNECTED34, UNCONNECTED35, UNCONNECTED36, UNCONNECTED37,
       UNCONNECTED38, UNCONNECTED39, UNCONNECTED40, UNCONNECTED41;
  wire UNCONNECTED42, UNCONNECTED43, UNCONNECTED44, UNCONNECTED45,
       UNCONNECTED46, UNCONNECTED47, UNCONNECTED48, UNCONNECTED49;
  wire UNCONNECTED50, UNCONNECTED51, UNCONNECTED52, UNCONNECTED53,
       UNCONNECTED54, UNCONNECTED55, UNCONNECTED56, UNCONNECTED57;
  wire UNCONNECTED58, UNCONNECTED59, UNCONNECTED60, UNCONNECTED61,
       UNCONNECTED62, UNCONNECTED63, UNCONNECTED64, UNCONNECTED65;
  wire UNCONNECTED66, UNCONNECTED67, UNCONNECTED68, UNCONNECTED69,
       UNCONNECTED70, UNCONNECTED71, UNCONNECTED72, UNCONNECTED73;
  wire UNCONNECTED74, UNCONNECTED75, UNCONNECTED76, UNCONNECTED77,
       UNCONNECTED78, UNCONNECTED79, UNCONNECTED80, UNCONNECTED81;
  wire UNCONNECTED82, UNCONNECTED83, UNCONNECTED84, UNCONNECTED85,
       UNCONNECTED86, UNCONNECTED87, UNCONNECTED88, UNCONNECTED89;
  wire UNCONNECTED90, UNCONNECTED91, UNCONNECTED92, UNCONNECTED93,
       UNCONNECTED94, UNCONNECTED95, UNCONNECTED96, UNCONNECTED97;
  wire UNCONNECTED98, UNCONNECTED99, UNCONNECTED100, UNCONNECTED101,
       UNCONNECTED102, UNCONNECTED103, UNCONNECTED104, UNCONNECTED105;
  wire UNCONNECTED106, UNCONNECTED107, UNCONNECTED108, UNCONNECTED109,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5,
       UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z8,
       UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10;
  wire UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z18;
  wire UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z22,
       UNCONNECTED_HIER_Z23, UNCONNECTED_HIER_Z24,
       UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z26;
  wire UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z28,
       UNCONNECTED_HIER_Z29, UNCONNECTED_HIER_Z30,
       UNCONNECTED_HIER_Z31, UNCONNECTED_HIER_Z32,
       UNCONNECTED_HIER_Z33, UNCONNECTED_HIER_Z34;
  wire UNCONNECTED_HIER_Z35, UNCONNECTED_HIER_Z36,
       UNCONNECTED_HIER_Z37, UNCONNECTED_HIER_Z38,
       UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z40,
       UNCONNECTED_HIER_Z41, UNCONNECTED_HIER_Z42;
  wire UNCONNECTED_HIER_Z43, UNCONNECTED_HIER_Z44,
       UNCONNECTED_HIER_Z45, UNCONNECTED_HIER_Z46,
       UNCONNECTED_HIER_Z47, UNCONNECTED_HIER_Z48,
       UNCONNECTED_HIER_Z49, UNCONNECTED_HIER_Z50;
  wire UNCONNECTED_HIER_Z51, UNCONNECTED_HIER_Z52,
       UNCONNECTED_HIER_Z53, UNCONNECTED_HIER_Z54,
       UNCONNECTED_HIER_Z55, UNCONNECTED_HIER_Z56,
       UNCONNECTED_HIER_Z57, UNCONNECTED_HIER_Z58;
  wire UNCONNECTED_HIER_Z59, UNCONNECTED_HIER_Z60,
       UNCONNECTED_HIER_Z61, UNCONNECTED_HIER_Z62,
       UNCONNECTED_HIER_Z63, UNCONNECTED_HIER_Z64,
       UNCONNECTED_HIER_Z65, UNCONNECTED_HIER_Z66;
  wire UNCONNECTED_HIER_Z67, UNCONNECTED_HIER_Z68,
       UNCONNECTED_HIER_Z69, UNCONNECTED_HIER_Z70,
       UNCONNECTED_HIER_Z71, UNCONNECTED_HIER_Z72,
       UNCONNECTED_HIER_Z73, UNCONNECTED_HIER_Z74;
  wire UNCONNECTED_HIER_Z75, UNCONNECTED_HIER_Z76,
       UNCONNECTED_HIER_Z77, UNCONNECTED_HIER_Z78,
       UNCONNECTED_HIER_Z79, UNCONNECTED_HIER_Z80,
       UNCONNECTED_HIER_Z81, UNCONNECTED_HIER_Z82;
  wire UNCONNECTED_HIER_Z83, UNCONNECTED_HIER_Z84,
       UNCONNECTED_HIER_Z85, UNCONNECTED_HIER_Z86,
       UNCONNECTED_HIER_Z87, UNCONNECTED_HIER_Z88,
       UNCONNECTED_HIER_Z89, UNCONNECTED_HIER_Z90;
  wire UNCONNECTED_HIER_Z91, UNCONNECTED_HIER_Z92,
       UNCONNECTED_HIER_Z93, UNCONNECTED_HIER_Z94,
       UNCONNECTED_HIER_Z95, UNCONNECTED_HIER_Z96,
       UNCONNECTED_HIER_Z97, UNCONNECTED_HIER_Z98;
  wire UNCONNECTED_HIER_Z99, UNCONNECTED_HIER_Z100,
       UNCONNECTED_HIER_Z101, UNCONNECTED_HIER_Z102,
       UNCONNECTED_HIER_Z103, UNCONNECTED_HIER_Z104,
       UNCONNECTED_HIER_Z105, UNCONNECTED_HIER_Z106;
  wire UNCONNECTED_HIER_Z107, UNCONNECTED_HIER_Z108,
       UNCONNECTED_HIER_Z109, UNCONNECTED_HIER_Z110,
       UNCONNECTED_HIER_Z111, UNCONNECTED_HIER_Z112,
       UNCONNECTED_HIER_Z113, UNCONNECTED_HIER_Z114;
  wire UNCONNECTED_HIER_Z115, UNCONNECTED_HIER_Z116,
       UNCONNECTED_HIER_Z117, UNCONNECTED_HIER_Z118,
       UNCONNECTED_HIER_Z119, UNCONNECTED_HIER_Z120,
       UNCONNECTED_HIER_Z121, UNCONNECTED_HIER_Z122;
  wire UNCONNECTED_HIER_Z123, UNCONNECTED_HIER_Z124,
       UNCONNECTED_HIER_Z125, UNCONNECTED_HIER_Z126,
       UNCONNECTED_HIER_Z127, UNCONNECTED_HIER_Z128,
       UNCONNECTED_HIER_Z129, UNCONNECTED_HIER_Z130;
  wire UNCONNECTED_HIER_Z131, UNCONNECTED_HIER_Z132,
       UNCONNECTED_HIER_Z133, UNCONNECTED_HIER_Z134,
       UNCONNECTED_HIER_Z135, UNCONNECTED_HIER_Z136,
       UNCONNECTED_HIER_Z137, UNCONNECTED_HIER_Z138;
  wire UNCONNECTED_HIER_Z139, UNCONNECTED_HIER_Z140,
       UNCONNECTED_HIER_Z141, UNCONNECTED_HIER_Z142, bram_re_wire,
       bram_we_wire;
  assign s_axi_rresp[0] = 1'b0;
  assign s_axi_rresp[1] = 1'b0;
  assign s_axi_bresp[0] = 1'b0;
  assign s_axi_bresp[1] = 1'b0;
  axi_ctrl_ADDR_WIDTH32_DATA_WIDTH32_ID_WIDTH5_ADDR_MASK32h0000ffff
       u_axi_ctrl(.clk (clk), .rst_n (rst_n), .s_axi_awid (s_axi_awid),
       .s_axi_awaddr ({UNCONNECTED_HIER_Z14, UNCONNECTED_HIER_Z13,
       UNCONNECTED_HIER_Z12, UNCONNECTED_HIER_Z11,
       UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z8,
       UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z5,
       UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z,
       s_axi_awaddr[15:0]}), .s_axi_awlen ({UNCONNECTED_HIER_Z22,
       UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z20,
       UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z18,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z15}), .s_axi_awsize (s_axi_awsize),
       .s_axi_awburst ({UNCONNECTED_HIER_Z24, UNCONNECTED_HIER_Z23}),
       .s_axi_awlock (UNCONNECTED_HIER_Z25), .s_axi_awcache
       ({UNCONNECTED_HIER_Z29, UNCONNECTED_HIER_Z28,
       UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z26}), .s_axi_awprot
       ({UNCONNECTED_HIER_Z32, UNCONNECTED_HIER_Z31,
       UNCONNECTED_HIER_Z30}), .s_axi_awqos ({UNCONNECTED_HIER_Z36,
       UNCONNECTED_HIER_Z35, UNCONNECTED_HIER_Z34,
       UNCONNECTED_HIER_Z33}), .s_axi_awregion ({UNCONNECTED_HIER_Z40,
       UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z38,
       UNCONNECTED_HIER_Z37}), .s_axi_awvalid (s_axi_awvalid),
       .s_axi_awready (s_axi_awready), .s_axi_wdata
       ({UNCONNECTED_HIER_Z72, UNCONNECTED_HIER_Z71,
       UNCONNECTED_HIER_Z70, UNCONNECTED_HIER_Z69,
       UNCONNECTED_HIER_Z68, UNCONNECTED_HIER_Z67,
       UNCONNECTED_HIER_Z66, UNCONNECTED_HIER_Z65,
       UNCONNECTED_HIER_Z64, UNCONNECTED_HIER_Z63,
       UNCONNECTED_HIER_Z62, UNCONNECTED_HIER_Z61,
       UNCONNECTED_HIER_Z60, UNCONNECTED_HIER_Z59,
       UNCONNECTED_HIER_Z58, UNCONNECTED_HIER_Z57,
       UNCONNECTED_HIER_Z56, UNCONNECTED_HIER_Z55,
       UNCONNECTED_HIER_Z54, UNCONNECTED_HIER_Z53,
       UNCONNECTED_HIER_Z52, UNCONNECTED_HIER_Z51,
       UNCONNECTED_HIER_Z50, UNCONNECTED_HIER_Z49,
       UNCONNECTED_HIER_Z48, UNCONNECTED_HIER_Z47,
       UNCONNECTED_HIER_Z46, UNCONNECTED_HIER_Z45,
       UNCONNECTED_HIER_Z44, UNCONNECTED_HIER_Z43,
       UNCONNECTED_HIER_Z42, UNCONNECTED_HIER_Z41}), .s_axi_wstrb
       ({UNCONNECTED_HIER_Z76, UNCONNECTED_HIER_Z75,
       UNCONNECTED_HIER_Z74, UNCONNECTED_HIER_Z73}), .s_axi_wlast
       (s_axi_wlast), .s_axi_wvalid (s_axi_wvalid), .s_axi_wready
       (s_axi_wready), .s_axi_bid (s_axi_bid), .s_axi_bresp
       ({UNCONNECTED3, UNCONNECTED2}), .s_axi_bvalid (s_axi_bvalid),
       .s_axi_bready (s_axi_bready), .s_axi_arid (s_axi_arid),
       .s_axi_araddr ({UNCONNECTED_HIER_Z92, UNCONNECTED_HIER_Z91,
       UNCONNECTED_HIER_Z90, UNCONNECTED_HIER_Z89,
       UNCONNECTED_HIER_Z88, UNCONNECTED_HIER_Z87,
       UNCONNECTED_HIER_Z86, UNCONNECTED_HIER_Z85,
       UNCONNECTED_HIER_Z84, UNCONNECTED_HIER_Z83,
       UNCONNECTED_HIER_Z82, UNCONNECTED_HIER_Z81,
       UNCONNECTED_HIER_Z80, UNCONNECTED_HIER_Z79,
       UNCONNECTED_HIER_Z78, UNCONNECTED_HIER_Z77,
       s_axi_araddr[15:0]}), .s_axi_arlen (s_axi_arlen), .s_axi_arsize
       (s_axi_arsize), .s_axi_arburst ({UNCONNECTED_HIER_Z94,
       UNCONNECTED_HIER_Z93}), .s_axi_arlock (UNCONNECTED_HIER_Z95),
       .s_axi_arcache ({UNCONNECTED_HIER_Z99, UNCONNECTED_HIER_Z98,
       UNCONNECTED_HIER_Z97, UNCONNECTED_HIER_Z96}), .s_axi_arprot
       ({UNCONNECTED_HIER_Z102, UNCONNECTED_HIER_Z101,
       UNCONNECTED_HIER_Z100}), .s_axi_arqos ({UNCONNECTED_HIER_Z106,
       UNCONNECTED_HIER_Z105, UNCONNECTED_HIER_Z104,
       UNCONNECTED_HIER_Z103}), .s_axi_arregion
       ({UNCONNECTED_HIER_Z110, UNCONNECTED_HIER_Z109,
       UNCONNECTED_HIER_Z108, UNCONNECTED_HIER_Z107}), .s_axi_arvalid
       (s_axi_arvalid), .s_axi_arready (s_axi_arready), .s_axi_rid
       (s_axi_rid), .s_axi_rdata ({UNCONNECTED35, UNCONNECTED34,
       UNCONNECTED33, UNCONNECTED32, UNCONNECTED31, UNCONNECTED30,
       UNCONNECTED29, UNCONNECTED28, UNCONNECTED27, UNCONNECTED26,
       UNCONNECTED25, UNCONNECTED24, UNCONNECTED23, UNCONNECTED22,
       UNCONNECTED21, UNCONNECTED20, UNCONNECTED19, UNCONNECTED18,
       UNCONNECTED17, UNCONNECTED16, UNCONNECTED15, UNCONNECTED14,
       UNCONNECTED13, UNCONNECTED12, UNCONNECTED11, UNCONNECTED10,
       UNCONNECTED9, UNCONNECTED8, UNCONNECTED7, UNCONNECTED6,
       UNCONNECTED5, UNCONNECTED4}), .s_axi_rresp ({UNCONNECTED37,
       UNCONNECTED36}), .s_axi_rlast (s_axi_rlast), .s_axi_rvalid
       (s_axi_rvalid), .s_axi_rready (s_axi_rready), .bram_we
       (bram_we_wire), .bram_waddr ({UNCONNECTED55, UNCONNECTED54,
       UNCONNECTED53, UNCONNECTED52, UNCONNECTED51, UNCONNECTED50,
       UNCONNECTED49, UNCONNECTED48, UNCONNECTED47, UNCONNECTED46,
       UNCONNECTED45, UNCONNECTED44, UNCONNECTED43, UNCONNECTED42,
       UNCONNECTED41, UNCONNECTED40, UNCONNECTED39, UNCONNECTED38,
       bram_waddr_wire[13:0]}), .bram_wdata ({UNCONNECTED87,
       UNCONNECTED86, UNCONNECTED85, UNCONNECTED84, UNCONNECTED83,
       UNCONNECTED82, UNCONNECTED81, UNCONNECTED80, UNCONNECTED79,
       UNCONNECTED78, UNCONNECTED77, UNCONNECTED76, UNCONNECTED75,
       UNCONNECTED74, UNCONNECTED73, UNCONNECTED72, UNCONNECTED71,
       UNCONNECTED70, UNCONNECTED69, UNCONNECTED68, UNCONNECTED67,
       UNCONNECTED66, UNCONNECTED65, UNCONNECTED64, UNCONNECTED63,
       UNCONNECTED62, UNCONNECTED61, UNCONNECTED60, UNCONNECTED59,
       UNCONNECTED58, UNCONNECTED57, UNCONNECTED56}), .bram_wstrb
       ({UNCONNECTED91, UNCONNECTED90, UNCONNECTED89, UNCONNECTED88}),
       .bram_re (bram_re_wire), .bram_raddr ({UNCONNECTED109,
       UNCONNECTED108, UNCONNECTED107, UNCONNECTED106, UNCONNECTED105,
       UNCONNECTED104, UNCONNECTED103, UNCONNECTED102, UNCONNECTED101,
       UNCONNECTED100, UNCONNECTED99, UNCONNECTED98, UNCONNECTED97,
       UNCONNECTED96, UNCONNECTED95, UNCONNECTED94, UNCONNECTED93,
       UNCONNECTED92, bram_raddr_wire[13:0]}), .bram_rdata_in
       ({UNCONNECTED_HIER_Z142, UNCONNECTED_HIER_Z141,
       UNCONNECTED_HIER_Z140, UNCONNECTED_HIER_Z139,
       UNCONNECTED_HIER_Z138, UNCONNECTED_HIER_Z137,
       UNCONNECTED_HIER_Z136, UNCONNECTED_HIER_Z135,
       UNCONNECTED_HIER_Z134, UNCONNECTED_HIER_Z133,
       UNCONNECTED_HIER_Z132, UNCONNECTED_HIER_Z131,
       UNCONNECTED_HIER_Z130, UNCONNECTED_HIER_Z129,
       UNCONNECTED_HIER_Z128, UNCONNECTED_HIER_Z127,
       UNCONNECTED_HIER_Z126, UNCONNECTED_HIER_Z125,
       UNCONNECTED_HIER_Z124, UNCONNECTED_HIER_Z123,
       UNCONNECTED_HIER_Z122, UNCONNECTED_HIER_Z121,
       UNCONNECTED_HIER_Z120, UNCONNECTED_HIER_Z119,
       UNCONNECTED_HIER_Z118, UNCONNECTED_HIER_Z117,
       UNCONNECTED_HIER_Z116, UNCONNECTED_HIER_Z115,
       UNCONNECTED_HIER_Z114, UNCONNECTED_HIER_Z113,
       UNCONNECTED_HIER_Z112, UNCONNECTED_HIER_Z111}));
  sram_macro_DATA_WIDTH32_ADDR_WIDTH32_MEM_DEPTH16384_INIT_FILE8h00
       u_sram_macro(.clk (clk), .bram_we (bram_we_wire), .bram_waddr
       ({18'b0, bram_waddr_wire[13:0]}), .bram_wdata (s_axi_wdata),
       .bram_wstrb (s_axi_wstrb), .bram_re (bram_re_wire), .bram_raddr
       ({18'b0, bram_raddr_wire[13:0]}), .bram_rdata_out (s_axi_rdata));
endmodule

