
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Apr  5 2026 18:24:26 +07 (Apr  5 2026 11:24:26 UTC)

// Verification Directory fv/top_axi_ram 

module top_axi_ram(clk, rst_n, s_axi_awid, s_axi_awaddr, s_axi_awlen,
     s_axi_awsize, s_axi_awburst, s_axi_awlock, s_axi_awcache,
     s_axi_awprot, s_axi_awqos, s_axi_awregion, s_axi_awvalid,
     s_axi_awready, s_axi_wdata, s_axi_wstrb, s_axi_wlast,
     s_axi_wvalid, s_axi_wready, s_axi_bid, s_axi_bresp, s_axi_bvalid,
     s_axi_bready, s_axi_arid, s_axi_araddr, s_axi_arlen, s_axi_arsize,
     s_axi_arburst, s_axi_arlock, s_axi_arcache, s_axi_arprot,
     s_axi_arqos, s_axi_arregion, s_axi_arvalid, s_axi_arready,
     s_axi_rid, s_axi_rdata, s_axi_rresp, s_axi_rlast, s_axi_rvalid,
     s_axi_rready);
  input clk, rst_n, s_axi_awlock, s_axi_awvalid, s_axi_wlast,
       s_axi_wvalid, s_axi_bready, s_axi_arlock, s_axi_arvalid,
       s_axi_rready;
  input [4:0] s_axi_awid, s_axi_arid;
  input [31:0] s_axi_awaddr, s_axi_wdata, s_axi_araddr;
  input [7:0] s_axi_awlen, s_axi_arlen;
  input [2:0] s_axi_awsize, s_axi_awprot, s_axi_arsize, s_axi_arprot;
  input [1:0] s_axi_awburst, s_axi_arburst;
  input [3:0] s_axi_awcache, s_axi_awqos, s_axi_awregion, s_axi_wstrb,
       s_axi_arcache, s_axi_arqos, s_axi_arregion;
  output s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready,
       s_axi_rlast, s_axi_rvalid;
  output [4:0] s_axi_bid, s_axi_rid;
  output [1:0] s_axi_bresp, s_axi_rresp;
  output [31:0] s_axi_rdata;
  wire clk, rst_n, s_axi_awlock, s_axi_awvalid, s_axi_wlast,
       s_axi_wvalid, s_axi_bready, s_axi_arlock, s_axi_arvalid,
       s_axi_rready;
  wire [4:0] s_axi_awid, s_axi_arid;
  wire [31:0] s_axi_awaddr, s_axi_wdata, s_axi_araddr;
  wire [7:0] s_axi_awlen, s_axi_arlen;
  wire [2:0] s_axi_awsize, s_axi_awprot, s_axi_arsize, s_axi_arprot;
  wire [1:0] s_axi_awburst, s_axi_arburst;
  wire [3:0] s_axi_awcache, s_axi_awqos, s_axi_awregion, s_axi_wstrb,
       s_axi_arcache, s_axi_arqos, s_axi_arregion;
  wire s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready,
       s_axi_rlast, s_axi_rvalid;
  wire [4:0] s_axi_bid, s_axi_rid;
  wire [1:0] s_axi_bresp, s_axi_rresp;
  wire [31:0] s_axi_rdata;
  wire [9:0] u_sram_macro_sram_addr;
  wire [31:0] bram_waddr_wire;
  wire [31:0] u_axi_ctrl_ar_addr_reg;
  wire [2:0] u_axi_ctrl_ar_size_reg;
  wire [1:0] u_axi_ctrl_w_state;
  wire [1:0] u_axi_ctrl_r_state;
  wire [7:0] u_axi_ctrl_ar_len_reg;
  wire [31:0] u_axi_ctrl_aw_addr_reg;
  wire [2:0] u_axi_ctrl_aw_size_reg;
  wire [7:0] u_axi_ctrl_r_count;
  wire UNCONNECTED, bram_re_wire, n_0, n_1, n_2, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_205, n_206, n_207, n_208, n_209, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_269, n_272, n_273, n_274, n_275;
  wire n_276, n_277, n_278, n_279, n_280, n_281, n_282, n_283;
  wire n_284, n_285, n_286, n_362, n_432, n_529, u_axi_ctrl_n_464,
       u_axi_ctrl_n_1173;
  wire u_sram_macro_sram_banksel;
  assign s_axi_rresp[0] = 1'b0;
  assign s_axi_rresp[1] = 1'b0;
  assign s_axi_bresp[0] = 1'b0;
  assign s_axi_bresp[1] = 1'b0;
  srambank_256x4x32_6t122 u_sram_macro_u_sram_macro(.banksel
       (u_sram_macro_sram_banksel), .clk (clk), .wd (s_axi_wdata),
       .read (bram_re_wire), .write (n_214), .ADDRESS
       (u_sram_macro_sram_addr), .dataout (s_axi_rdata));
  INVx1_ASAP7_75t_R g4534(.A (u_axi_ctrl_n_464), .Y (n_269));
  INVx1_ASAP7_75t_R g4536(.A (s_axi_wlast), .Y (n_230));
  AO222x2_ASAP7_75t_R g5261__2398(.A1 (n_218), .A2 (s_axi_araddr[11]),
       .B1 (n_277), .B2 (n_216), .C1 (n_214), .C2 (bram_waddr_wire[9]),
       .Y (u_sram_macro_sram_addr[9]));
  AO222x2_ASAP7_75t_R g5262__5107(.A1 (n_218), .A2 (s_axi_araddr[10]),
       .B1 (n_274), .B2 (n_216), .C1 (n_214), .C2 (bram_waddr_wire[8]),
       .Y (u_sram_macro_sram_addr[8]));
  AO222x2_ASAP7_75t_R g5263__6260(.A1 (n_218), .A2 (s_axi_araddr[9]),
       .B1 (n_276), .B2 (n_216), .C1 (n_214), .C2 (bram_waddr_wire[7]),
       .Y (u_sram_macro_sram_addr[7]));
  XNOR2xp5_ASAP7_75t_R g5264__4319(.A (u_axi_ctrl_ar_addr_reg[11]), .B
       (n_229), .Y (n_277));
  OA21x2_ASAP7_75t_R g5265__8428(.A1 (u_axi_ctrl_ar_addr_reg[10]), .A2
       (n_228), .B (n_229), .Y (n_274));
  AO222x2_ASAP7_75t_R g5266__5526(.A1 (n_218), .A2 (s_axi_araddr[8]),
       .B1 (n_275), .B2 (n_216), .C1 (n_214), .C2 (bram_waddr_wire[6]),
       .Y (u_sram_macro_sram_addr[6]));
  NAND2xp5_ASAP7_75t_R g5267__6783(.A (u_axi_ctrl_ar_addr_reg[10]), .B
       (n_228), .Y (n_229));
  AO222x2_ASAP7_75t_R g5268__3680(.A1 (n_218), .A2 (s_axi_araddr[7]),
       .B1 (n_280), .B2 (n_216), .C1 (n_214), .C2 (bram_waddr_wire[5]),
       .Y (u_sram_macro_sram_addr[5]));
  AOI21xp5_ASAP7_75t_R g5269__1617(.A1 (n_227), .A2 (n_201), .B
       (n_228), .Y (n_276));
  NOR2xp33_ASAP7_75t_R g5270__2802(.A (n_201), .B (n_227), .Y (n_228));
  AO222x2_ASAP7_75t_R g5271__1705(.A1 (n_216), .A2 (n_281), .B1
       (n_218), .B2 (s_axi_araddr[6]), .C1 (n_214), .C2
       (bram_waddr_wire[4]), .Y (u_sram_macro_sram_addr[4]));
  OA21x2_ASAP7_75t_R g5272__5122(.A1 (u_axi_ctrl_ar_addr_reg[8]), .A2
       (n_226), .B (n_227), .Y (n_275));
  NAND2xp5_ASAP7_75t_R g5273__8246(.A (u_axi_ctrl_ar_addr_reg[8]), .B
       (n_226), .Y (n_227));
  AOI21xp5_ASAP7_75t_R g5274__7098(.A1 (n_225), .A2 (n_200), .B
       (n_226), .Y (n_280));
  NOR2xp33_ASAP7_75t_R g5275__6131(.A (n_200), .B (n_225), .Y (n_226));
  AO222x2_ASAP7_75t_R g5276__1881(.A1 (n_216), .A2 (n_283), .B1
       (n_218), .B2 (s_axi_araddr[5]), .C1 (n_214), .C2
       (bram_waddr_wire[3]), .Y (u_sram_macro_sram_addr[3]));
  AOI22xp5_ASAP7_75t_R g5277__5115(.A1 (u_axi_ctrl_ar_addr_reg[6]), .A2
       (n_224), .B1 (u_axi_ctrl_ar_size_reg[1]), .B2 (n_208), .Y
       (n_225));
  XOR2xp5_ASAP7_75t_R g5278__7482(.A (u_axi_ctrl_ar_addr_reg[6]), .B
       (n_224), .Y (n_281));
  AO222x2_ASAP7_75t_R g5279__4733(.A1 (n_216), .A2 (n_278), .B1
       (n_218), .B2 (s_axi_araddr[4]), .C1 (n_214), .C2
       (bram_waddr_wire[2]), .Y (u_sram_macro_sram_addr[2]));
  XOR2xp5_ASAP7_75t_R g5280__6161(.A (u_axi_ctrl_ar_addr_reg[5]), .B
       (n_223), .Y (n_283));
  AO22x1_ASAP7_75t_R g5281__9315(.A1 (u_axi_ctrl_ar_addr_reg[5]), .A2
       (n_223), .B1 (u_axi_ctrl_ar_size_reg[1]), .B2 (n_211), .Y
       (n_224));
  AO222x2_ASAP7_75t_R g5282__9945(.A1 (n_216), .A2 (n_279), .B1
       (n_218), .B2 (s_axi_araddr[3]), .C1 (n_214), .C2
       (bram_waddr_wire[1]), .Y (u_sram_macro_sram_addr[1]));
  OAI21xp5_ASAP7_75t_R g5283__2883(.A1 (u_axi_ctrl_ar_size_reg[1]), .A2
       (n_207), .B (n_222), .Y (n_223));
  OAI21xp5_ASAP7_75t_R g5284__2346(.A1 (n_212), .A2 (n_221), .B
       (u_axi_ctrl_ar_addr_reg[4]), .Y (n_222));
  AO222x2_ASAP7_75t_R g5285__1666(.A1 (n_216), .A2 (n_282), .B1
       (n_218), .B2 (s_axi_araddr[2]), .C1 (n_214), .C2
       (bram_waddr_wire[0]), .Y (u_sram_macro_sram_addr[0]));
  XOR2xp5_ASAP7_75t_R g5286__7410(.A (n_215), .B (n_221), .Y (n_278));
  AOI21xp5_ASAP7_75t_R g5287__6417(.A1 (n_220), .A2 (n_205), .B
       (n_221), .Y (n_279));
  NOR2xp33_ASAP7_75t_R g5288__5477(.A (n_205), .B (n_220), .Y (n_221));
  AOI22xp5_ASAP7_75t_R g5289__2398(.A1 (u_axi_ctrl_ar_addr_reg[2]), .A2
       (n_219), .B1 (u_axi_ctrl_ar_size_reg[1]), .B2 (n_209), .Y
       (n_220));
  XOR2xp5_ASAP7_75t_R g5290__5107(.A (u_axi_ctrl_ar_addr_reg[2]), .B
       (n_219), .Y (n_282));
  OR2x2_ASAP7_75t_R g5291__6260(.A (n_214), .B (bram_re_wire), .Y
       (u_sram_macro_sram_banksel));
  AO22x1_ASAP7_75t_R g5292__4319(.A1 (u_axi_ctrl_ar_addr_reg[1]), .A2
       (n_217), .B1 (u_axi_ctrl_ar_size_reg[1]), .B2 (n_206), .Y
       (n_219));
  OAI21xp5_ASAP7_75t_R g5293__8428(.A1 (u_axi_ctrl_n_1173), .A2
       (s_axi_rlast), .B (n_284), .Y (bram_re_wire));
  NAND2xp5_ASAP7_75t_R g5294__5526(.A (n_272), .B (n_273), .Y (n_217));
  NOR2x1_ASAP7_75t_R g5295__6783(.A (n_214), .B (n_284), .Y (n_218));
  XOR2xp5_ASAP7_75t_R g5296__3680(.A (u_axi_ctrl_ar_addr_reg[4]), .B
       (n_212), .Y (n_215));
  AND2x2_ASAP7_75t_R g5297__1617(.A (n_362), .B (n_284), .Y (n_216));
  NAND2xp5_ASAP7_75t_R g5298__2802(.A (u_axi_ctrl_ar_addr_reg[0]), .B
       (n_213), .Y (n_273));
  INVx1_ASAP7_75t_R g5299(.A (n_214), .Y (n_362));
  NAND3xp33_ASAP7_75t_R g5300__1705(.A (s_axi_rready), .B (n_7), .C
       (s_axi_rvalid), .Y (u_axi_ctrl_n_1173));
  AND4x1_ASAP7_75t_R g5301__5122(.A (s_axi_wvalid), .B (n_13), .C
       (s_axi_wready), .D (u_axi_ctrl_w_state[0]), .Y (n_214));
  INVx1_ASAP7_75t_R g5302(.A (n_286), .Y (n_213));
  NAND2xp5_ASAP7_75t_R g5303__8246(.A (n_199), .B (n_206), .Y (n_286));
  OR2x2_ASAP7_75t_R g5304__7098(.A (n_285), .B (u_axi_ctrl_n_464), .Y
       (n_284));
  NAND2xp5_ASAP7_75t_R g5305__6131(.A (n_199), .B (n_209), .Y (n_272));
  AND2x2_ASAP7_75t_R g5306__1881(.A (n_199), .B (n_211), .Y (n_212));
  NOR2xp33_ASAP7_75t_R g5308__5115(.A (u_axi_ctrl_ar_size_reg[0]), .B
       (n_202), .Y (n_211));
  NOR2xp33_ASAP7_75t_R g5309__7482(.A (u_axi_ctrl_r_state[0]), .B
       (n_24), .Y (n_7));
  NOR2xp33_ASAP7_75t_R g5310__4733(.A (u_axi_ctrl_ar_size_reg[2]), .B
       (n_203), .Y (n_209));
  INVx1_ASAP7_75t_R g5311(.A (n_207), .Y (n_208));
  NAND2xp5_ASAP7_75t_R g5312__6161(.A (s_axi_arready), .B
       (s_axi_arvalid), .Y (u_axi_ctrl_n_464));
  NAND2xp5_ASAP7_75t_R g5313__9315(.A (u_axi_ctrl_ar_size_reg[0]), .B
       (u_axi_ctrl_ar_size_reg[2]), .Y (n_207));
  NOR2xp33_ASAP7_75t_R g5314__9945(.A (u_axi_ctrl_ar_size_reg[0]), .B
       (u_axi_ctrl_ar_size_reg[2]), .Y (n_206));
  OR2x2_ASAP7_75t_R g5315__2883(.A (u_axi_ctrl_r_state[0]), .B
       (u_axi_ctrl_r_state[1]), .Y (n_285));
  INVx1_ASAP7_75t_R g5316(.A (u_axi_ctrl_ar_addr_reg[3]), .Y (n_205));
  INVx1_ASAP7_75t_R g5318(.A (u_axi_ctrl_ar_size_reg[0]), .Y (n_203));
  INVx1_ASAP7_75t_R g5319(.A (u_axi_ctrl_ar_size_reg[2]), .Y (n_202));
  INVx1_ASAP7_75t_R g5320(.A (u_axi_ctrl_ar_addr_reg[9]), .Y (n_201));
  INVx1_ASAP7_75t_R g5321(.A (u_axi_ctrl_ar_addr_reg[7]), .Y (n_200));
  INVx1_ASAP7_75t_R g5322(.A (u_axi_ctrl_ar_size_reg[1]), .Y (n_199));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[0] (.CLK (clk), .D
       (n_137), .QN (u_axi_ctrl_ar_addr_reg[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[1] (.CLK (clk), .D
       (n_161), .QN (u_axi_ctrl_ar_addr_reg[1]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[2] (.CLK (clk), .D
       (n_136), .QN (u_axi_ctrl_ar_addr_reg[2]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[3] (.CLK (clk), .D
       (n_135), .QN (u_axi_ctrl_ar_addr_reg[3]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[4] (.CLK (clk), .D
       (n_139), .QN (u_axi_ctrl_ar_addr_reg[4]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[5] (.CLK (clk), .D
       (n_133), .QN (u_axi_ctrl_ar_addr_reg[5]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[6] (.CLK (clk), .D
       (n_134), .QN (u_axi_ctrl_ar_addr_reg[6]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[7] (.CLK (clk), .D
       (n_132), .QN (u_axi_ctrl_ar_addr_reg[7]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[8] (.CLK (clk), .D
       (n_131), .QN (u_axi_ctrl_ar_addr_reg[8]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[9] (.CLK (clk), .D
       (n_130), .QN (u_axi_ctrl_ar_addr_reg[9]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[10] (.CLK (clk), .D
       (n_140), .QN (u_axi_ctrl_ar_addr_reg[10]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_addr_reg_reg[11] (.CLK (clk), .D
       (n_129), .QN (u_axi_ctrl_ar_addr_reg[11]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_len_reg_reg[0] (.CLK (clk), .D
       (n_111), .QN (u_axi_ctrl_ar_len_reg[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_len_reg_reg[1] (.CLK (clk), .D
       (n_113), .QN (u_axi_ctrl_ar_len_reg[1]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_len_reg_reg[2] (.CLK (clk), .D
       (n_86), .QN (u_axi_ctrl_ar_len_reg[2]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_len_reg_reg[3] (.CLK (clk), .D
       (n_96), .QN (u_axi_ctrl_ar_len_reg[3]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_len_reg_reg[4] (.CLK (clk), .D
       (n_95), .QN (u_axi_ctrl_ar_len_reg[4]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_len_reg_reg[5] (.CLK (clk), .D
       (n_94), .QN (u_axi_ctrl_ar_len_reg[5]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_len_reg_reg[6] (.CLK (clk), .D
       (n_93), .QN (u_axi_ctrl_ar_len_reg[6]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_len_reg_reg[7] (.CLK (clk), .D
       (n_91), .QN (u_axi_ctrl_ar_len_reg[7]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_size_reg_reg[0] (.CLK (clk), .D
       (n_89), .QN (u_axi_ctrl_ar_size_reg[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_size_reg_reg[1] (.CLK (clk), .D
       (n_104), .QN (u_axi_ctrl_ar_size_reg[1]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_ar_size_reg_reg[2] (.CLK (clk), .D
       (n_92), .QN (u_axi_ctrl_ar_size_reg[2]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[0] (.CLK (clk), .D
       (n_163), .QN (u_axi_ctrl_aw_addr_reg[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[1] (.CLK (clk), .D
       (n_170), .QN (u_axi_ctrl_aw_addr_reg[1]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[2] (.CLK (clk), .D
       (n_175), .QN (bram_waddr_wire[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[3] (.CLK (clk), .D
       (n_178), .QN (bram_waddr_wire[1]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[4] (.CLK (clk), .D
       (n_181), .QN (bram_waddr_wire[2]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[5] (.CLK (clk), .D
       (n_184), .QN (bram_waddr_wire[3]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[6] (.CLK (clk), .D
       (n_187), .QN (bram_waddr_wire[4]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[7] (.CLK (clk), .D
       (n_192), .QN (bram_waddr_wire[5]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[8] (.CLK (clk), .D
       (n_191), .QN (bram_waddr_wire[6]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[9] (.CLK (clk), .D
       (n_196), .QN (bram_waddr_wire[7]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[10] (.CLK (clk), .D
       (n_197), .QN (bram_waddr_wire[8]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_addr_reg_reg[11] (.CLK (clk), .D
       (n_198), .QN (bram_waddr_wire[9]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_size_reg_reg[0] (.CLK (clk), .D
       (n_144), .QN (u_axi_ctrl_aw_size_reg[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_size_reg_reg[1] (.CLK (clk), .D
       (n_146), .QN (u_axi_ctrl_aw_size_reg[1]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_aw_size_reg_reg[2] (.CLK (clk), .D
       (n_143), .QN (u_axi_ctrl_aw_size_reg[2]));
  SDFHx1_ASAP7_75t_R \u_axi_ctrl_r_count_reg[0] (.CLK (clk), .D (n_72),
       .SE (u_axi_ctrl_r_count[0]), .SI (n_50), .QN
       (u_axi_ctrl_r_count[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_r_count_reg[1] (.CLK (clk), .D
       (n_122), .QN (u_axi_ctrl_r_count[1]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_r_count_reg[2] (.CLK (clk), .D
       (n_157), .QN (u_axi_ctrl_r_count[2]));
  SDFHx1_ASAP7_75t_R \u_axi_ctrl_r_count_reg[3] (.CLK (clk), .D (n_99),
       .SE (u_axi_ctrl_r_count[3]), .SI (n_151), .QN
       (u_axi_ctrl_r_count[3]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_r_count_reg[4] (.CLK (clk), .D
       (n_167), .QN (u_axi_ctrl_r_count[4]));
  SDFHx1_ASAP7_75t_R \u_axi_ctrl_r_count_reg[5] (.CLK (clk), .D
       (n_142), .SE (u_axi_ctrl_r_count[5]), .SI (n_164), .QN
       (u_axi_ctrl_r_count[5]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_r_count_reg[6] (.CLK (clk), .D
       (n_172), .QN (u_axi_ctrl_r_count[6]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_r_count_reg[7] (.CLK (clk), .D
       (n_176), .QN (u_axi_ctrl_r_count[7]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_r_state_reg[0] (.CLK (clk), .D
       (n_38), .QN (u_axi_ctrl_r_state[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_r_state_reg[1] (.CLK (clk), .D
       (n_97), .QN (u_axi_ctrl_r_state[1]));
  DFFHQNx3_ASAP7_75t_R u_axi_ctrl_s_axi_arready_reg(.CLK (clk), .D
       (n_87), .QN (s_axi_arready));
  DFFHQNx3_ASAP7_75t_R u_axi_ctrl_s_axi_awready_reg(.CLK (clk), .D
       (n_119), .QN (s_axi_awready));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_bid_reg[0] (.CLK (clk), .D
       (n_149), .QN (s_axi_bid[0]));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_bid_reg[1] (.CLK (clk), .D
       (n_148), .QN (s_axi_bid[1]));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_bid_reg[2] (.CLK (clk), .D
       (n_147), .QN (s_axi_bid[2]));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_bid_reg[3] (.CLK (clk), .D
       (n_150), .QN (s_axi_bid[3]));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_bid_reg[4] (.CLK (clk), .D
       (n_145), .QN (s_axi_bid[4]));
  DFFHQNx3_ASAP7_75t_R u_axi_ctrl_s_axi_bvalid_reg(.CLK (clk), .D
       (n_156), .QN (s_axi_bvalid));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_rid_reg[0] (.CLK (clk), .D
       (n_90), .QN (s_axi_rid[0]));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_rid_reg[1] (.CLK (clk), .D
       (n_100), .QN (s_axi_rid[1]));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_rid_reg[2] (.CLK (clk), .D
       (n_103), .QN (s_axi_rid[2]));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_rid_reg[3] (.CLK (clk), .D
       (n_102), .QN (s_axi_rid[3]));
  DFFHQNx3_ASAP7_75t_R \u_axi_ctrl_s_axi_rid_reg[4] (.CLK (clk), .D
       (n_101), .QN (s_axi_rid[4]));
  DFFHQNx3_ASAP7_75t_R u_axi_ctrl_s_axi_rlast_reg(.CLK (clk), .D
       (n_174), .QN (s_axi_rlast));
  DFFHQNx3_ASAP7_75t_R u_axi_ctrl_s_axi_rvalid_reg(.CLK (clk), .D
       (n_85), .QN (s_axi_rvalid));
  DFFHQNx3_ASAP7_75t_R u_axi_ctrl_s_axi_wready_reg(.CLK (clk), .D
       (n_121), .QN (s_axi_wready));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_w_state_reg[0] (.CLK (clk), .D
       (n_154), .QN (u_axi_ctrl_w_state[0]));
  DFFHQNx1_ASAP7_75t_R \u_axi_ctrl_w_state_reg[1] (.CLK (clk), .D
       (n_162), .QN (u_axi_ctrl_w_state[1]));
  AOI222xp33_ASAP7_75t_R g6656__2346(.A1 (n_195), .A2
       (bram_waddr_wire[9]), .B1 (n_193), .B2 (n_77), .C1 (n_141), .C2
       (s_axi_awaddr[11]), .Y (n_198));
  AOI221xp5_ASAP7_75t_R g6658__1666(.A1 (n_141), .A2
       (s_axi_awaddr[10]), .B1 (n_195), .B2 (bram_waddr_wire[8]), .C
       (n_194), .Y (n_197));
  AOI222xp33_ASAP7_75t_R g6660__7410(.A1 (n_190), .A2
       (bram_waddr_wire[7]), .B1 (n_188), .B2 (n_77), .C1 (n_141), .C2
       (s_axi_awaddr[9]), .Y (n_196));
  NOR3xp33_ASAP7_75t_R g6662__6417(.A (n_189), .B (n_76), .C
       (bram_waddr_wire[8]), .Y (n_194));
  AO21x1_ASAP7_75t_R g6663__5477(.A1 (n_77), .A2 (n_189), .B (n_126),
       .Y (n_195));
  OAI32xp33_ASAP7_75t_R g6664__2398(.A1 (n_189), .A2 (n_16), .A3
       (bram_waddr_wire[9]), .B1 (bram_waddr_wire[8]), .B2 (n_22), .Y
       (n_193));
  AOI222xp33_ASAP7_75t_R g6665__5107(.A1 (n_141), .A2
       (s_axi_awaddr[7]), .B1 (n_186), .B2 (n_77), .C1 (n_126), .C2
       (bram_waddr_wire[5]), .Y (n_192));
  AOI322xp5_ASAP7_75t_R g6666__6260(.A1 (n_185), .A2 (n_77), .A3
       (n_14), .B1 (s_axi_awaddr[8]), .B2 (n_141), .C1 (n_190), .C2
       (bram_waddr_wire[6]), .Y (n_191));
  OAI21xp5_ASAP7_75t_R g6668__4319(.A1 (n_76), .A2 (n_185), .B (n_125),
       .Y (n_190));
  NAND3xp33_ASAP7_75t_R g6669__8428(.A (n_185), .B
       (bram_waddr_wire[6]), .C (bram_waddr_wire[7]), .Y (n_189));
  AO32x1_ASAP7_75t_R g6670__5526(.A1 (n_185), .A2 (n_18), .A3
       (bram_waddr_wire[6]), .B1 (n_14), .B2 (bram_waddr_wire[7]), .Y
       (n_188));
  AOI222xp33_ASAP7_75t_R g6671__6783(.A1 (n_141), .A2
       (s_axi_awaddr[6]), .B1 (n_77), .B2 (n_182), .C1 (n_126), .C2
       (bram_waddr_wire[4]), .Y (n_187));
  XOR2xp5_ASAP7_75t_R g6673__3680(.A (bram_waddr_wire[5]), .B (n_183),
       .Y (n_186));
  AND2x2_ASAP7_75t_R g6674__1617(.A (bram_waddr_wire[5]), .B (n_183),
       .Y (n_185));
  AOI222xp33_ASAP7_75t_R g6675__2802(.A1 (n_141), .A2
       (s_axi_awaddr[5]), .B1 (n_77), .B2 (n_179), .C1 (n_126), .C2
       (bram_waddr_wire[3]), .Y (n_184));
  XNOR2xp5_ASAP7_75t_R g6677__1705(.A (bram_waddr_wire[4]), .B (n_180),
       .Y (n_182));
  OAI22xp5_ASAP7_75t_R g6678__5122(.A1 (n_20), .A2 (n_180), .B1 (n_8),
       .B2 (n_41), .Y (n_183));
  AOI222xp33_ASAP7_75t_R g6679__8246(.A1 (n_141), .A2
       (s_axi_awaddr[4]), .B1 (n_77), .B2 (n_1), .C1 (n_126), .C2
       (bram_waddr_wire[2]), .Y (n_181));
  XOR2xp5_ASAP7_75t_R g6681__7098(.A (bram_waddr_wire[3]), .B (n_177),
       .Y (n_179));
  AOI22xp5_ASAP7_75t_R g6682__6131(.A1 (bram_waddr_wire[3]), .A2
       (n_177), .B1 (u_axi_ctrl_aw_size_reg[1]), .B2 (n_56), .Y
       (n_180));
  AOI222xp33_ASAP7_75t_R g6683__1881(.A1 (n_141), .A2
       (s_axi_awaddr[3]), .B1 (n_77), .B2 (n_0), .C1 (n_126), .C2
       (bram_waddr_wire[1]), .Y (n_178));
  OAI22xp5_ASAP7_75t_R g6687__5115(.A1 (n_21), .A2 (n_173), .B1
       (u_axi_ctrl_aw_size_reg[1]), .B2 (n_41), .Y (n_177));
  AOI32xp33_ASAP7_75t_R g6690__7482(.A1 (n_152), .A2
       (u_axi_ctrl_r_count[6]), .A3 (u_axi_ctrl_r_count[5]), .B1
       (u_axi_ctrl_r_count[7]), .B2 (n_171), .Y (n_176));
  AOI222xp33_ASAP7_75t_R g6691__4733(.A1 (n_141), .A2
       (s_axi_awaddr[2]), .B1 (n_77), .B2 (n_165), .C1 (n_126), .C2
       (bram_waddr_wire[0]), .Y (n_175));
  A2O1A1Ixp33_ASAP7_75t_R g6692__6161(.A1 (s_axi_rlast), .A2 (n_83), .B
       (n_432), .C (rst_n), .Y (n_174));
  AOI22xp5_ASAP7_75t_R g6696__9315(.A1 (u_axi_ctrl_r_count[6]), .A2
       (n_169), .B1 (u_axi_ctrl_r_count[5]), .B2 (n_153), .Y (n_172));
  AOI22xp5_ASAP7_75t_R g6698__9945(.A1 (bram_waddr_wire[1]), .A2
       (n_168), .B1 (n_8), .B2 (n_56), .Y (n_173));
  AO21x1_ASAP7_75t_R g6700__2883(.A1 (n_12), .A2 (n_73), .B (n_169), .Y
       (n_171));
  AOI222xp33_ASAP7_75t_R g6701__2346(.A1 (n_141), .A2
       (s_axi_awaddr[1]), .B1 (n_77), .B2 (n_529), .C1 (n_126), .C2
       (u_axi_ctrl_aw_addr_reg[1]), .Y (n_170));
  AOI22xp5_ASAP7_75t_R g6707__1666(.A1 (u_axi_ctrl_r_count[4]), .A2
       (n_160), .B1 (u_axi_ctrl_r_count[3]), .B2 (n_117), .Y (n_167));
  XNOR2xp5_ASAP7_75t_R g6709__6417(.A (bram_waddr_wire[0]), .B (n_159),
       .Y (n_165));
  OAI21xp5_ASAP7_75t_R g6710__5477(.A1 (u_axi_ctrl_r_count[5]), .A2
       (n_72), .B (n_164), .Y (n_169));
  OAI22xp5_ASAP7_75t_R g6711__2398(.A1 (n_17), .A2 (n_159), .B1 (n_8),
       .B2 (n_57), .Y (n_168));
  AOI222xp33_ASAP7_75t_R g6715__5107(.A1 (n_141), .A2
       (s_axi_awaddr[0]), .B1 (n_77), .B2 (n_123), .C1 (n_126), .C2
       (u_axi_ctrl_aw_addr_reg[0]), .Y (n_163));
  AOI31xp33_ASAP7_75t_R g6716__6260(.A1 (n_127), .A2 (n_2), .A3
       (u_axi_ctrl_w_state[1]), .B (n_155), .Y (n_162));
  AOI222xp33_ASAP7_75t_R g6717__4319(.A1 (n_73), .A2 (n_124), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[1]), .C1 (n_78), .C2
       (s_axi_araddr[1]), .Y (n_161));
  AOI21xp5_ASAP7_75t_R g6718__8428(.A1 (n_73), .A2 (n_10), .B (n_160),
       .Y (n_164));
  AOI32xp33_ASAP7_75t_R g6734__6783(.A1 (n_73), .A2 (n_54), .A3 (n_11),
       .B1 (u_axi_ctrl_r_count[2]), .B2 (n_128), .Y (n_157));
  AOI31xp33_ASAP7_75t_R g6735__3680(.A1 (n_98), .A2 (n_2), .A3
       (s_axi_bvalid), .B (n_120), .Y (n_156));
  NOR3xp33_ASAP7_75t_R g6736__1617(.A (n_127), .B (n_36), .C
       (u_axi_ctrl_w_state[1]), .Y (n_155));
  AOI21xp5_ASAP7_75t_R g6737__2802(.A1 (n_127), .A2 (n_35), .B (n_141),
       .Y (n_154));
  NOR2xp33_ASAP7_75t_R g6738__1705(.A (u_axi_ctrl_r_count[6]), .B
       (n_142), .Y (n_153));
  NOR2xp33_ASAP7_75t_R g6739__5122(.A (u_axi_ctrl_r_count[7]), .B
       (n_142), .Y (n_152));
  OAI21xp5_ASAP7_75t_R g6741__8246(.A1 (u_axi_ctrl_r_count[3]), .A2
       (n_72), .B (n_151), .Y (n_160));
  AOI22xp5_ASAP7_75t_R g6746__7098(.A1 (u_axi_ctrl_aw_addr_reg[1]), .A2
       (n_118), .B1 (u_axi_ctrl_aw_size_reg[1]), .B2 (n_42), .Y
       (n_159));
  A2O1A1Ixp33_ASAP7_75t_R g6747__6131(.A1 (s_axi_awid[3]), .A2 (n_75),
       .B (n_105), .C (n_2), .Y (n_150));
  A2O1A1Ixp33_ASAP7_75t_R g6748__1881(.A1 (s_axi_awid[0]), .A2 (n_75),
       .B (n_112), .C (rst_n), .Y (n_149));
  A2O1A1Ixp33_ASAP7_75t_R g6749__5115(.A1 (s_axi_awid[1]), .A2 (n_75),
       .B (n_109), .C (n_2), .Y (n_148));
  A2O1A1Ixp33_ASAP7_75t_R g6750__7482(.A1 (s_axi_awid[2]), .A2 (n_75),
       .B (n_106), .C (rst_n), .Y (n_147));
  A2O1A1Ixp33_ASAP7_75t_R g6751__4733(.A1 (s_axi_awsize[1]), .A2
       (n_75), .B (n_88), .C (n_2), .Y (n_146));
  A2O1A1Ixp33_ASAP7_75t_R g6752__6161(.A1 (s_axi_awid[4]), .A2 (n_75),
       .B (n_110), .C (rst_n), .Y (n_145));
  A2O1A1Ixp33_ASAP7_75t_R g6753__9315(.A1 (s_axi_awsize[0]), .A2
       (n_75), .B (n_108), .C (n_2), .Y (n_144));
  A2O1A1Ixp33_ASAP7_75t_R g6754__9945(.A1 (s_axi_awsize[2]), .A2
       (n_75), .B (n_107), .C (rst_n), .Y (n_143));
  AOI21xp5_ASAP7_75t_R g6756__2883(.A1 (n_73), .A2 (n_11), .B (n_128),
       .Y (n_151));
  AOI222xp33_ASAP7_75t_R g6760__2346(.A1 (n_274), .A2 (n_73), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[10]), .C1 (n_78), .C2
       (s_axi_araddr[10]), .Y (n_140));
  AOI222xp33_ASAP7_75t_R g6761__1666(.A1 (n_73), .A2 (n_278), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[4]), .C1 (n_78), .C2
       (s_axi_araddr[4]), .Y (n_139));
  NAND5xp2_ASAP7_75t_R g6762__7410(.A (n_84), .B (n_61), .C (n_62), .D
       (n_63), .E (n_64), .Y (n_138));
  AOI222xp33_ASAP7_75t_R g6763__6417(.A1 (n_73), .A2 (n_70), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[0]), .C1 (n_78), .C2
       (s_axi_araddr[0]), .Y (n_137));
  AOI222xp33_ASAP7_75t_R g6764__5477(.A1 (n_73), .A2 (n_282), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[2]), .C1 (n_78), .C2
       (s_axi_araddr[2]), .Y (n_136));
  AOI222xp33_ASAP7_75t_R g6765__2398(.A1 (n_73), .A2 (n_279), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[3]), .C1 (n_78), .C2
       (s_axi_araddr[3]), .Y (n_135));
  AOI222xp33_ASAP7_75t_R g6766__5107(.A1 (n_73), .A2 (n_281), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[6]), .C1 (n_78), .C2
       (s_axi_araddr[6]), .Y (n_134));
  AOI222xp33_ASAP7_75t_R g6767__6260(.A1 (n_73), .A2 (n_283), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[5]), .C1 (n_78), .C2
       (s_axi_araddr[5]), .Y (n_133));
  AOI222xp33_ASAP7_75t_R g6768__4319(.A1 (n_73), .A2 (n_280), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[7]), .C1 (n_78), .C2
       (s_axi_araddr[7]), .Y (n_132));
  AOI222xp33_ASAP7_75t_R g6769__8428(.A1 (n_73), .A2 (n_275), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[8]), .C1 (n_78), .C2
       (s_axi_araddr[8]), .Y (n_131));
  AOI222xp33_ASAP7_75t_R g6770__5526(.A1 (n_73), .A2 (n_276), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[9]), .C1 (n_78), .C2
       (s_axi_araddr[9]), .Y (n_130));
  AOI222xp33_ASAP7_75t_R g6771__6783(.A1 (n_277), .A2 (n_73), .B1
       (n_51), .B2 (u_axi_ctrl_ar_addr_reg[11]), .C1 (n_78), .C2
       (s_axi_araddr[11]), .Y (n_129));
  OR3x1_ASAP7_75t_R g6772__3680(.A (n_99), .B (n_10), .C (n_9), .Y
       (n_142));
  AND3x1_ASAP7_75t_R g6773__1617(.A (n_115), .B (n_2), .C (n_5), .Y
       (n_141));
  INVx1_ASAP7_75t_R g6789(.A (n_126), .Y (n_125));
  XOR2xp5_ASAP7_75t_R g6790__2802(.A (n_273), .B (n_60), .Y (n_124));
  XNOR2xp5_ASAP7_75t_R g6791__1705(.A (n_81), .B
       (u_axi_ctrl_aw_addr_reg[0]), .Y (n_123));
  AOI22xp5_ASAP7_75t_R g6792__5122(.A1 (n_65), .A2 (n_73), .B1
       (u_axi_ctrl_r_count[1]), .B2 (n_51), .Y (n_122));
  A2O1A1Ixp33_ASAP7_75t_R g6793__8246(.A1 (s_axi_wready), .A2 (n_59),
       .B (n_75), .C (n_2), .Y (n_121));
  NOR2xp33_ASAP7_75t_R g6794__7098(.A (n_36), .B (n_98), .Y (n_120));
  A2O1A1Ixp33_ASAP7_75t_R g6795__6131(.A1 (n_55), .A2 (n_39), .B
       (n_71), .C (rst_n), .Y (n_119));
  NAND2xp5_ASAP7_75t_R g6796__1881(.A (n_80), .B (n_114), .Y (n_118));
  NOR2xp33_ASAP7_75t_R g6797__5115(.A (u_axi_ctrl_r_count[4]), .B
       (n_99), .Y (n_117));
  OAI21xp5_ASAP7_75t_R g6800__7482(.A1 (n_54), .A2 (n_72), .B (n_50),
       .Y (n_128));
  OA21x2_ASAP7_75t_R g6804__6161(.A1 (n_5), .A2 (n_13), .B (n_98), .Y
       (n_127));
  NOR2x1_ASAP7_75t_R g6805__9315(.A (n_4), .B (n_115), .Y (n_126));
  A2O1A1Ixp33_ASAP7_75t_R g6806__9945(.A1 (s_axi_arlen[1]), .A2 (n_6),
       .B (n_43), .C (n_2), .Y (n_113));
  AND2x2_ASAP7_75t_R g6807__2883(.A (s_axi_bid[0]), .B (n_74), .Y
       (n_112));
  A2O1A1Ixp33_ASAP7_75t_R g6808__2346(.A1 (s_axi_arlen[0]), .A2 (n_6),
       .B (n_26), .C (rst_n), .Y (n_111));
  AND2x2_ASAP7_75t_R g6809__1666(.A (s_axi_bid[4]), .B (n_74), .Y
       (n_110));
  AND2x2_ASAP7_75t_R g6810__7410(.A (s_axi_bid[1]), .B (n_74), .Y
       (n_109));
  NOR2xp33_ASAP7_75t_R g6811__6417(.A (n_15), .B (n_75), .Y (n_108));
  NOR2xp33_ASAP7_75t_R g6812__5477(.A (n_19), .B (n_75), .Y (n_107));
  AND2x2_ASAP7_75t_R g6813__2398(.A (s_axi_bid[2]), .B (n_74), .Y
       (n_106));
  AND2x2_ASAP7_75t_R g6814__5107(.A (s_axi_bid[3]), .B (n_74), .Y
       (n_105));
  A2O1A1Ixp33_ASAP7_75t_R g6815__6260(.A1 (s_axi_arsize[1]), .A2 (n_6),
       .B (n_27), .C (rst_n), .Y (n_104));
  A2O1A1Ixp33_ASAP7_75t_R g6816__4319(.A1 (s_axi_arid[2]), .A2 (n_6),
       .B (n_29), .C (n_2), .Y (n_103));
  A2O1A1Ixp33_ASAP7_75t_R g6817__8428(.A1 (s_axi_arid[3]), .A2 (n_6),
       .B (n_34), .C (n_2), .Y (n_102));
  A2O1A1Ixp33_ASAP7_75t_R g6818__5526(.A1 (s_axi_arid[4]), .A2 (n_6),
       .B (n_47), .C (rst_n), .Y (n_101));
  A2O1A1Ixp33_ASAP7_75t_R g6819__6783(.A1 (s_axi_arid[1]), .A2 (n_6),
       .B (n_33), .C (rst_n), .Y (n_100));
  NAND2xp5_ASAP7_75t_R g6820__3680(.A (n_362), .B (n_74), .Y (n_115));
  NAND2xp5_ASAP7_75t_R g6821__1617(.A (n_82), .B
       (u_axi_ctrl_aw_addr_reg[0]), .Y (n_114));
  A2O1A1Ixp33_ASAP7_75t_R g6822__2802(.A1 (n_7), .A2
       (u_axi_ctrl_n_1173), .B (n_52), .C (n_2), .Y (n_97));
  A2O1A1Ixp33_ASAP7_75t_R g6823__1705(.A1 (s_axi_arlen[3]), .A2 (n_6),
       .B (n_25), .C (n_2), .Y (n_96));
  A2O1A1Ixp33_ASAP7_75t_R g6824__5122(.A1 (s_axi_arlen[4]), .A2 (n_6),
       .B (n_28), .C (rst_n), .Y (n_95));
  A2O1A1Ixp33_ASAP7_75t_R g6825__8246(.A1 (s_axi_arlen[5]), .A2 (n_6),
       .B (n_30), .C (rst_n), .Y (n_94));
  A2O1A1Ixp33_ASAP7_75t_R g6826__7098(.A1 (s_axi_arlen[6]), .A2 (n_6),
       .B (n_44), .C (n_2), .Y (n_93));
  A2O1A1Ixp33_ASAP7_75t_R g6827__6131(.A1 (s_axi_arsize[2]), .A2 (n_6),
       .B (n_31), .C (n_2), .Y (n_92));
  A2O1A1Ixp33_ASAP7_75t_R g6828__1881(.A1 (s_axi_arlen[7]), .A2 (n_6),
       .B (n_32), .C (rst_n), .Y (n_91));
  A2O1A1Ixp33_ASAP7_75t_R g6829__5115(.A1 (s_axi_arid[0]), .A2 (n_6),
       .B (n_49), .C (rst_n), .Y (n_90));
  A2O1A1Ixp33_ASAP7_75t_R g6830__7482(.A1 (s_axi_arsize[0]), .A2 (n_6),
       .B (n_45), .C (n_2), .Y (n_89));
  NOR2xp33_ASAP7_75t_R g6831__4733(.A (n_8), .B (n_75), .Y (n_88));
  A2O1A1Ixp33_ASAP7_75t_R g6832__6161(.A1 (s_axi_arready), .A2 (n_285),
       .B (n_48), .C (n_2), .Y (n_87));
  A2O1A1Ixp33_ASAP7_75t_R g6833__9315(.A1 (s_axi_arlen[2]), .A2 (n_6),
       .B (n_46), .C (rst_n), .Y (n_86));
  A2O1A1Ixp33_ASAP7_75t_R g6834__9945(.A1 (s_axi_rvalid), .A2
       (u_axi_ctrl_n_1173), .B (n_52), .C (rst_n), .Y (n_85));
  NOR2xp33_ASAP7_75t_R g6835__2883(.A (n_67), .B (n_66), .Y (n_84));
  NAND3xp33_ASAP7_75t_R g6836__2346(.A (n_73), .B (n_54), .C
       (u_axi_ctrl_r_count[2]), .Y (n_99));
  AOI31xp33_ASAP7_75t_R g6837__1666(.A1 (s_axi_bready), .A2
       (s_axi_bvalid), .A3 (u_axi_ctrl_w_state[1]), .B (n_58), .Y
       (n_98));
  INVx1_ASAP7_75t_R g6838(.A (n_81), .Y (n_82));
  INVx1_ASAP7_75t_R g6839(.A (n_79), .Y (n_80));
  INVx1_ASAP7_75t_R g6840(.A (n_77), .Y (n_76));
  INVx1_ASAP7_75t_R g6841(.A (n_75), .Y (n_74));
  INVx1_ASAP7_75t_R g6842(.A (n_73), .Y (n_72));
  NOR2xp33_ASAP7_75t_R g6843__7410(.A (n_23), .B (n_55), .Y (n_71));
  XNOR2xp5_ASAP7_75t_R g6844__6417(.A (u_axi_ctrl_ar_addr_reg[0]), .B
       (n_286), .Y (n_70));
  AND2x2_ASAP7_75t_R g6846__5477(.A (n_53), .B (u_axi_ctrl_n_1173), .Y
       (n_83));
  NAND2xp5_ASAP7_75t_R g6847__2398(.A (n_8), .B (n_42), .Y (n_81));
  NOR2xp33_ASAP7_75t_R g6848__5107(.A (u_axi_ctrl_aw_size_reg[1]), .B
       (n_57), .Y (n_79));
  NOR2x1_ASAP7_75t_R g6849__6260(.A (u_axi_ctrl_r_state[1]), .B (n_38),
       .Y (n_78));
  NOR2x1_ASAP7_75t_R g6850__4319(.A (n_36), .B (n_362), .Y (n_77));
  AND2x2_ASAP7_75t_R g6851__8428(.A (n_55), .B (n_40), .Y (n_75));
  AND2x2_ASAP7_75t_R g6852__5526(.A (n_7), .B (n_37), .Y (n_73));
  XOR2xp5_ASAP7_75t_R g6853__6783(.A (u_axi_ctrl_ar_len_reg[5]), .B
       (u_axi_ctrl_r_count[5]), .Y (n_69));
  XOR2xp5_ASAP7_75t_R g6854__3680(.A (u_axi_ctrl_ar_len_reg[4]), .B
       (u_axi_ctrl_r_count[4]), .Y (n_68));
  XOR2xp5_ASAP7_75t_R g6855__1617(.A (u_axi_ctrl_ar_len_reg[0]), .B
       (u_axi_ctrl_r_count[0]), .Y (n_67));
  XOR2xp5_ASAP7_75t_R g6856__2802(.A (u_axi_ctrl_ar_len_reg[7]), .B
       (u_axi_ctrl_r_count[7]), .Y (n_66));
  XOR2xp5_ASAP7_75t_R g6857__1705(.A (u_axi_ctrl_r_count[0]), .B
       (u_axi_ctrl_r_count[1]), .Y (n_65));
  XNOR2xp5_ASAP7_75t_R g6858__5122(.A (u_axi_ctrl_ar_len_reg[3]), .B
       (u_axi_ctrl_r_count[3]), .Y (n_64));
  XNOR2xp5_ASAP7_75t_R g6859__8246(.A (u_axi_ctrl_ar_len_reg[1]), .B
       (u_axi_ctrl_r_count[1]), .Y (n_63));
  XNOR2xp5_ASAP7_75t_R g6860__7098(.A (u_axi_ctrl_ar_len_reg[6]), .B
       (u_axi_ctrl_r_count[6]), .Y (n_62));
  XNOR2xp5_ASAP7_75t_R g6861__6131(.A (u_axi_ctrl_ar_len_reg[2]), .B
       (u_axi_ctrl_r_count[2]), .Y (n_61));
  XOR2xp5_ASAP7_75t_R g6862__1881(.A (u_axi_ctrl_ar_addr_reg[1]), .B
       (n_272), .Y (n_60));
  INVx1_ASAP7_75t_R g6863(.A (n_58), .Y (n_59));
  INVx1_ASAP7_75t_R g6864(.A (n_53), .Y (n_52));
  INVx1_ASAP7_75t_R g6865(.A (n_51), .Y (n_50));
  AND2x2_ASAP7_75t_R g6866__5115(.A (s_axi_rid[0]), .B (n_284), .Y
       (n_49));
  NOR2xp33_ASAP7_75t_R g6867__7482(.A (n_285), .B (n_269), .Y (n_48));
  AND2x2_ASAP7_75t_R g6868__4733(.A (s_axi_rid[4]), .B (n_284), .Y
       (n_47));
  AND2x2_ASAP7_75t_R g6869__6161(.A (u_axi_ctrl_ar_len_reg[2]), .B
       (n_284), .Y (n_46));
  AND2x2_ASAP7_75t_R g6870__9315(.A (u_axi_ctrl_ar_size_reg[0]), .B
       (n_284), .Y (n_45));
  AND2x2_ASAP7_75t_R g6871__9945(.A (u_axi_ctrl_ar_len_reg[6]), .B
       (n_284), .Y (n_44));
  AND2x2_ASAP7_75t_R g6872__2883(.A (u_axi_ctrl_ar_len_reg[1]), .B
       (n_284), .Y (n_43));
  NOR2xp33_ASAP7_75t_R g6873__2346(.A (n_230), .B (n_362), .Y (n_58));
  NAND2xp5_ASAP7_75t_R g6874__1666(.A (u_axi_ctrl_aw_size_reg[0]), .B
       (n_19), .Y (n_57));
  NOR2xp33_ASAP7_75t_R g6875__7410(.A (u_axi_ctrl_aw_size_reg[0]), .B
       (n_19), .Y (n_56));
  NOR2xp33_ASAP7_75t_R g6876__6417(.A (u_axi_ctrl_w_state[0]), .B
       (u_axi_ctrl_w_state[1]), .Y (n_55));
  AND2x2_ASAP7_75t_R g6877__5477(.A (u_axi_ctrl_r_count[0]), .B
       (u_axi_ctrl_r_count[1]), .Y (n_54));
  NAND2xp5_ASAP7_75t_R g6878__2398(.A (u_axi_ctrl_r_state[0]), .B
       (n_24), .Y (n_53));
  NOR2x1_ASAP7_75t_R g6879__5107(.A (n_4), .B (bram_re_wire), .Y
       (n_51));
  INVx1_ASAP7_75t_R g6880(.A (n_39), .Y (n_40));
  INVx1_ASAP7_75t_R g6881(.A (n_38), .Y (n_37));
  INVx1_ASAP7_75t_R g6882(.A (n_36), .Y (n_35));
  AND2x2_ASAP7_75t_R g6883__6260(.A (s_axi_rid[3]), .B (n_284), .Y
       (n_34));
  AND2x2_ASAP7_75t_R g6884__4319(.A (s_axi_rid[1]), .B (n_284), .Y
       (n_33));
  AND2x2_ASAP7_75t_R g6885__8428(.A (u_axi_ctrl_ar_len_reg[7]), .B
       (n_284), .Y (n_32));
  AND2x2_ASAP7_75t_R g6886__5526(.A (u_axi_ctrl_ar_size_reg[2]), .B
       (n_284), .Y (n_31));
  AND2x2_ASAP7_75t_R g6887__6783(.A (u_axi_ctrl_ar_len_reg[5]), .B
       (n_284), .Y (n_30));
  AND2x2_ASAP7_75t_R g6888__3680(.A (s_axi_rid[2]), .B (n_284), .Y
       (n_29));
  AND2x2_ASAP7_75t_R g6889__1617(.A (u_axi_ctrl_ar_len_reg[4]), .B
       (n_284), .Y (n_28));
  AND2x2_ASAP7_75t_R g6890__2802(.A (u_axi_ctrl_ar_size_reg[1]), .B
       (n_284), .Y (n_27));
  AND2x2_ASAP7_75t_R g6891__1705(.A (u_axi_ctrl_ar_len_reg[0]), .B
       (n_284), .Y (n_26));
  AND2x2_ASAP7_75t_R g6892__5122(.A (u_axi_ctrl_ar_len_reg[3]), .B
       (n_284), .Y (n_25));
  NOR2xp33_ASAP7_75t_R g6893__8246(.A (u_axi_ctrl_aw_size_reg[2]), .B
       (u_axi_ctrl_aw_size_reg[0]), .Y (n_42));
  NAND2xp5_ASAP7_75t_R g6894__7098(.A (u_axi_ctrl_aw_size_reg[2]), .B
       (u_axi_ctrl_aw_size_reg[0]), .Y (n_41));
  NAND2xp5_ASAP7_75t_R g6895__6131(.A (s_axi_awready), .B
       (s_axi_awvalid), .Y (n_39));
  NAND2xp5_ASAP7_75t_R g6896__1881(.A (rst_n), .B (bram_re_wire), .Y
       (n_38));
  NAND2xp5_ASAP7_75t_R g6897__5115(.A (u_axi_ctrl_w_state[0]), .B
       (n_2), .Y (n_36));
  INVx1_ASAP7_75t_R g6899(.A (u_axi_ctrl_r_state[1]), .Y (n_24));
  INVx1_ASAP7_75t_R g6901(.A (s_axi_awready), .Y (n_23));
  INVx1_ASAP7_75t_R g6902(.A (bram_waddr_wire[9]), .Y (n_22));
  INVx1_ASAP7_75t_R g6903(.A (bram_waddr_wire[2]), .Y (n_21));
  INVx1_ASAP7_75t_R g6904(.A (bram_waddr_wire[4]), .Y (n_20));
  INVx1_ASAP7_75t_R g6905(.A (u_axi_ctrl_aw_size_reg[2]), .Y (n_19));
  INVx1_ASAP7_75t_R g6906(.A (bram_waddr_wire[7]), .Y (n_18));
  INVx1_ASAP7_75t_R g6908(.A (u_axi_ctrl_w_state[0]), .Y (n_5));
  INVx1_ASAP7_75t_R g6912(.A (bram_waddr_wire[0]), .Y (n_17));
  INVx1_ASAP7_75t_R g6913(.A (bram_waddr_wire[8]), .Y (n_16));
  INVx1_ASAP7_75t_R g6914(.A (u_axi_ctrl_aw_size_reg[0]), .Y (n_15));
  INVx1_ASAP7_75t_R g6915(.A (bram_waddr_wire[6]), .Y (n_14));
  INVx1_ASAP7_75t_R g6917(.A (u_axi_ctrl_w_state[1]), .Y (n_13));
  INVx1_ASAP7_75t_R g6921(.A (u_axi_ctrl_r_count[6]), .Y (n_12));
  INVx1_ASAP7_75t_R g6922(.A (u_axi_ctrl_r_count[2]), .Y (n_11));
  INVx1_ASAP7_75t_R g6923(.A (u_axi_ctrl_r_count[4]), .Y (n_10));
  INVx1_ASAP7_75t_R g6924(.A (u_axi_ctrl_r_count[3]), .Y (n_9));
  INVx1_ASAP7_75t_R g6925(.A (u_axi_ctrl_aw_size_reg[1]), .Y (n_8));
  INVx1_ASAP7_75t_R g6927(.A (n_284), .Y (n_6));
  INVx2_ASAP7_75t_R drc_bufs6935(.A (n_4), .Y (n_2));
  INVx1_ASAP7_75t_R drc_bufs6936(.A (rst_n), .Y (n_4));
  XNOR2xp5_ASAP7_75t_R g2__7482(.A (bram_waddr_wire[2]), .B (n_173), .Y
       (n_1));
  XOR2xp5_ASAP7_75t_R g6937__4733(.A (bram_waddr_wire[1]), .B (n_168),
       .Y (n_0));
  NOR4xp25_ASAP7_75t_R g2(.A (n_138), .B (n_68), .C (n_69), .D (n_53),
       .Y (n_432));
  FAx1_ASAP7_75t_R g7002(.A (n_114), .B (n_79), .CI
       (u_axi_ctrl_aw_addr_reg[1]), .CON (UNCONNECTED), .SN (n_529));
endmodule

