
//input ports
add mapped point iClk iClk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point a[31] a[31] -type PI PI
add mapped point a[30] a[30] -type PI PI
add mapped point a[29] a[29] -type PI PI
add mapped point a[28] a[28] -type PI PI
add mapped point a[27] a[27] -type PI PI
add mapped point a[26] a[26] -type PI PI
add mapped point a[25] a[25] -type PI PI
add mapped point a[24] a[24] -type PI PI
add mapped point a[23] a[23] -type PI PI
add mapped point a[22] a[22] -type PI PI
add mapped point a[21] a[21] -type PI PI
add mapped point a[20] a[20] -type PI PI
add mapped point a[19] a[19] -type PI PI
add mapped point a[18] a[18] -type PI PI
add mapped point a[17] a[17] -type PI PI
add mapped point a[16] a[16] -type PI PI
add mapped point a[15] a[15] -type PI PI
add mapped point a[14] a[14] -type PI PI
add mapped point a[13] a[13] -type PI PI
add mapped point a[12] a[12] -type PI PI
add mapped point a[11] a[11] -type PI PI
add mapped point a[10] a[10] -type PI PI
add mapped point a[9] a[9] -type PI PI
add mapped point a[8] a[8] -type PI PI
add mapped point a[7] a[7] -type PI PI
add mapped point a[6] a[6] -type PI PI
add mapped point a[5] a[5] -type PI PI
add mapped point a[4] a[4] -type PI PI
add mapped point a[3] a[3] -type PI PI
add mapped point a[2] a[2] -type PI PI
add mapped point a[1] a[1] -type PI PI
add mapped point a[0] a[0] -type PI PI
add mapped point b[31] b[31] -type PI PI
add mapped point b[30] b[30] -type PI PI
add mapped point b[29] b[29] -type PI PI
add mapped point b[28] b[28] -type PI PI
add mapped point b[27] b[27] -type PI PI
add mapped point b[26] b[26] -type PI PI
add mapped point b[25] b[25] -type PI PI
add mapped point b[24] b[24] -type PI PI
add mapped point b[23] b[23] -type PI PI
add mapped point b[22] b[22] -type PI PI
add mapped point b[21] b[21] -type PI PI
add mapped point b[20] b[20] -type PI PI
add mapped point b[19] b[19] -type PI PI
add mapped point b[18] b[18] -type PI PI
add mapped point b[17] b[17] -type PI PI
add mapped point b[16] b[16] -type PI PI
add mapped point b[15] b[15] -type PI PI
add mapped point b[14] b[14] -type PI PI
add mapped point b[13] b[13] -type PI PI
add mapped point b[12] b[12] -type PI PI
add mapped point b[11] b[11] -type PI PI
add mapped point b[10] b[10] -type PI PI
add mapped point b[9] b[9] -type PI PI
add mapped point b[8] b[8] -type PI PI
add mapped point b[7] b[7] -type PI PI
add mapped point b[6] b[6] -type PI PI
add mapped point b[5] b[5] -type PI PI
add mapped point b[4] b[4] -type PI PI
add mapped point b[3] b[3] -type PI PI
add mapped point b[2] b[2] -type PI PI
add mapped point b[1] b[1] -type PI PI
add mapped point b[0] b[0] -type PI PI

//output ports
add mapped point p[63] p[63] -type PO PO
add mapped point p[62] p[62] -type PO PO
add mapped point p[61] p[61] -type PO PO
add mapped point p[60] p[60] -type PO PO
add mapped point p[59] p[59] -type PO PO
add mapped point p[58] p[58] -type PO PO
add mapped point p[57] p[57] -type PO PO
add mapped point p[56] p[56] -type PO PO
add mapped point p[55] p[55] -type PO PO
add mapped point p[54] p[54] -type PO PO
add mapped point p[53] p[53] -type PO PO
add mapped point p[52] p[52] -type PO PO
add mapped point p[51] p[51] -type PO PO
add mapped point p[50] p[50] -type PO PO
add mapped point p[49] p[49] -type PO PO
add mapped point p[48] p[48] -type PO PO
add mapped point p[47] p[47] -type PO PO
add mapped point p[46] p[46] -type PO PO
add mapped point p[45] p[45] -type PO PO
add mapped point p[44] p[44] -type PO PO
add mapped point p[43] p[43] -type PO PO
add mapped point p[42] p[42] -type PO PO
add mapped point p[41] p[41] -type PO PO
add mapped point p[40] p[40] -type PO PO
add mapped point p[39] p[39] -type PO PO
add mapped point p[38] p[38] -type PO PO
add mapped point p[37] p[37] -type PO PO
add mapped point p[36] p[36] -type PO PO
add mapped point p[35] p[35] -type PO PO
add mapped point p[34] p[34] -type PO PO
add mapped point p[33] p[33] -type PO PO
add mapped point p[32] p[32] -type PO PO
add mapped point p[31] p[31] -type PO PO
add mapped point p[30] p[30] -type PO PO
add mapped point p[29] p[29] -type PO PO
add mapped point p[28] p[28] -type PO PO
add mapped point p[27] p[27] -type PO PO
add mapped point p[26] p[26] -type PO PO
add mapped point p[25] p[25] -type PO PO
add mapped point p[24] p[24] -type PO PO
add mapped point p[23] p[23] -type PO PO
add mapped point p[22] p[22] -type PO PO
add mapped point p[21] p[21] -type PO PO
add mapped point p[20] p[20] -type PO PO
add mapped point p[19] p[19] -type PO PO
add mapped point p[18] p[18] -type PO PO
add mapped point p[17] p[17] -type PO PO
add mapped point p[16] p[16] -type PO PO
add mapped point p[15] p[15] -type PO PO
add mapped point p[14] p[14] -type PO PO
add mapped point p[13] p[13] -type PO PO
add mapped point p[12] p[12] -type PO PO
add mapped point p[11] p[11] -type PO PO
add mapped point p[10] p[10] -type PO PO
add mapped point p[9] p[9] -type PO PO
add mapped point p[8] p[8] -type PO PO
add mapped point p[7] p[7] -type PO PO
add mapped point p[6] p[6] -type PO PO
add mapped point p[5] p[5] -type PO PO
add mapped point p[4] p[4] -type PO PO
add mapped point p[3] p[3] -type PO PO
add mapped point p[2] p[2] -type PO PO
add mapped point p[1] p[1] -type PO PO
add mapped point p[0] p[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point p[63]/q p_reg[63]/QN -type DFF DFF
add mapped point p[62]/q p_reg[62]/QN -type DFF DFF
add mapped point p[60]/q p_reg[60]/QN -type DFF DFF
add mapped point p[56]/q p_reg[56]/QN -type DFF DFF
add mapped point p[48]/q p_reg[48]/QN -type DFF DFF
add mapped point p[32]/q p_reg[32]/QN -type DFF DFF
add mapped point p[0]/q p_reg[0]/QN -type DFF DFF
add mapped point p[31]/q p_reg[31]/QN -type DFF DFF
add mapped point p[47]/q p_reg[47]/QN -type DFF DFF
add mapped point p[30]/q p_reg[30]/QN -type DFF DFF
add mapped point p[29]/q p_reg[29]/QN -type DFF DFF
add mapped point p[55]/q p_reg[55]/QN -type DFF DFF
add mapped point p[46]/q p_reg[46]/QN -type DFF DFF
add mapped point p[28]/q p_reg[28]/QN -type DFF DFF
add mapped point p[27]/q p_reg[27]/QN -type DFF DFF
add mapped point p[45]/q p_reg[45]/QN -type DFF DFF
add mapped point p[26]/q p_reg[26]/QN -type DFF DFF
add mapped point p[25]/q p_reg[25]/QN -type DFF DFF
add mapped point p[59]/q p_reg[59]/QN -type DFF DFF
add mapped point p[54]/q p_reg[54]/QN -type DFF DFF
add mapped point p[44]/q p_reg[44]/QN -type DFF DFF
add mapped point p[24]/q p_reg[24]/QN -type DFF DFF
add mapped point p[23]/q p_reg[23]/QN -type DFF DFF
add mapped point p[43]/q p_reg[43]/QN -type DFF DFF
add mapped point p[22]/q p_reg[22]/QN -type DFF DFF
add mapped point p[21]/q p_reg[21]/QN -type DFF DFF
add mapped point p[53]/q p_reg[53]/QN -type DFF DFF
add mapped point p[42]/q p_reg[42]/QN -type DFF DFF
add mapped point p[20]/q p_reg[20]/QN -type DFF DFF
add mapped point p[19]/q p_reg[19]/QN -type DFF DFF
add mapped point p[41]/q p_reg[41]/QN -type DFF DFF
add mapped point p[18]/q p_reg[18]/QN -type DFF DFF
add mapped point p[11]/q p_reg[11]/QN -type DFF DFF
add mapped point p[61]/q p_reg[61]/QN -type DFF DFF
add mapped point p[58]/q p_reg[58]/QN -type DFF DFF
add mapped point p[52]/q p_reg[52]/QN -type DFF DFF
add mapped point p[33]/q p_reg[33]/QN -type DFF DFF
add mapped point p[40]/q p_reg[40]/QN -type DFF DFF
add mapped point p[16]/q p_reg[16]/QN -type DFF DFF
add mapped point p[15]/q p_reg[15]/QN -type DFF DFF
add mapped point p[49]/q p_reg[49]/QN -type DFF DFF
add mapped point p[39]/q p_reg[39]/QN -type DFF DFF
add mapped point p[14]/q p_reg[14]/QN -type DFF DFF
add mapped point p[13]/q p_reg[13]/QN -type DFF DFF
add mapped point p[7]/q p_reg[7]/QN -type DFF DFF
add mapped point p[51]/q p_reg[51]/QN -type DFF DFF
add mapped point p[38]/q p_reg[38]/QN -type DFF DFF
add mapped point p[12]/q p_reg[12]/QN -type DFF DFF
add mapped point p[9]/q p_reg[9]/QN -type DFF DFF
add mapped point p[37]/q p_reg[37]/QN -type DFF DFF
add mapped point p[10]/q p_reg[10]/QN -type DFF DFF
add mapped point p[17]/q p_reg[17]/QN -type DFF DFF
add mapped point p[57]/q p_reg[57]/QN -type DFF DFF
add mapped point p[50]/q p_reg[50]/QN -type DFF DFF
add mapped point p[36]/q p_reg[36]/QN -type DFF DFF
add mapped point p[8]/q p_reg[8]/QN -type DFF DFF
add mapped point p[35]/q p_reg[35]/QN -type DFF DFF
add mapped point p[6]/q p_reg[6]/QN -type DFF DFF
add mapped point p[5]/q p_reg[5]/QN -type DFF DFF
add mapped point p[34]/q p_reg[34]/QN -type DFF DFF
add mapped point p[4]/q p_reg[4]/QN -type DFF DFF
add mapped point p[3]/q p_reg[3]/QN -type DFF DFF
add mapped point p[2]/q p_reg[2]/QN -type DFF DFF
add mapped point p[1]/q p_reg[1]/QN -type DFF DFF
add mapped point mult_reg[36]/q mult_reg_reg[36]/QN -type DFF DFF
add mapped point mult_reg[37]/q mult_reg_reg[37]/QN -type DFF DFF
add mapped point mult_reg[38]/q mult_reg_reg[38]/QN -type DFF DFF
add mapped point mult_reg[40]/q mult_reg_reg[40]/QN -type DFF DFF
add mapped point mult_reg[41]/q mult_reg_reg[41]/QN -type DFF DFF
add mapped point mult_reg[42]/q mult_reg_reg[42]/QN -type DFF DFF
add mapped point mult_reg[44]/q mult_reg_reg[44]/QN -type DFF DFF
add mapped point mult_reg[45]/q mult_reg_reg[45]/QN -type DFF DFF
add mapped point mult_reg[46]/q mult_reg_reg[46]/QN -type DFF DFF
add mapped point mult_reg[47]/q mult_reg_reg[47]/QN -type DFF DFF
add mapped point mult_reg[48]/q mult_reg_reg[48]/QN -type DFF DFF
add mapped point mult_reg[49]/q mult_reg_reg[49]/QN -type DFF DFF
add mapped point mult_reg[50]/q mult_reg_reg[50]/QN -type DFF DFF
add mapped point mult_reg[51]/q mult_reg_reg[51]/QN -type DFF DFF
add mapped point mult_reg[52]/q mult_reg_reg[52]/QN -type DFF DFF
add mapped point mult_reg[53]/q mult_reg_reg[53]/QN -type DFF DFF
add mapped point mult_reg[54]/q mult_reg_reg[54]/QN -type DFF DFF
add mapped point mult_reg[56]/q mult_reg_reg[56]/QN -type DFF DFF
add mapped point mult_reg[57]/q mult_reg_reg[57]/QN -type DFF DFF
add mapped point mult_reg[58]/q mult_reg_reg[58]/QN -type DFF DFF
add mapped point mult_reg[60]/q mult_reg_reg[60]/QN -type DFF DFF
add mapped point mult_reg[61]/q mult_reg_reg[61]/QN -type DFF DFF
add mapped point mult_reg[62]/q mult_reg_reg[62]/QN -type DFF DFF
add mapped point mult_reg[15]/q mult_reg_reg[15]/QN -type DFF DFF
add mapped point mult_reg[43]/q mult_reg_reg[43]/QN -type DFF DFF
add mapped point mult_reg[39]/q mult_reg_reg[39]/QN -type DFF DFF
add mapped point mult_reg[35]/q mult_reg_reg[35]/QN -type DFF DFF
add mapped point mult_reg[27]/q mult_reg_reg[27]/QN -type DFF DFF
add mapped point mult_reg[11]/q mult_reg_reg[11]/QN -type DFF DFF
add mapped point mult_reg[23]/q mult_reg_reg[23]/QN -type DFF DFF
add mapped point mult_reg[19]/q mult_reg_reg[19]/QN -type DFF DFF
add mapped point mult_reg[7]/q mult_reg_reg[7]/QN -type DFF DFF
add mapped point mult_reg[63]/q mult_reg_reg[63]/QN -type DFF DFF
add mapped point mult_reg[0]/q mult_reg_reg[0]/QN -type DFF DFF
add mapped point mult_reg[1]/q mult_reg_reg[1]/QN -type DFF DFF
add mapped point mult_reg[2]/q mult_reg_reg[2]/QN -type DFF DFF
add mapped point mult_reg[3]/q mult_reg_reg[3]/QN -type DFF DFF
add mapped point mult_reg[4]/q mult_reg_reg[4]/QN -type DFF DFF
add mapped point mult_reg[5]/q mult_reg_reg[5]/QN -type DFF DFF
add mapped point mult_reg[6]/q mult_reg_reg[6]/QN -type DFF DFF
add mapped point mult_reg[8]/q mult_reg_reg[8]/QN -type DFF DFF
add mapped point mult_reg[9]/q mult_reg_reg[9]/QN -type DFF DFF
add mapped point mult_reg[10]/q mult_reg_reg[10]/QN -type DFF DFF
add mapped point mult_reg[59]/q mult_reg_reg[59]/QN -type DFF DFF
add mapped point mult_reg[12]/q mult_reg_reg[12]/QN -type DFF DFF
add mapped point mult_reg[13]/q mult_reg_reg[13]/QN -type DFF DFF
add mapped point mult_reg[14]/q mult_reg_reg[14]/QN -type DFF DFF
add mapped point mult_reg[16]/q mult_reg_reg[16]/QN -type DFF DFF
add mapped point mult_reg[17]/q mult_reg_reg[17]/QN -type DFF DFF
add mapped point mult_reg[18]/q mult_reg_reg[18]/QN -type DFF DFF
add mapped point mult_reg[20]/q mult_reg_reg[20]/QN -type DFF DFF
add mapped point mult_reg[21]/q mult_reg_reg[21]/QN -type DFF DFF
add mapped point mult_reg[22]/q mult_reg_reg[22]/QN -type DFF DFF
add mapped point mult_reg[24]/q mult_reg_reg[24]/QN -type DFF DFF
add mapped point mult_reg[25]/q mult_reg_reg[25]/QN -type DFF DFF
add mapped point mult_reg[26]/q mult_reg_reg[26]/QN -type DFF DFF
add mapped point mult_reg[55]/q mult_reg_reg[55]/QN -type DFF DFF
add mapped point mult_reg[28]/q mult_reg_reg[28]/QN -type DFF DFF
add mapped point mult_reg[29]/q mult_reg_reg[29]/QN -type DFF DFF
add mapped point mult_reg[30]/q mult_reg_reg[30]/QN -type DFF DFF
add mapped point mult_reg[31]/q mult_reg_reg[31]/QN -type DFF DFF
add mapped point mult_reg[32]/q mult_reg_reg[32]/QN -type DFF DFF
add mapped point mult_reg[33]/q mult_reg_reg[33]/QN -type DFF DFF
add mapped point mult_reg[34]/q mult_reg_reg[34]/QN -type DFF DFF
add mapped point b_reg[17]/q b_reg_reg[17]/QN -type DFF DFF
add mapped point b_reg[3]/q b_reg_reg[3]/QN -type DFF DFF
add mapped point b_reg[7]/q b_reg_reg[7]/QN -type DFF DFF
add mapped point b_reg[30]/q b_reg_reg[30]/QN -type DFF DFF
add mapped point a_reg[20]/q a_reg_reg[20]/QN -type DFF DFF
add mapped point b_reg[13]/q b_reg_reg[13]/QN -type DFF DFF
add mapped point b_reg[24]/q b_reg_reg[24]/QN -type DFF DFF
add mapped point b_reg[22]/q b_reg_reg[22]/QN -type DFF DFF
add mapped point b_reg[6]/q b_reg_reg[6]/QN -type DFF DFF
add mapped point b_reg[11]/q b_reg_reg[11]/QN -type DFF DFF
add mapped point b_reg[0]/q b_reg_reg[0]/QN -type DFF DFF
add mapped point b_reg[4]/q b_reg_reg[4]/QN -type DFF DFF
add mapped point a_reg[25]/q a_reg_reg[25]/QN -type DFF DFF
add mapped point a_reg[28]/q a_reg_reg[28]/QN -type DFF DFF
add mapped point a_reg[27]/q a_reg_reg[27]/QN -type DFF DFF
add mapped point b_reg[29]/q b_reg_reg[29]/QN -type DFF DFF
add mapped point b_reg[18]/q b_reg_reg[18]/QN -type DFF DFF
add mapped point a_reg[29]/q a_reg_reg[29]/QN -type DFF DFF
add mapped point b_reg[31]/q b_reg_reg[31]/QN -type DFF DFF
add mapped point b_reg[23]/q b_reg_reg[23]/QN -type DFF DFF
add mapped point b_reg[19]/q b_reg_reg[19]/QN -type DFF DFF
add mapped point a_reg[31]/q a_reg_reg[31]/QN -type DFF DFF
add mapped point b_reg[2]/q b_reg_reg[2]/QN -type DFF DFF
add mapped point b_reg[5]/q b_reg_reg[5]/QN -type DFF DFF
add mapped point b_reg[8]/q b_reg_reg[8]/QN -type DFF DFF
add mapped point b_reg[10]/q b_reg_reg[10]/QN -type DFF DFF
add mapped point b_reg[12]/q b_reg_reg[12]/QN -type DFF DFF
add mapped point b_reg[21]/q b_reg_reg[21]/QN -type DFF DFF
add mapped point b_reg[14]/q b_reg_reg[14]/QN -type DFF DFF
add mapped point b_reg[20]/q b_reg_reg[20]/QN -type DFF DFF
add mapped point b_reg[28]/q b_reg_reg[28]/QN -type DFF DFF
add mapped point a_reg[13]/q a_reg_reg[13]/QN -type DFF DFF
add mapped point a_reg[15]/q a_reg_reg[15]/QN -type DFF DFF
add mapped point a_reg[9]/q a_reg_reg[9]/QN -type DFF DFF
add mapped point a_reg[0]/q a_reg_reg[0]/QN -type DFF DFF
add mapped point a_reg[26]/q a_reg_reg[26]/QN -type DFF DFF
add mapped point b_reg[27]/q b_reg_reg[27]/QN -type DFF DFF
add mapped point a_reg[24]/q a_reg_reg[24]/QN -type DFF DFF
add mapped point a_reg[5]/q a_reg_reg[5]/QN -type DFF DFF
add mapped point b_reg[15]/q b_reg_reg[15]/QN -type DFF DFF
add mapped point a_reg[14]/q a_reg_reg[14]/QN -type DFF DFF
add mapped point a_reg[18]/q a_reg_reg[18]/QN -type DFF DFF
add mapped point a_reg[23]/q a_reg_reg[23]/QN -type DFF DFF
add mapped point a_reg[30]/q a_reg_reg[30]/QN -type DFF DFF
add mapped point a_reg[21]/q a_reg_reg[21]/QN -type DFF DFF
add mapped point a_reg[19]/q a_reg_reg[19]/QN -type DFF DFF
add mapped point a_reg[6]/q a_reg_reg[6]/QN -type DFF DFF
add mapped point a_reg[12]/q a_reg_reg[12]/QN -type DFF DFF
add mapped point b_reg[1]/q b_reg_reg[1]/QN -type DFF DFF
add mapped point b_reg[26]/q b_reg_reg[26]/QN -type DFF DFF
add mapped point b_reg[25]/q b_reg_reg[25]/QN -type DFF DFF
add mapped point a_reg[17]/q a_reg_reg[17]/QN -type DFF DFF
add mapped point b_reg[16]/q b_reg_reg[16]/QN -type DFF DFF
add mapped point a_reg[16]/q a_reg_reg[16]/QN -type DFF DFF
add mapped point a_reg[11]/q a_reg_reg[11]/QN -type DFF DFF
add mapped point a_reg[22]/q a_reg_reg[22]/QN -type DFF DFF
add mapped point a_reg[10]/q a_reg_reg[10]/QN -type DFF DFF
add mapped point b_reg[9]/q b_reg_reg[9]/QN -type DFF DFF
add mapped point a_reg[7]/q a_reg_reg[7]/QN -type DFF DFF
add mapped point a_reg[8]/q a_reg_reg[8]/QN -type DFF DFF
add mapped point a_reg[3]/q a_reg_reg[3]/QN -type DFF DFF
add mapped point a_reg[4]/q a_reg_reg[4]/QN -type DFF DFF
add mapped point a_reg[2]/q a_reg_reg[2]/QN -type DFF DFF
add mapped point a_reg[1]/q a_reg_reg[1]/QN -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
