/*
###############################################################
#  Generated by:      Cadence Innovus 22.17-s086_1
#  OS:                Linux x86_64(Host ID vlsiktmt)
#  Generated on:      Sun Apr 12 21:09:17 2026
#  Design:            Adder32
#  Command:           saveNetlist -excludeLeafCell ./outputs/innovus.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Apr 12 2026 20:33:44 +07 (Apr 12 2026 13:33:44 UTC)
// Verification Directory fv/Adder32 
module Adder32 (
	iClk, 
	iA, 
	iB, 
	oS);
   input iClk;
   input [31:0] iA;
   input [31:0] iB;
   output [31:0] oS;

   // Internal wires
   wire FE_PHN16_n_260;
   wire FE_PHN15_iB_21;
   wire FE_PHN14_n_225;
   wire FE_PHN13_iA_21;
   wire FE_PHN12_iA_26;
   wire FE_PHN11_n_224;
   wire FE_PHN10_iB_26;
   wire FE_PHN9_n_220;
   wire FE_PHN8_n_229;
   wire FE_PHN7_n_239;
   wire FE_PHN6_n_248;
   wire FE_PHN5_FE_RN_0_0;
   wire FE_PHN4_iB_30;
   wire FE_PHN3_n_260;
   wire FE_PHN2_iA_30;
   wire FE_PHN1_n_234;
   wire FE_PHN0_n_221;
   wire FE_RN_0_0;
   wire add_8_11_n_693;
   wire add_8_11_n_696;
   wire add_8_11_n_699;
   wire add_8_11_n_703;
   wire add_8_11_n_707;
   wire add_8_11_n_711;
   wire add_8_11_n_712;
   wire add_8_11_n_713;
   wire add_8_11_n_714;
   wire add_8_11_n_720;
   wire add_8_11_n_722;
   wire add_8_11_n_723;
   wire add_8_11_n_725;
   wire add_8_11_n_727;
   wire add_8_11_n_731;
   wire add_8_11_n_733;
   wire add_8_11_n_736;
   wire add_8_11_n_739;
   wire add_8_11_n_740;
   wire add_8_11_n_741;
   wire add_8_11_n_742;
   wire add_8_11_n_743;
   wire add_8_11_n_748;
   wire add_8_11_n_749;
   wire add_8_11_n_752;
   wire add_8_11_n_753;
   wire add_8_11_n_755;
   wire add_8_11_n_759;
   wire add_8_11_n_762;
   wire add_8_11_n_763;
   wire add_8_11_n_767;
   wire add_8_11_n_768;
   wire add_8_11_n_769;
   wire add_8_11_n_773;
   wire add_8_11_n_774;
   wire add_8_11_n_776;
   wire add_8_11_n_781;
   wire add_8_11_n_785;
   wire add_8_11_n_787;
   wire add_8_11_n_790;
   wire add_8_11_n_792;
   wire add_8_11_n_793;
   wire add_8_11_n_795;
   wire add_8_11_n_799;
   wire add_8_11_n_802;
   wire add_8_11_n_805;
   wire add_8_11_n_806;
   wire add_8_11_n_811;
   wire add_8_11_n_813;
   wire add_8_11_n_816;
   wire add_8_11_n_817;
   wire add_8_11_n_820;
   wire add_8_11_n_822;
   wire add_8_11_n_824;
   wire add_8_11_n_825;
   wire add_8_11_n_827;
   wire add_8_11_n_829;
   wire add_8_11_n_831;
   wire add_8_11_n_833;
   wire add_8_11_n_837;
   wire add_8_11_n_839;
   wire add_8_11_n_843;
   wire add_8_11_n_846;
   wire add_8_11_n_849;
   wire add_8_11_n_851;
   wire add_8_11_n_852;
   wire add_8_11_n_854;
   wire add_8_11_n_858;
   wire add_8_11_n_859;
   wire add_8_11_n_862;
   wire add_8_11_n_863;
   wire add_8_11_n_864;
   wire add_8_11_n_869;
   wire add_8_11_n_871;
   wire add_8_11_n_875;
   wire add_8_11_n_878;
   wire add_8_11_n_882;
   wire add_8_11_n_884;
   wire add_8_11_n_888;
   wire add_8_11_n_889;
   wire add_8_11_n_891;
   wire add_8_11_n_892;
   wire add_8_11_n_894;
   wire add_8_11_n_895;
   wire add_8_11_n_898;
   wire add_8_11_n_899;
   wire add_8_11_n_901;
   wire add_8_11_n_903;
   wire add_8_11_n_904;
   wire add_8_11_n_905;
   wire add_8_11_n_906;
   wire add_8_11_n_907;
   wire add_8_11_n_908;
   wire add_8_11_n_909;
   wire add_8_11_n_910;
   wire add_8_11_n_911;
   wire add_8_11_n_913;
   wire add_8_11_n_914;
   wire add_8_11_n_915;
   wire add_8_11_n_916;
   wire add_8_11_n_917;
   wire add_8_11_n_918;
   wire add_8_11_n_919;
   wire add_8_11_n_920;
   wire add_8_11_n_921;
   wire add_8_11_n_922;
   wire add_8_11_n_923;
   wire add_8_11_n_927;
   wire add_8_11_n_928;
   wire add_8_11_n_929;
   wire add_8_11_n_930;
   wire add_8_11_n_931;
   wire add_8_11_n_932;
   wire add_8_11_n_933;
   wire add_8_11_n_934;
   wire add_8_11_n_937;
   wire add_8_11_n_940;
   wire add_8_11_n_945;
   wire add_8_11_n_948;
   wire add_8_11_n_951;
   wire add_8_11_n_954;
   wire add_8_11_n_957;
   wire add_8_11_n_968;
   wire add_8_11_n_969;
   wire add_8_11_n_970;
   wire add_8_11_n_971;
   wire add_8_11_n_972;
   wire add_8_11_n_976;
   wire add_8_11_n_978;
   wire add_8_11_n_980;
   wire add_8_11_n_981;
   wire add_8_11_n_982;
   wire add_8_11_n_983;
   wire add_8_11_n_984;
   wire add_8_11_n_985;
   wire add_8_11_n_986;
   wire add_8_11_n_987;
   wire add_8_11_n_988;
   wire add_8_11_n_989;
   wire add_8_11_n_990;
   wire add_8_11_n_991;
   wire add_8_11_n_993;
   wire add_8_11_n_994;
   wire add_8_11_n_995;
   wire add_8_11_n_996;
   wire add_8_11_n_997;
   wire add_8_11_n_998;
   wire add_8_11_n_999;
   wire add_8_11_n_1000;
   wire add_8_11_n_1007;
   wire add_8_11_n_1010;
   wire add_8_11_n_1015;
   wire add_8_11_n_1018;
   wire add_8_11_n_1019;
   wire add_8_11_n_1022;
   wire n_116;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;

   HB1xp67_ASAP7_75t_R FE_PHC16_n_260 (.Y(FE_PHN3_n_260),
	.A(FE_PHN16_n_260));
   HB1xp67_ASAP7_75t_R FE_PHC15_iB_21 (.Y(FE_PHN15_iB_21),
	.A(iB[21]));
   HB1xp67_ASAP7_75t_R FE_PHC14_n_225 (.Y(n_225),
	.A(FE_PHN14_n_225));
   HB1xp67_ASAP7_75t_R FE_PHC13_iA_21 (.Y(FE_PHN13_iA_21),
	.A(iA[21]));
   HB1xp67_ASAP7_75t_R FE_PHC12_iA_26 (.Y(FE_PHN12_iA_26),
	.A(iA[26]));
   HB1xp67_ASAP7_75t_R FE_PHC11_n_224 (.Y(n_224),
	.A(FE_PHN11_n_224));
   HB1xp67_ASAP7_75t_R FE_PHC10_iB_26 (.Y(FE_PHN10_iB_26),
	.A(iB[26]));
   HB1xp67_ASAP7_75t_R FE_PHC9_n_220 (.Y(n_220),
	.A(FE_PHN9_n_220));
   HB1xp67_ASAP7_75t_R FE_PHC8_n_229 (.Y(n_229),
	.A(FE_PHN8_n_229));
   HB1xp67_ASAP7_75t_R FE_PHC7_n_239 (.Y(n_239),
	.A(FE_PHN7_n_239));
   HB1xp67_ASAP7_75t_R FE_PHC6_n_248 (.Y(n_248),
	.A(FE_PHN6_n_248));
   HB1xp67_ASAP7_75t_R FE_PHC5_FE_RN_0_0 (.Y(FE_PHN5_FE_RN_0_0),
	.A(FE_RN_0_0));
   HB1xp67_ASAP7_75t_R FE_PHC4_iB_30 (.Y(FE_PHN4_iB_30),
	.A(iB[30]));
   HB1xp67_ASAP7_75t_R FE_PHC3_n_260 (.Y(n_260),
	.A(FE_PHN3_n_260));
   HB1xp67_ASAP7_75t_R FE_PHC2_iA_30 (.Y(FE_PHN2_iA_30),
	.A(iA[30]));
   HB1xp67_ASAP7_75t_R FE_PHC1_n_234 (.Y(FE_PHN1_n_234),
	.A(n_234));
   HB2xp67_ASAP7_75t_R FE_PHC0_n_221 (.Y(FE_PHN0_n_221),
	.A(n_221));
   AOI21x1_ASAP7_75t_R FE_RC_2_0 (.Y(add_8_11_n_799),
	.A1(add_8_11_n_805),
	.A2(add_8_11_n_971),
	.B(add_8_11_n_970));
   XOR2xp5_ASAP7_75t_R FE_RC_1_0 (.Y(FE_RN_0_0),
	.A(iA[31]),
	.B(iB[31]));
   XNOR2xp5_ASAP7_75t_R FE_RC_0_0 (.Y(n_116),
	.A(FE_PHN5_FE_RN_0_0),
	.B(add_8_11_n_693));
   DFFHQNx1_ASAP7_75t_R \oS_reg[12]  (.QN(oS[12]),
	.CLK(iClk),
	.D(n_229));
   DFFHQNx1_ASAP7_75t_R \oS_reg[30]  (.QN(oS[30]),
	.CLK(iClk),
	.D(n_233));
   DFFHQNx1_ASAP7_75t_R \oS_reg[9]  (.QN(oS[9]),
	.CLK(iClk),
	.D(n_249));
   DFFHQNx1_ASAP7_75t_R \oS_reg[28]  (.QN(oS[28]),
	.CLK(iClk),
	.D(n_222));
   DFFHQNx1_ASAP7_75t_R \oS_reg[24]  (.QN(oS[24]),
	.CLK(iClk),
	.D(n_223));
   DFFHQNx1_ASAP7_75t_R \oS_reg[16]  (.QN(oS[16]),
	.CLK(iClk),
	.D(n_220));
   DFFHQNx1_ASAP7_75t_R \oS_reg[4]  (.QN(oS[4]),
	.CLK(iClk),
	.D(n_245));
   DFFHQNx1_ASAP7_75t_R \oS_reg[0]  (.QN(oS[0]),
	.CLK(iClk),
	.D(FE_PHN0_n_221));
   DFFHQNx1_ASAP7_75t_R \oS_reg[15]  (.QN(oS[15]),
	.CLK(iClk),
	.D(n_224));
   DFFHQNx1_ASAP7_75t_R \oS_reg[23]  (.QN(oS[23]),
	.CLK(iClk),
	.D(n_225));
   DFFHQNx1_ASAP7_75t_R \oS_reg[14]  (.QN(oS[14]),
	.CLK(iClk),
	.D(n_227));
   DFFHQNx1_ASAP7_75t_R \oS_reg[13]  (.QN(oS[13]),
	.CLK(iClk),
	.D(n_226));
   DFFHQNx1_ASAP7_75t_R \oS_reg[27]  (.QN(oS[27]),
	.CLK(iClk),
	.D(n_230));
   DFFHQNx1_ASAP7_75t_R \oS_reg[22]  (.QN(oS[22]),
	.CLK(iClk),
	.D(n_228));
   DFFHQNx1_ASAP7_75t_R \oS_reg[20]  (.QN(oS[20]),
	.CLK(iClk),
	.D(n_237));
   DFFHQNx1_ASAP7_75t_R \oS_reg[10]  (.QN(oS[10]),
	.CLK(iClk),
	.D(n_219));
   DFFHQNx1_ASAP7_75t_R \oS_reg[2]  (.QN(oS[2]),
	.CLK(iClk),
	.D(n_248));
   DFFHQNx1_ASAP7_75t_R \oS_reg[21]  (.QN(oS[21]),
	.CLK(iClk),
	.D(n_232));
   DFFHQNx1_ASAP7_75t_R \oS_reg[31]  (.QN(oS[31]),
	.CLK(iClk),
	.D(n_116));
   DFFHQNx1_ASAP7_75t_R \oS_reg[1]  (.QN(oS[1]),
	.CLK(iClk),
	.D(FE_PHN1_n_234));
   DFFHQNx1_ASAP7_75t_R \oS_reg[29]  (.QN(oS[29]),
	.CLK(iClk),
	.D(n_235));
   DFFHQNx1_ASAP7_75t_R \oS_reg[26]  (.QN(oS[26]),
	.CLK(iClk),
	.D(n_236));
   DFFHQNx1_ASAP7_75t_R \oS_reg[8]  (.QN(oS[8]),
	.CLK(iClk),
	.D(n_238));
   DFFHQNx1_ASAP7_75t_R \oS_reg[7]  (.QN(oS[7]),
	.CLK(iClk),
	.D(n_239));
   DFFHQNx1_ASAP7_75t_R \oS_reg[19]  (.QN(oS[19]),
	.CLK(iClk),
	.D(n_240));
   DFFHQNx1_ASAP7_75t_R \oS_reg[6]  (.QN(oS[6]),
	.CLK(iClk),
	.D(n_241));
   DFFHQNx1_ASAP7_75t_R \oS_reg[5]  (.QN(oS[5]),
	.CLK(iClk),
	.D(n_242));
   DFFHQNx1_ASAP7_75t_R \oS_reg[25]  (.QN(oS[25]),
	.CLK(iClk),
	.D(n_243));
   DFFHQNx1_ASAP7_75t_R \oS_reg[18]  (.QN(oS[18]),
	.CLK(iClk),
	.D(n_244));
   DFFHQNx1_ASAP7_75t_R \oS_reg[3]  (.QN(oS[3]),
	.CLK(iClk),
	.D(n_246));
   DFFHQNx1_ASAP7_75t_R \oS_reg[17]  (.QN(oS[17]),
	.CLK(iClk),
	.D(n_247));
   DFFHQNx1_ASAP7_75t_R \oS_reg[11]  (.QN(oS[11]),
	.CLK(iClk),
	.D(n_231));
   OAI21xp5_ASAP7_75t_R add_8_11_g1106__5107 (.Y(add_8_11_n_693),
	.A1(add_8_11_n_948),
	.A2(add_8_11_n_696),
	.B(n_259));
   AOI21xp5_ASAP7_75t_R add_8_11_g1108__4319 (.Y(add_8_11_n_696),
	.A1(add_8_11_n_699),
	.A2(add_8_11_n_976),
	.B(add_8_11_n_903));
   OAI21xp5_ASAP7_75t_R add_8_11_g1111__5526 (.Y(add_8_11_n_699),
	.A1(add_8_11_n_1007),
	.A2(add_8_11_n_703),
	.B(n_261));
   AOI21xp5_ASAP7_75t_R add_8_11_g1114__3680 (.Y(add_8_11_n_703),
	.A1(add_8_11_n_707),
	.A2(add_8_11_n_908),
	.B(add_8_11_n_978));
   OAI21x1_ASAP7_75t_R add_8_11_g1116__2802 (.Y(add_8_11_n_707),
	.A1(add_8_11_n_905),
	.A2(add_8_11_n_713),
	.B(add_8_11_n_957));
   OAI21xp33_ASAP7_75t_R add_8_11_g1120__7098 (.Y(add_8_11_n_711),
	.A1(add_8_11_n_917),
	.A2(add_8_11_n_722),
	.B(add_8_11_n_988));
   OAI21xp33_ASAP7_75t_R add_8_11_g1121__6131 (.Y(add_8_11_n_712),
	.A1(add_8_11_n_927),
	.A2(add_8_11_n_720),
	.B(add_8_11_n_916));
   INVx1_ASAP7_75t_R add_8_11_g1122 (.Y(add_8_11_n_713),
	.A(add_8_11_n_714));
   AO21x1_ASAP7_75t_R add_8_11_g1123__1881 (.Y(add_8_11_n_714),
	.A1(add_8_11_n_846),
	.A2(add_8_11_n_723),
	.B(add_8_11_n_822));
   NOR2xp33_ASAP7_75t_R add_8_11_g1127__4733 (.Y(add_8_11_n_720),
	.A(add_8_11_n_817),
	.B(add_8_11_n_725));
   INVxp33_ASAP7_75t_R add_8_11_g1129 (.Y(add_8_11_n_722),
	.A(add_8_11_n_723));
   OAI21xp5_ASAP7_75t_R add_8_11_g1130__6161 (.Y(add_8_11_n_723),
	.A1(add_8_11_n_837),
	.A2(add_8_11_n_731),
	.B(add_8_11_n_792));
   NOR2xp33_ASAP7_75t_R add_8_11_g1132__9945 (.Y(add_8_11_n_725),
	.A(add_8_11_n_933),
	.B(add_8_11_n_731));
   NAND2xp33_ASAP7_75t_R add_8_11_g1133__2883 (.Y(add_8_11_n_727),
	.A(add_8_11_n_911),
	.B(add_8_11_n_731));
   NAND2xp5_ASAP7_75t_R add_8_11_g1137__1666 (.Y(add_8_11_n_731),
	.A(add_8_11_n_968),
	.B(add_8_11_n_736));
   OAI21xp33_ASAP7_75t_R add_8_11_g1138__7410 (.Y(add_8_11_n_733),
	.A1(add_8_11_n_998),
	.A2(add_8_11_n_739),
	.B(add_8_11_n_918));
   OAI21xp5_ASAP7_75t_R add_8_11_g1140__5477 (.Y(add_8_11_n_736),
	.A1(add_8_11_n_849),
	.A2(add_8_11_n_742),
	.B(add_8_11_n_795));
   NOR2xp33_ASAP7_75t_R add_8_11_g1143__6260 (.Y(add_8_11_n_739),
	.A(add_8_11_n_825),
	.B(add_8_11_n_741));
   NAND2xp33_ASAP7_75t_R add_8_11_g1144__4319 (.Y(add_8_11_n_740),
	.A(n_251),
	.B(add_8_11_n_748));
   INVxp33_ASAP7_75t_R add_8_11_g1145 (.Y(add_8_11_n_741),
	.A(add_8_11_n_742));
   NAND2xp5_ASAP7_75t_R add_8_11_g1146__8428 (.Y(add_8_11_n_742),
	.A(add_8_11_n_984),
	.B(add_8_11_n_749));
   OAI21xp33_ASAP7_75t_R add_8_11_g1147__5526 (.Y(add_8_11_n_743),
	.A1(add_8_11_n_929),
	.A2(add_8_11_n_752),
	.B(add_8_11_n_990));
   INVxp33_ASAP7_75t_R add_8_11_g1151 (.Y(add_8_11_n_748),
	.A(add_8_11_n_749));
   NOR2xp67_ASAP7_75t_R add_8_11_g1152__2802 (.Y(add_8_11_n_749),
	.A(add_8_11_n_1015),
	.B(add_8_11_n_755));
   AOI21xp33_ASAP7_75t_R add_8_11_g1154__5122 (.Y(add_8_11_n_752),
	.A1(add_8_11_n_763),
	.A2(add_8_11_n_997),
	.B(add_8_11_n_831));
   OAI21xp33_ASAP7_75t_R add_8_11_g1155__8246 (.Y(add_8_11_n_753),
	.A1(add_8_11_n_994),
	.A2(add_8_11_n_767),
	.B(add_8_11_n_919));
   AOI21xp5_ASAP7_75t_R add_8_11_g1157__7098 (.Y(add_8_11_n_755),
	.A1(add_8_11_n_763),
	.A2(add_8_11_n_833),
	.B(add_8_11_n_793));
   NAND2xp33_ASAP7_75t_R add_8_11_g1159__1881 (.Y(add_8_11_n_759),
	.A(n_257),
	.B(add_8_11_n_762));
   INVxp33_ASAP7_75t_R add_8_11_g1164 (.Y(add_8_11_n_762),
	.A(add_8_11_n_763));
   NOR2xp67_ASAP7_75t_R add_8_11_g1165__4733 (.Y(add_8_11_n_763),
	.A(add_8_11_n_940),
	.B(add_8_11_n_769));
   AOI21xp33_ASAP7_75t_R add_8_11_g1166__6161 (.Y(add_8_11_n_767),
	.A1(add_8_11_n_773),
	.A2(add_8_11_n_932),
	.B(add_8_11_n_820));
   NAND2xp33_ASAP7_75t_R add_8_11_g1167__9315 (.Y(add_8_11_n_768),
	.A(add_8_11_n_913),
	.B(add_8_11_n_774));
   AOI21xp5_ASAP7_75t_R add_8_11_g1169__9945 (.Y(add_8_11_n_769),
	.A1(add_8_11_n_776),
	.A2(add_8_11_n_839),
	.B(add_8_11_n_790));
   INVxp33_ASAP7_75t_R add_8_11_g1171 (.Y(add_8_11_n_773),
	.A(add_8_11_n_774));
   NAND2xp33_ASAP7_75t_R add_8_11_g1172__2346 (.Y(add_8_11_n_774),
	.A(add_8_11_n_986),
	.B(add_8_11_n_776));
   OAI21x1_ASAP7_75t_R add_8_11_g1176__1666 (.Y(add_8_11_n_776),
	.A1(add_8_11_n_945),
	.A2(add_8_11_n_781),
	.B(n_263));
   AOI21x1_ASAP7_75t_R add_8_11_g1178__6417 (.Y(add_8_11_n_781),
	.A1(add_8_11_n_787),
	.A2(add_8_11_n_980),
	.B(add_8_11_n_907));
   OAI21xp33_ASAP7_75t_R add_8_11_g1181__5107 (.Y(add_8_11_n_785),
	.A1(add_8_11_n_914),
	.A2(add_8_11_n_799),
	.B(add_8_11_n_993));
   OAI21x1_ASAP7_75t_R add_8_11_g1183__6260 (.Y(add_8_11_n_787),
	.A1(add_8_11_n_843),
	.A2(add_8_11_n_799),
	.B(add_8_11_n_829));
   A2O1A1Ixp33_ASAP7_75t_R add_8_11_g1185__8428 (.Y(add_8_11_n_790),
	.A1(add_8_11_n_919),
	.A2(add_8_11_n_811),
	.B(add_8_11_n_921),
	.C(add_8_11_n_954));
   OA21x2_ASAP7_75t_R add_8_11_g1186__5526 (.Y(add_8_11_n_792),
	.A1(add_8_11_n_920),
	.A2(add_8_11_n_806),
	.B(add_8_11_n_1018));
   A2O1A1Ixp33_ASAP7_75t_R add_8_11_g1187__6783 (.Y(add_8_11_n_793),
	.A1(add_8_11_n_990),
	.A2(add_8_11_n_813),
	.B(add_8_11_n_922),
	.C(add_8_11_n_1019));
   OA21x2_ASAP7_75t_R add_8_11_g1188__3680 (.Y(add_8_11_n_795),
	.A1(add_8_11_n_982),
	.A2(add_8_11_n_802),
	.B(add_8_11_n_1022));
   OA21x2_ASAP7_75t_R add_8_11_g1194__1705 (.Y(add_8_11_n_802),
	.A1(add_8_11_n_998),
	.A2(add_8_11_n_824),
	.B(add_8_11_n_918));
   OAI21x1_ASAP7_75t_R add_8_11_g1195__5122 (.Y(add_8_11_n_805),
	.A1(add_8_11_n_827),
	.A2(add_8_11_n_934),
	.B(n_253));
   OA21x2_ASAP7_75t_R add_8_11_g1196__8246 (.Y(add_8_11_n_806),
	.A1(add_8_11_n_927),
	.A2(add_8_11_n_816),
	.B(add_8_11_n_916));
   NAND2xp33_ASAP7_75t_R add_8_11_g1198__6131 (.Y(add_8_11_n_811),
	.A(add_8_11_n_995),
	.B(add_8_11_n_820));
   NAND2xp33_ASAP7_75t_R add_8_11_g1199__1881 (.Y(add_8_11_n_813),
	.A(add_8_11_n_930),
	.B(add_8_11_n_831));
   INVxp33_ASAP7_75t_R add_8_11_g1201 (.Y(add_8_11_n_816),
	.A(add_8_11_n_817));
   OAI21xp33_ASAP7_75t_R add_8_11_g1202__7482 (.Y(add_8_11_n_817),
	.A1(add_8_11_n_933),
	.A2(add_8_11_n_911),
	.B(add_8_11_n_937));
   OAI21xp33_ASAP7_75t_R add_8_11_g1203__4733 (.Y(add_8_11_n_820),
	.A1(add_8_11_n_931),
	.A2(add_8_11_n_913),
	.B(add_8_11_n_906));
   OAI21xp33_ASAP7_75t_R add_8_11_g1204__6161 (.Y(add_8_11_n_822),
	.A1(add_8_11_n_988),
	.A2(add_8_11_n_983),
	.B(add_8_11_n_951));
   INVxp33_ASAP7_75t_R add_8_11_g1205 (.Y(add_8_11_n_824),
	.A(add_8_11_n_825));
   OAI21xp33_ASAP7_75t_R add_8_11_g1206__9315 (.Y(add_8_11_n_825),
	.A1(add_8_11_n_985),
	.A2(n_251),
	.B(add_8_11_n_969));
   OA21x2_ASAP7_75t_R add_8_11_g1207__9945 (.Y(add_8_11_n_827),
	.A1(add_8_11_n_1000),
	.A2(add_8_11_n_923),
	.B(n_255));
   OA21x2_ASAP7_75t_R add_8_11_g1208__2883 (.Y(add_8_11_n_829),
	.A1(add_8_11_n_993),
	.A2(add_8_11_n_991),
	.B(add_8_11_n_1010));
   OAI21xp33_ASAP7_75t_R add_8_11_g1209__2346 (.Y(add_8_11_n_831),
	.A1(add_8_11_n_996),
	.A2(n_257),
	.B(add_8_11_n_910));
   NOR3xp33_ASAP7_75t_R add_8_11_g1210__1666 (.Y(add_8_11_n_833),
	.A(add_8_11_n_929),
	.B(add_8_11_n_922),
	.C(add_8_11_n_996));
   OR3x1_ASAP7_75t_R add_8_11_g1211__7410 (.Y(add_8_11_n_837),
	.A(add_8_11_n_927),
	.B(add_8_11_n_920),
	.C(add_8_11_n_933));
   NOR4xp25_ASAP7_75t_R add_8_11_g1212__6417 (.Y(add_8_11_n_839),
	.A(add_8_11_n_994),
	.B(add_8_11_n_931),
	.C(add_8_11_n_921),
	.D(add_8_11_n_987));
   OR2x2_ASAP7_75t_R add_8_11_g1213__5477 (.Y(add_8_11_n_843),
	.A(add_8_11_n_914),
	.B(add_8_11_n_991));
   NOR2xp33_ASAP7_75t_R add_8_11_g1214__2398 (.Y(add_8_11_n_846),
	.A(add_8_11_n_917),
	.B(add_8_11_n_983));
   OR2x2_ASAP7_75t_R add_8_11_g1215__5107 (.Y(add_8_11_n_849),
	.A(add_8_11_n_998),
	.B(add_8_11_n_982));
   AOI21xp33_ASAP7_75t_R add_8_11_g1216__6260 (.Y(add_8_11_n_851),
	.A1(iA[19]),
	.A2(iB[19]),
	.B(add_8_11_n_982));
   NAND2xp33_ASAP7_75t_R add_8_11_g1217__4319 (.Y(add_8_11_n_852),
	.A(add_8_11_n_990),
	.B(add_8_11_n_930));
   AND2x2_ASAP7_75t_R add_8_11_g1218__8428 (.Y(add_8_11_n_854),
	.A(add_8_11_n_997),
	.B(add_8_11_n_910));
   AOI21xp33_ASAP7_75t_R add_8_11_g1220__6783 (.Y(add_8_11_n_858),
	.A1(iA[15]),
	.A2(iB[15]),
	.B(add_8_11_n_922));
   AND2x2_ASAP7_75t_R add_8_11_g1221__3680 (.Y(add_8_11_n_859),
	.A(add_8_11_n_984),
	.B(add_8_11_n_969));
   NAND2xp33_ASAP7_75t_R add_8_11_g1222__1617 (.Y(add_8_11_n_862),
	.A(add_8_11_n_918),
	.B(add_8_11_n_999));
   AOI21xp33_ASAP7_75t_R add_8_11_g1223__2802 (.Y(add_8_11_n_863),
	.A1(iA[11]),
	.A2(iB[11]),
	.B(add_8_11_n_921));
   NAND2xp33_ASAP7_75t_R add_8_11_g1224__1705 (.Y(add_8_11_n_864),
	.A(add_8_11_n_993),
	.B(add_8_11_n_915));
   NOR2xp33_ASAP7_75t_R add_8_11_g1227__7098 (.Y(add_8_11_n_869),
	.A(add_8_11_n_981),
	.B(add_8_11_n_907));
   NOR2xp33_ASAP7_75t_R add_8_11_g1228__6131 (.Y(add_8_11_n_871),
	.A(add_8_11_n_972),
	.B(add_8_11_n_970));
   AOI21xp33_ASAP7_75t_R add_8_11_g1231__7482 (.Y(add_8_11_n_875),
	.A1(iA[5]),
	.A2(iB[5]),
	.B(add_8_11_n_991));
   NAND2xp33_ASAP7_75t_R add_8_11_g1233__6161 (.Y(add_8_11_n_878),
	.A(add_8_11_n_904),
	.B(add_8_11_n_976));
   NOR2xp33_ASAP7_75t_R add_8_11_g1235__9945 (.Y(add_8_11_n_882),
	.A(add_8_11_n_909),
	.B(add_8_11_n_978));
   AOI21xp33_ASAP7_75t_R add_8_11_g1236__2883 (.Y(add_8_11_n_884),
	.A1(FE_PHN12_iA_26),
	.A2(FE_PHN10_iB_26),
	.B(add_8_11_n_905));
   AOI21xp33_ASAP7_75t_R add_8_11_g1238__1666 (.Y(add_8_11_n_888),
	.A1(iA[25]),
	.A2(iB[25]),
	.B(add_8_11_n_983));
   NAND2xp33_ASAP7_75t_R add_8_11_g1239__7410 (.Y(add_8_11_n_889),
	.A(add_8_11_n_919),
	.B(add_8_11_n_995));
   AOI21xp33_ASAP7_75t_R add_8_11_g1240__6417 (.Y(add_8_11_n_891),
	.A1(iA[23]),
	.A2(iB[23]),
	.B(add_8_11_n_920));
   AND2x2_ASAP7_75t_R add_8_11_g1241__5477 (.Y(add_8_11_n_892),
	.A(add_8_11_n_986),
	.B(add_8_11_n_913));
   NAND2xp33_ASAP7_75t_R add_8_11_g1242__2398 (.Y(add_8_11_n_894),
	.A(add_8_11_n_916),
	.B(add_8_11_n_928));
   AND2x2_ASAP7_75t_R add_8_11_g1243__5107 (.Y(add_8_11_n_895),
	.A(add_8_11_n_932),
	.B(add_8_11_n_906));
   AOI21xp33_ASAP7_75t_R add_8_11_g1244__6260 (.Y(add_8_11_n_898),
	.A1(FE_PHN13_iA_21),
	.A2(FE_PHN15_iB_21),
	.B(add_8_11_n_933));
   AND2x2_ASAP7_75t_R add_8_11_g1245__4319 (.Y(add_8_11_n_899),
	.A(add_8_11_n_968),
	.B(add_8_11_n_911));
   NOR2xp33_ASAP7_75t_R add_8_11_g1246__8428 (.Y(add_8_11_n_901),
	.A(add_8_11_n_917),
	.B(add_8_11_n_989));
   INVxp33_ASAP7_75t_R add_8_11_g1248 (.Y(add_8_11_n_903),
	.A(add_8_11_n_904));
   INVxp33_ASAP7_75t_R add_8_11_g1249 (.Y(add_8_11_n_908),
	.A(add_8_11_n_909));
   INVxp33_ASAP7_75t_R add_8_11_g1250 (.Y(add_8_11_n_915),
	.A(add_8_11_n_914));
   INVxp33_ASAP7_75t_R add_8_11_g1254 (.Y(add_8_11_n_928),
	.A(add_8_11_n_927));
   INVxp33_ASAP7_75t_R add_8_11_g1255 (.Y(add_8_11_n_930),
	.A(add_8_11_n_929));
   INVxp33_ASAP7_75t_R add_8_11_g1256 (.Y(add_8_11_n_932),
	.A(add_8_11_n_931));
   NOR2xp33_ASAP7_75t_R add_8_11_g1257__6783 (.Y(add_8_11_n_934),
	.A(iB[2]),
	.B(iA[2]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1258__3680 (.Y(add_8_11_n_937),
	.A(iB[21]),
	.B(iA[21]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1259__1617 (.Y(add_8_11_n_940),
	.A(iB[12]),
	.B(iA[12]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1260__2802 (.Y(add_8_11_n_904),
	.A(iB[29]),
	.B(iA[29]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1261__1705 (.Y(add_8_11_n_905),
	.A(iB[26]),
	.B(FE_PHN12_iA_26));
   NAND2xp33_ASAP7_75t_R add_8_11_g1262__5122 (.Y(add_8_11_n_906),
	.A(iB[9]),
	.B(iA[9]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1263__8246 (.Y(add_8_11_n_945),
	.A(iB[7]),
	.B(iA[7]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1264__7098 (.Y(add_8_11_n_948),
	.A(iB[30]),
	.B(iA[30]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1265__6131 (.Y(add_8_11_n_951),
	.A(iB[25]),
	.B(iA[25]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1266__1881 (.Y(add_8_11_n_954),
	.A(iB[11]),
	.B(iA[11]));
   AND2x2_ASAP7_75t_R add_8_11_g1267__5115 (.Y(add_8_11_n_907),
	.A(iB[6]),
	.B(iA[6]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1268__7482 (.Y(add_8_11_n_957),
	.A(FE_PHN10_iB_26),
	.B(FE_PHN12_iA_26));
   NOR2xp33_ASAP7_75t_R add_8_11_g1269__4733 (.Y(add_8_11_n_909),
	.A(iB[27]),
	.B(iA[27]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1270__6161 (.Y(add_8_11_n_910),
	.A(iB[13]),
	.B(iA[13]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1271__9315 (.Y(add_8_11_n_911),
	.A(iB[20]),
	.B(iA[20]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1273__2883 (.Y(add_8_11_n_913),
	.A(iB[8]),
	.B(iA[8]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1274__2346 (.Y(add_8_11_n_914),
	.A(iB[4]),
	.B(iA[4]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1275__1666 (.Y(add_8_11_n_916),
	.A(iB[22]),
	.B(iA[22]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1276__7410 (.Y(add_8_11_n_917),
	.A(iB[24]),
	.B(iA[24]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1277__6417 (.Y(add_8_11_n_918),
	.A(iB[18]),
	.B(iA[18]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1278__5477 (.Y(add_8_11_n_919),
	.A(iB[10]),
	.B(iA[10]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1279__2398 (.Y(add_8_11_n_920),
	.A(iB[23]),
	.B(iA[23]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1280__5107 (.Y(add_8_11_n_921),
	.A(iB[11]),
	.B(iA[11]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1281__6260 (.Y(add_8_11_n_922),
	.A(iB[15]),
	.B(iA[15]));
   NAND2x1p5_ASAP7_75t_R add_8_11_g1282__4319 (.Y(add_8_11_n_923),
	.A(iB[0]),
	.B(iA[0]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1283__8428 (.Y(add_8_11_n_927),
	.A(iB[22]),
	.B(iA[22]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1284__5526 (.Y(add_8_11_n_929),
	.A(iB[14]),
	.B(iA[14]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1285__6783 (.Y(add_8_11_n_931),
	.A(iB[9]),
	.B(iA[9]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1286__3680 (.Y(add_8_11_n_933),
	.A(iB[21]),
	.B(iA[21]));
   INVxp33_ASAP7_75t_R add_8_11_g1287 (.Y(add_8_11_n_971),
	.A(add_8_11_n_972));
   INVxp33_ASAP7_75t_R add_8_11_g1288 (.Y(add_8_11_n_980),
	.A(add_8_11_n_981));
   INVxp33_ASAP7_75t_R add_8_11_g1289 (.Y(add_8_11_n_984),
	.A(add_8_11_n_985));
   INVxp33_ASAP7_75t_R add_8_11_g1290 (.Y(add_8_11_n_986),
	.A(add_8_11_n_987));
   INVxp33_ASAP7_75t_R add_8_11_g1291 (.Y(add_8_11_n_989),
	.A(add_8_11_n_988));
   INVxp33_ASAP7_75t_R add_8_11_g1292 (.Y(add_8_11_n_995),
	.A(add_8_11_n_994));
   INVxp33_ASAP7_75t_R add_8_11_g1293 (.Y(add_8_11_n_997),
	.A(add_8_11_n_996));
   INVxp33_ASAP7_75t_R add_8_11_g1294 (.Y(add_8_11_n_999),
	.A(add_8_11_n_998));
   NOR2x1_ASAP7_75t_R add_8_11_g1295__1617 (.Y(add_8_11_n_1000),
	.A(iB[1]),
	.B(iA[1]));
   OR2x2_ASAP7_75t_R add_8_11_g1296__2802 (.Y(add_8_11_n_968),
	.A(iA[20]),
	.B(iB[20]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1297__1705 (.Y(add_8_11_n_969),
	.A(iB[17]),
	.B(iA[17]));
   AND2x2_ASAP7_75t_R add_8_11_g1298__5122 (.Y(add_8_11_n_970),
	.A(iB[3]),
	.B(iA[3]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1299__8246 (.Y(add_8_11_n_972),
	.A(iB[3]),
	.B(iA[3]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1300__7098 (.Y(add_8_11_n_1007),
	.A(iB[28]),
	.B(iA[28]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1301__6131 (.Y(add_8_11_n_1010),
	.A(iB[5]),
	.B(iA[5]));
   OR2x2_ASAP7_75t_R add_8_11_g1305__4733 (.Y(add_8_11_n_976),
	.A(iA[29]),
	.B(iB[29]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1306__6161 (.Y(add_8_11_n_1015),
	.A(iB[16]),
	.B(iA[16]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1307__9315 (.Y(add_8_11_n_1018),
	.A(iB[23]),
	.B(iA[23]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1308__9945 (.Y(add_8_11_n_1019),
	.A(iB[15]),
	.B(iA[15]));
   AND2x2_ASAP7_75t_R add_8_11_g1310__2346 (.Y(add_8_11_n_978),
	.A(iB[27]),
	.B(iA[27]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1311__1666 (.Y(add_8_11_n_1022),
	.A(iB[19]),
	.B(iA[19]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1313__6417 (.Y(add_8_11_n_981),
	.A(iB[6]),
	.B(iA[6]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1314__5477 (.Y(add_8_11_n_982),
	.A(iB[19]),
	.B(iA[19]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1315__2398 (.Y(add_8_11_n_983),
	.A(iB[25]),
	.B(iA[25]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1316__5107 (.Y(add_8_11_n_985),
	.A(iB[17]),
	.B(iA[17]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1317__6260 (.Y(add_8_11_n_987),
	.A(iB[8]),
	.B(iA[8]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1318__4319 (.Y(add_8_11_n_988),
	.A(iB[24]),
	.B(iA[24]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1319__8428 (.Y(add_8_11_n_990),
	.A(iB[14]),
	.B(iA[14]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1320__5526 (.Y(add_8_11_n_991),
	.A(iB[5]),
	.B(iA[5]));
   NAND2xp33_ASAP7_75t_R add_8_11_g1322__3680 (.Y(add_8_11_n_993),
	.A(iB[4]),
	.B(iA[4]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1323__1617 (.Y(add_8_11_n_994),
	.A(iB[10]),
	.B(iA[10]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1324__2802 (.Y(add_8_11_n_996),
	.A(iB[13]),
	.B(iA[13]));
   NOR2xp33_ASAP7_75t_R add_8_11_g1325__1705 (.Y(add_8_11_n_998),
	.A(iB[18]),
	.B(iA[18]));
   XNOR2xp5_ASAP7_75t_R g2 (.Y(n_219),
	.A(add_8_11_n_889),
	.B(add_8_11_n_767));
   XNOR2xp5_ASAP7_75t_R g1366 (.Y(FE_PHN9_n_220),
	.A(n_250),
	.B(add_8_11_n_755));
   OAI21xp33_ASAP7_75t_R g1367 (.Y(n_221),
	.A1(iA[0]),
	.A2(iB[0]),
	.B(add_8_11_n_923));
   XNOR2xp5_ASAP7_75t_R g1368 (.Y(n_222),
	.A(n_260),
	.B(add_8_11_n_703));
   XOR2xp5_ASAP7_75t_R g1369 (.Y(n_223),
	.A(add_8_11_n_901),
	.B(add_8_11_n_722));
   XNOR2xp5_ASAP7_75t_R g1370 (.Y(FE_PHN11_n_224),
	.A(add_8_11_n_858),
	.B(add_8_11_n_743));
   XNOR2xp5_ASAP7_75t_R g1371 (.Y(FE_PHN14_n_225),
	.A(add_8_11_n_891),
	.B(add_8_11_n_712));
   XNOR2xp5_ASAP7_75t_R g1372 (.Y(n_226),
	.A(add_8_11_n_854),
	.B(add_8_11_n_759));
   XNOR2xp5_ASAP7_75t_R g1373 (.Y(n_227),
	.A(add_8_11_n_852),
	.B(add_8_11_n_752));
   XNOR2xp5_ASAP7_75t_R g1374 (.Y(n_228),
	.A(add_8_11_n_894),
	.B(add_8_11_n_720));
   XNOR2xp5_ASAP7_75t_R g1375 (.Y(FE_PHN8_n_229),
	.A(n_256),
	.B(add_8_11_n_769));
   XNOR2xp5_ASAP7_75t_R g1376 (.Y(n_230),
	.A(add_8_11_n_882),
	.B(add_8_11_n_707));
   XNOR2xp5_ASAP7_75t_R g1377 (.Y(n_231),
	.A(add_8_11_n_863),
	.B(add_8_11_n_753));
   XNOR2xp5_ASAP7_75t_R g1378 (.Y(n_232),
	.A(add_8_11_n_898),
	.B(add_8_11_n_727));
   XNOR2xp5_ASAP7_75t_R g1379 (.Y(n_233),
	.A(n_258),
	.B(add_8_11_n_696));
   XNOR2xp5_ASAP7_75t_R g1380 (.Y(n_234),
	.A(add_8_11_n_923),
	.B(n_254));
   XOR2xp5_ASAP7_75t_R g1381 (.Y(n_235),
	.A(add_8_11_n_878),
	.B(add_8_11_n_699));
   XNOR2xp5_ASAP7_75t_R g1382 (.Y(n_236),
	.A(add_8_11_n_884),
	.B(add_8_11_n_714));
   XNOR2xp5_ASAP7_75t_R g1383 (.Y(n_237),
	.A(add_8_11_n_899),
	.B(add_8_11_n_736));
   XNOR2xp5_ASAP7_75t_R g1384 (.Y(n_238),
	.A(add_8_11_n_892),
	.B(add_8_11_n_776));
   XNOR2xp5_ASAP7_75t_R g1385 (.Y(FE_PHN7_n_239),
	.A(n_262),
	.B(add_8_11_n_781));
   XNOR2xp5_ASAP7_75t_R g1386 (.Y(n_240),
	.A(add_8_11_n_851),
	.B(add_8_11_n_733));
   XNOR2xp5_ASAP7_75t_R g1387 (.Y(n_241),
	.A(add_8_11_n_869),
	.B(add_8_11_n_787));
   XNOR2xp5_ASAP7_75t_R g1388 (.Y(n_242),
	.A(add_8_11_n_875),
	.B(add_8_11_n_785));
   XNOR2xp5_ASAP7_75t_R g1389 (.Y(n_243),
	.A(add_8_11_n_888),
	.B(add_8_11_n_711));
   XNOR2xp5_ASAP7_75t_R g1390 (.Y(n_244),
	.A(add_8_11_n_862),
	.B(add_8_11_n_739));
   XNOR2xp5_ASAP7_75t_R g1391 (.Y(n_245),
	.A(add_8_11_n_864),
	.B(add_8_11_n_799));
   XNOR2xp5_ASAP7_75t_R g1392 (.Y(n_246),
	.A(add_8_11_n_871),
	.B(add_8_11_n_805));
   XNOR2xp5_ASAP7_75t_R g1393 (.Y(n_247),
	.A(add_8_11_n_859),
	.B(add_8_11_n_740));
   XNOR2xp5_ASAP7_75t_R g1394 (.Y(FE_PHN6_n_248),
	.A(n_252),
	.B(add_8_11_n_827));
   XNOR2xp5_ASAP7_75t_R g1395 (.Y(n_249),
	.A(add_8_11_n_895),
	.B(add_8_11_n_768));
   HAxp5_ASAP7_75t_R g1396 (.CON(n_251),
	.SN(n_250),
	.A(iA[16]),
	.B(iB[16]));
   HAxp5_ASAP7_75t_R g1397 (.CON(n_253),
	.SN(n_252),
	.A(iA[2]),
	.B(iB[2]));
   HAxp5_ASAP7_75t_R g1398 (.CON(n_255),
	.SN(n_254),
	.A(iA[1]),
	.B(iB[1]));
   HAxp5_ASAP7_75t_R g1399 (.CON(n_257),
	.SN(n_256),
	.A(iA[12]),
	.B(iB[12]));
   HAxp5_ASAP7_75t_R g1400 (.CON(n_259),
	.SN(n_258),
	.A(FE_PHN2_iA_30),
	.B(FE_PHN4_iB_30));
   HAxp5_ASAP7_75t_R g1401 (.CON(n_261),
	.SN(FE_PHN16_n_260),
	.A(iA[28]),
	.B(iB[28]));
   HAxp5_ASAP7_75t_R g1402 (.CON(n_263),
	.SN(n_262),
	.A(iA[7]),
	.B(iB[7]));
endmodule

