
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Apr 11 2026 12:42:15 +07 (Apr 11 2026 05:42:15 UTC)

// Verification Directory fv/Adder32 

module Adder32(iClk, iA, iB, oS);
  input iClk;
  input [31:0] iA, iB;
  output [31:0] oS;
  wire iClk;
  wire [31:0] iA, iB;
  wire [31:0] oS;
  wire add_8_11_n_693, add_8_11_n_696, add_8_11_n_699, add_8_11_n_703,
       add_8_11_n_707, add_8_11_n_711, add_8_11_n_712, add_8_11_n_713;
  wire add_8_11_n_714, add_8_11_n_720, add_8_11_n_722, add_8_11_n_723,
       add_8_11_n_725, add_8_11_n_727, add_8_11_n_729, add_8_11_n_731;
  wire add_8_11_n_733, add_8_11_n_736, add_8_11_n_739, add_8_11_n_740,
       add_8_11_n_741, add_8_11_n_742, add_8_11_n_743, add_8_11_n_748;
  wire add_8_11_n_749, add_8_11_n_752, add_8_11_n_753, add_8_11_n_754,
       add_8_11_n_755, add_8_11_n_759, add_8_11_n_762, add_8_11_n_763;
  wire add_8_11_n_767, add_8_11_n_768, add_8_11_n_769, add_8_11_n_773,
       add_8_11_n_774, add_8_11_n_775, add_8_11_n_776, add_8_11_n_777;
  wire add_8_11_n_781, add_8_11_n_785, add_8_11_n_786, add_8_11_n_787,
       add_8_11_n_790, add_8_11_n_792, add_8_11_n_793, add_8_11_n_795;
  wire add_8_11_n_796, add_8_11_n_798, add_8_11_n_799, add_8_11_n_802,
       add_8_11_n_805, add_8_11_n_806, add_8_11_n_811, add_8_11_n_813;
  wire add_8_11_n_816, add_8_11_n_817, add_8_11_n_820, add_8_11_n_822,
       add_8_11_n_824, add_8_11_n_825, add_8_11_n_827, add_8_11_n_829;
  wire add_8_11_n_831, add_8_11_n_833, add_8_11_n_837, add_8_11_n_839,
       add_8_11_n_843, add_8_11_n_846, add_8_11_n_849, add_8_11_n_851;
  wire add_8_11_n_852, add_8_11_n_854, add_8_11_n_858, add_8_11_n_859,
       add_8_11_n_862, add_8_11_n_863, add_8_11_n_864, add_8_11_n_869;
  wire add_8_11_n_871, add_8_11_n_875, add_8_11_n_878, add_8_11_n_882,
       add_8_11_n_884, add_8_11_n_888, add_8_11_n_889, add_8_11_n_891;
  wire add_8_11_n_892, add_8_11_n_894, add_8_11_n_895, add_8_11_n_898,
       add_8_11_n_899, add_8_11_n_901, add_8_11_n_902, add_8_11_n_903;
  wire add_8_11_n_904, add_8_11_n_905, add_8_11_n_906, add_8_11_n_907,
       add_8_11_n_908, add_8_11_n_909, add_8_11_n_910, add_8_11_n_911;
  wire add_8_11_n_913, add_8_11_n_914, add_8_11_n_915, add_8_11_n_916,
       add_8_11_n_917, add_8_11_n_918, add_8_11_n_919, add_8_11_n_920;
  wire add_8_11_n_921, add_8_11_n_922, add_8_11_n_923, add_8_11_n_927,
       add_8_11_n_928, add_8_11_n_929, add_8_11_n_930, add_8_11_n_931;
  wire add_8_11_n_932, add_8_11_n_933, add_8_11_n_934, add_8_11_n_937,
       add_8_11_n_940, add_8_11_n_945, add_8_11_n_948, add_8_11_n_951;
  wire add_8_11_n_954, add_8_11_n_957, add_8_11_n_968, add_8_11_n_969,
       add_8_11_n_970, add_8_11_n_971, add_8_11_n_972, add_8_11_n_976;
  wire add_8_11_n_978, add_8_11_n_980, add_8_11_n_981, add_8_11_n_982,
       add_8_11_n_983, add_8_11_n_984, add_8_11_n_985, add_8_11_n_986;
  wire add_8_11_n_987, add_8_11_n_988, add_8_11_n_989, add_8_11_n_990,
       add_8_11_n_991, add_8_11_n_993, add_8_11_n_994, add_8_11_n_995;
  wire add_8_11_n_996, add_8_11_n_997, add_8_11_n_998, add_8_11_n_999,
       add_8_11_n_1000, add_8_11_n_1007, add_8_11_n_1010,
       add_8_11_n_1015;
  wire add_8_11_n_1018, add_8_11_n_1019, add_8_11_n_1022, n_3, n_17,
       n_18, n_21, n_33;
  wire n_35, n_41, n_46, n_48, n_54, n_66, n_69, n_78;
  wire n_80, n_82, n_83, n_86, n_116, n_186, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_253, n_254, n_255, n_256, n_257, n_258, n_259, n_260;
  wire n_261, n_262, n_263;
  DFFHQNx1_ASAP7_75t_R \oS_reg[12] (.CLK (iClk), .D (n_229), .QN
       (oS[12]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[30] (.CLK (iClk), .D (n_233), .QN
       (oS[30]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[9] (.CLK (iClk), .D (n_249), .QN
       (oS[9]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[28] (.CLK (iClk), .D (n_222), .QN
       (oS[28]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[24] (.CLK (iClk), .D (n_223), .QN
       (oS[24]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[16] (.CLK (iClk), .D (n_220), .QN
       (oS[16]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[4] (.CLK (iClk), .D (n_245), .QN
       (oS[4]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[0] (.CLK (iClk), .D (n_221), .QN
       (oS[0]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[15] (.CLK (iClk), .D (n_224), .QN
       (oS[15]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[23] (.CLK (iClk), .D (n_225), .QN
       (oS[23]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[14] (.CLK (iClk), .D (n_227), .QN
       (oS[14]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[13] (.CLK (iClk), .D (n_226), .QN
       (oS[13]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[27] (.CLK (iClk), .D (n_230), .QN
       (oS[27]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[22] (.CLK (iClk), .D (n_228), .QN
       (oS[22]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[20] (.CLK (iClk), .D (n_237), .QN
       (oS[20]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[10] (.CLK (iClk), .D (n_219), .QN
       (oS[10]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[2] (.CLK (iClk), .D (n_248), .QN
       (oS[2]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[21] (.CLK (iClk), .D (n_232), .QN
       (oS[21]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[31] (.CLK (iClk), .D (n_116), .QN
       (oS[31]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[1] (.CLK (iClk), .D (n_234), .QN
       (oS[1]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[29] (.CLK (iClk), .D (n_235), .QN
       (oS[29]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[26] (.CLK (iClk), .D (n_236), .QN
       (oS[26]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[8] (.CLK (iClk), .D (n_238), .QN
       (oS[8]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[7] (.CLK (iClk), .D (n_239), .QN
       (oS[7]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[19] (.CLK (iClk), .D (n_240), .QN
       (oS[19]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[6] (.CLK (iClk), .D (n_241), .QN
       (oS[6]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[5] (.CLK (iClk), .D (n_242), .QN
       (oS[5]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[25] (.CLK (iClk), .D (n_243), .QN
       (oS[25]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[18] (.CLK (iClk), .D (n_244), .QN
       (oS[18]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[3] (.CLK (iClk), .D (n_246), .QN
       (oS[3]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[17] (.CLK (iClk), .D (n_247), .QN
       (oS[17]));
  DFFHQNx1_ASAP7_75t_R \oS_reg[11] (.CLK (iClk), .D (n_231), .QN
       (oS[11]));
  INVxp67_ASAP7_75t_R g51(.A (n_186), .Y (n_116));
  INVx1_ASAP7_75t_R g141(.A (n_54), .Y (n_86));
  INVx1_ASAP7_75t_R g152(.A (n_48), .Y (n_83));
  INVx2_ASAP7_75t_R g154(.A (n_46), .Y (n_82));
  INVx1_ASAP7_75t_R g161(.A (n_41), .Y (n_80));
  INVx2_ASAP7_75t_R g76(.A (n_17), .Y (n_78));
  INVx1_ASAP7_75t_R g115(.A (n_35), .Y (n_69));
  INVxp67_ASAP7_75t_R g121(.A (n_3), .Y (n_66));
  INVx3_ASAP7_75t_R g142(.A (iA[1]), .Y (n_54));
  INVx3_ASAP7_75t_R g153(.A (iB[1]), .Y (n_48));
  INVx3_ASAP7_75t_R g155(.A (iB[0]), .Y (n_46));
  INVx1_ASAP7_75t_R g162(.A (iB[2]), .Y (n_41));
  INVx1_ASAP7_75t_R g116(.A (iA[2]), .Y (n_35));
  HB1xp67_ASAP7_75t_R g156(.A (iB[28]), .Y (n_33));
  HB1xp67_ASAP7_75t_R g112(.A (iA[28]), .Y (n_21));
  HB1xp67_ASAP7_75t_R g110(.A (iA[26]), .Y (n_18));
  INVx3_ASAP7_75t_R g77(.A (iA[0]), .Y (n_17));
  INVx1_ASAP7_75t_R g122(.A (iB[26]), .Y (n_3));
  XNOR2xp5_ASAP7_75t_R add_8_11_g1105__2398(.A (add_8_11_n_902), .B
       (add_8_11_n_693), .Y (n_186));
  OAI21xp5_ASAP7_75t_R add_8_11_g1106__5107(.A1 (add_8_11_n_948), .A2
       (add_8_11_n_696), .B (n_259), .Y (add_8_11_n_693));
  AOI21xp5_ASAP7_75t_R add_8_11_g1108__4319(.A1 (add_8_11_n_699), .A2
       (add_8_11_n_976), .B (add_8_11_n_903), .Y (add_8_11_n_696));
  OAI21x1_ASAP7_75t_R add_8_11_g1111__5526(.A1 (add_8_11_n_1007), .A2
       (add_8_11_n_703), .B (n_261), .Y (add_8_11_n_699));
  AOI21xp5_ASAP7_75t_R add_8_11_g1114__3680(.A1 (add_8_11_n_707), .A2
       (add_8_11_n_908), .B (add_8_11_n_978), .Y (add_8_11_n_703));
  OAI21xp5_ASAP7_75t_R add_8_11_g1116__2802(.A1 (add_8_11_n_905), .A2
       (add_8_11_n_713), .B (add_8_11_n_957), .Y (add_8_11_n_707));
  OAI21xp5_ASAP7_75t_R add_8_11_g1120__7098(.A1 (add_8_11_n_917), .A2
       (add_8_11_n_722), .B (add_8_11_n_988), .Y (add_8_11_n_711));
  OAI21xp33_ASAP7_75t_R add_8_11_g1121__6131(.A1 (add_8_11_n_927), .A2
       (add_8_11_n_720), .B (add_8_11_n_916), .Y (add_8_11_n_712));
  INVx1_ASAP7_75t_R add_8_11_g1122(.A (add_8_11_n_714), .Y
       (add_8_11_n_713));
  AO21x1_ASAP7_75t_R add_8_11_g1123__1881(.A1 (add_8_11_n_846), .A2
       (add_8_11_n_723), .B (add_8_11_n_822), .Y (add_8_11_n_714));
  NOR2xp33_ASAP7_75t_R add_8_11_g1127__4733(.A (add_8_11_n_817), .B
       (add_8_11_n_725), .Y (add_8_11_n_720));
  INVxp67_ASAP7_75t_R add_8_11_g1129(.A (add_8_11_n_723), .Y
       (add_8_11_n_722));
  OAI21xp5_ASAP7_75t_R add_8_11_g1130__6161(.A1 (add_8_11_n_837), .A2
       (add_8_11_n_731), .B (add_8_11_n_792), .Y (add_8_11_n_723));
  NOR2xp33_ASAP7_75t_R add_8_11_g1132__9945(.A (add_8_11_n_933), .B
       (add_8_11_n_729), .Y (add_8_11_n_725));
  NAND2xp5_ASAP7_75t_R add_8_11_g1133__2883(.A (add_8_11_n_911), .B
       (add_8_11_n_729), .Y (add_8_11_n_727));
  HB1xp67_ASAP7_75t_R add_8_11_g1136(.A (add_8_11_n_731), .Y
       (add_8_11_n_729));
  NAND2xp5_ASAP7_75t_R add_8_11_g1137__1666(.A (add_8_11_n_968), .B
       (add_8_11_n_736), .Y (add_8_11_n_731));
  OAI21xp33_ASAP7_75t_R add_8_11_g1138__7410(.A1 (add_8_11_n_998), .A2
       (add_8_11_n_739), .B (add_8_11_n_918), .Y (add_8_11_n_733));
  OAI21xp5_ASAP7_75t_R add_8_11_g1140__5477(.A1 (add_8_11_n_849), .A2
       (add_8_11_n_742), .B (add_8_11_n_795), .Y (add_8_11_n_736));
  NOR2xp33_ASAP7_75t_R add_8_11_g1143__6260(.A (add_8_11_n_825), .B
       (add_8_11_n_741), .Y (add_8_11_n_739));
  NAND2xp5_ASAP7_75t_R add_8_11_g1144__4319(.A (n_251), .B
       (add_8_11_n_748), .Y (add_8_11_n_740));
  INVxp67_ASAP7_75t_R add_8_11_g1145(.A (add_8_11_n_742), .Y
       (add_8_11_n_741));
  NAND2xp5_ASAP7_75t_R add_8_11_g1146__8428(.A (add_8_11_n_984), .B
       (add_8_11_n_749), .Y (add_8_11_n_742));
  OAI21xp33_ASAP7_75t_R add_8_11_g1147__5526(.A1 (add_8_11_n_929), .A2
       (add_8_11_n_752), .B (add_8_11_n_990), .Y (add_8_11_n_743));
  INVxp67_ASAP7_75t_R add_8_11_g1151(.A (add_8_11_n_749), .Y
       (add_8_11_n_748));
  NOR2xp33_ASAP7_75t_R add_8_11_g1152__2802(.A (add_8_11_n_1015), .B
       (add_8_11_n_755), .Y (add_8_11_n_749));
  AOI21xp5_ASAP7_75t_R add_8_11_g1154__5122(.A1 (add_8_11_n_763), .A2
       (add_8_11_n_997), .B (add_8_11_n_831), .Y (add_8_11_n_752));
  OAI21xp5_ASAP7_75t_R add_8_11_g1155__8246(.A1 (add_8_11_n_994), .A2
       (add_8_11_n_767), .B (add_8_11_n_919), .Y (add_8_11_n_753));
  HB1xp67_ASAP7_75t_R add_8_11_g1156(.A (add_8_11_n_755), .Y
       (add_8_11_n_754));
  AOI21xp5_ASAP7_75t_R add_8_11_g1157__7098(.A1 (add_8_11_n_763), .A2
       (add_8_11_n_833), .B (add_8_11_n_793), .Y (add_8_11_n_755));
  NAND2xp5_ASAP7_75t_R add_8_11_g1159__1881(.A (n_257), .B
       (add_8_11_n_762), .Y (add_8_11_n_759));
  INVxp67_ASAP7_75t_R add_8_11_g1164(.A (add_8_11_n_763), .Y
       (add_8_11_n_762));
  NOR2x1_ASAP7_75t_R add_8_11_g1165__4733(.A (add_8_11_n_940), .B
       (add_8_11_n_769), .Y (add_8_11_n_763));
  AOI21xp5_ASAP7_75t_R add_8_11_g1166__6161(.A1 (add_8_11_n_773), .A2
       (add_8_11_n_932), .B (add_8_11_n_820), .Y (add_8_11_n_767));
  NAND2xp5_ASAP7_75t_R add_8_11_g1167__9315(.A (add_8_11_n_913), .B
       (add_8_11_n_774), .Y (add_8_11_n_768));
  AOI21x1_ASAP7_75t_R add_8_11_g1169__9945(.A1 (add_8_11_n_776), .A2
       (add_8_11_n_839), .B (add_8_11_n_790), .Y (add_8_11_n_769));
  INVxp67_ASAP7_75t_R add_8_11_g1171(.A (add_8_11_n_774), .Y
       (add_8_11_n_773));
  NAND2xp5_ASAP7_75t_R add_8_11_g1172__2346(.A (add_8_11_n_986), .B
       (add_8_11_n_776), .Y (add_8_11_n_774));
  INVxp67_ASAP7_75t_R add_8_11_g1173(.A (add_8_11_n_777), .Y
       (add_8_11_n_775));
  INVxp67_ASAP7_75t_R add_8_11_g1175(.A (add_8_11_n_776), .Y
       (add_8_11_n_777));
  OAI21x1_ASAP7_75t_R add_8_11_g1176__1666(.A1 (add_8_11_n_945), .A2
       (add_8_11_n_781), .B (n_263), .Y (add_8_11_n_776));
  AOI21xp5_ASAP7_75t_R add_8_11_g1178__6417(.A1 (add_8_11_n_787), .A2
       (add_8_11_n_980), .B (add_8_11_n_907), .Y (add_8_11_n_781));
  OAI21xp5_ASAP7_75t_R add_8_11_g1181__5107(.A1 (add_8_11_n_914), .A2
       (add_8_11_n_796), .B (add_8_11_n_993), .Y (add_8_11_n_785));
  HB1xp67_ASAP7_75t_R add_8_11_g1182(.A (add_8_11_n_787), .Y
       (add_8_11_n_786));
  OAI21xp5_ASAP7_75t_R add_8_11_g1183__6260(.A1 (add_8_11_n_843), .A2
       (add_8_11_n_799), .B (add_8_11_n_829), .Y (add_8_11_n_787));
  A2O1A1Ixp33_ASAP7_75t_R add_8_11_g1185__8428(.A1 (add_8_11_n_919),
       .A2 (add_8_11_n_811), .B (add_8_11_n_921), .C (add_8_11_n_954),
       .Y (add_8_11_n_790));
  OA21x2_ASAP7_75t_R add_8_11_g1186__5526(.A1 (add_8_11_n_920), .A2
       (add_8_11_n_806), .B (add_8_11_n_1018), .Y (add_8_11_n_792));
  A2O1A1Ixp33_ASAP7_75t_R add_8_11_g1187__6783(.A1 (add_8_11_n_990),
       .A2 (add_8_11_n_813), .B (add_8_11_n_922), .C (add_8_11_n_1019),
       .Y (add_8_11_n_793));
  OA21x2_ASAP7_75t_R add_8_11_g1188__3680(.A1 (add_8_11_n_982), .A2
       (add_8_11_n_802), .B (add_8_11_n_1022), .Y (add_8_11_n_795));
  INVxp67_ASAP7_75t_R add_8_11_g1189(.A (add_8_11_n_798), .Y
       (add_8_11_n_796));
  INVxp67_ASAP7_75t_R add_8_11_g1191(.A (add_8_11_n_799), .Y
       (add_8_11_n_798));
  AOI21xp5_ASAP7_75t_R add_8_11_g1192__1617(.A1 (add_8_11_n_805), .A2
       (add_8_11_n_971), .B (add_8_11_n_970), .Y (add_8_11_n_799));
  OA21x2_ASAP7_75t_R add_8_11_g1194__1705(.A1 (add_8_11_n_998), .A2
       (add_8_11_n_824), .B (add_8_11_n_918), .Y (add_8_11_n_802));
  OAI21x1_ASAP7_75t_R add_8_11_g1195__5122(.A1 (add_8_11_n_827), .A2
       (add_8_11_n_934), .B (n_253), .Y (add_8_11_n_805));
  OA21x2_ASAP7_75t_R add_8_11_g1196__8246(.A1 (add_8_11_n_927), .A2
       (add_8_11_n_816), .B (add_8_11_n_916), .Y (add_8_11_n_806));
  NAND2xp5_ASAP7_75t_R add_8_11_g1198__6131(.A (add_8_11_n_995), .B
       (add_8_11_n_820), .Y (add_8_11_n_811));
  NAND2xp5_ASAP7_75t_R add_8_11_g1199__1881(.A (add_8_11_n_930), .B
       (add_8_11_n_831), .Y (add_8_11_n_813));
  INVx1_ASAP7_75t_R add_8_11_g1201(.A (add_8_11_n_817), .Y
       (add_8_11_n_816));
  OAI21xp5_ASAP7_75t_R add_8_11_g1202__7482(.A1 (add_8_11_n_933), .A2
       (add_8_11_n_911), .B (add_8_11_n_937), .Y (add_8_11_n_817));
  OAI21xp5_ASAP7_75t_R add_8_11_g1203__4733(.A1 (add_8_11_n_931), .A2
       (add_8_11_n_913), .B (add_8_11_n_906), .Y (add_8_11_n_820));
  OAI21xp5_ASAP7_75t_R add_8_11_g1204__6161(.A1 (add_8_11_n_988), .A2
       (add_8_11_n_983), .B (add_8_11_n_951), .Y (add_8_11_n_822));
  INVx1_ASAP7_75t_R add_8_11_g1205(.A (add_8_11_n_825), .Y
       (add_8_11_n_824));
  OAI21xp5_ASAP7_75t_R add_8_11_g1206__9315(.A1 (add_8_11_n_985), .A2
       (n_251), .B (add_8_11_n_969), .Y (add_8_11_n_825));
  OA21x2_ASAP7_75t_R add_8_11_g1207__9945(.A1 (add_8_11_n_1000), .A2
       (add_8_11_n_923), .B (n_255), .Y (add_8_11_n_827));
  OA21x2_ASAP7_75t_R add_8_11_g1208__2883(.A1 (add_8_11_n_993), .A2
       (add_8_11_n_991), .B (add_8_11_n_1010), .Y (add_8_11_n_829));
  OAI21xp5_ASAP7_75t_R add_8_11_g1209__2346(.A1 (add_8_11_n_996), .A2
       (n_257), .B (add_8_11_n_910), .Y (add_8_11_n_831));
  NOR3xp33_ASAP7_75t_R add_8_11_g1210__1666(.A (add_8_11_n_929), .B
       (add_8_11_n_922), .C (add_8_11_n_996), .Y (add_8_11_n_833));
  OR3x1_ASAP7_75t_R add_8_11_g1211__7410(.A (add_8_11_n_927), .B
       (add_8_11_n_920), .C (add_8_11_n_933), .Y (add_8_11_n_837));
  NOR4xp25_ASAP7_75t_R add_8_11_g1212__6417(.A (add_8_11_n_994), .B
       (add_8_11_n_931), .C (add_8_11_n_921), .D (add_8_11_n_987), .Y
       (add_8_11_n_839));
  OR2x2_ASAP7_75t_R add_8_11_g1213__5477(.A (add_8_11_n_914), .B
       (add_8_11_n_991), .Y (add_8_11_n_843));
  NOR2xp33_ASAP7_75t_R add_8_11_g1214__2398(.A (add_8_11_n_917), .B
       (add_8_11_n_983), .Y (add_8_11_n_846));
  OR2x2_ASAP7_75t_R add_8_11_g1215__5107(.A (add_8_11_n_998), .B
       (add_8_11_n_982), .Y (add_8_11_n_849));
  AOI21xp5_ASAP7_75t_R add_8_11_g1216__6260(.A1 (iA[19]), .A2 (iB[19]),
       .B (add_8_11_n_982), .Y (add_8_11_n_851));
  NAND2xp33_ASAP7_75t_R add_8_11_g1217__4319(.A (add_8_11_n_990), .B
       (add_8_11_n_930), .Y (add_8_11_n_852));
  AND2x2_ASAP7_75t_R add_8_11_g1218__8428(.A (add_8_11_n_997), .B
       (add_8_11_n_910), .Y (add_8_11_n_854));
  AOI21xp5_ASAP7_75t_R add_8_11_g1220__6783(.A1 (iA[15]), .A2 (iB[15]),
       .B (add_8_11_n_922), .Y (add_8_11_n_858));
  AND2x2_ASAP7_75t_R add_8_11_g1221__3680(.A (add_8_11_n_984), .B
       (add_8_11_n_969), .Y (add_8_11_n_859));
  NAND2xp33_ASAP7_75t_R add_8_11_g1222__1617(.A (add_8_11_n_918), .B
       (add_8_11_n_999), .Y (add_8_11_n_862));
  AOI21xp5_ASAP7_75t_R add_8_11_g1223__2802(.A1 (iA[11]), .A2 (iB[11]),
       .B (add_8_11_n_921), .Y (add_8_11_n_863));
  NAND2xp33_ASAP7_75t_R add_8_11_g1224__1705(.A (add_8_11_n_993), .B
       (add_8_11_n_915), .Y (add_8_11_n_864));
  NOR2xp33_ASAP7_75t_R add_8_11_g1227__7098(.A (add_8_11_n_981), .B
       (add_8_11_n_907), .Y (add_8_11_n_869));
  NOR2xp33_ASAP7_75t_R add_8_11_g1228__6131(.A (add_8_11_n_972), .B
       (add_8_11_n_970), .Y (add_8_11_n_871));
  AOI21xp5_ASAP7_75t_R add_8_11_g1231__7482(.A1 (iA[5]), .A2 (iB[5]),
       .B (add_8_11_n_991), .Y (add_8_11_n_875));
  NAND2xp33_ASAP7_75t_R add_8_11_g1233__6161(.A (add_8_11_n_904), .B
       (add_8_11_n_976), .Y (add_8_11_n_878));
  NOR2xp33_ASAP7_75t_R add_8_11_g1235__9945(.A (add_8_11_n_909), .B
       (add_8_11_n_978), .Y (add_8_11_n_882));
  AOI21xp5_ASAP7_75t_R add_8_11_g1236__2883(.A1 (n_18), .A2 (n_66), .B
       (add_8_11_n_905), .Y (add_8_11_n_884));
  AOI21xp5_ASAP7_75t_R add_8_11_g1238__1666(.A1 (iA[25]), .A2 (iB[25]),
       .B (add_8_11_n_983), .Y (add_8_11_n_888));
  NAND2xp33_ASAP7_75t_R add_8_11_g1239__7410(.A (add_8_11_n_919), .B
       (add_8_11_n_995), .Y (add_8_11_n_889));
  AOI21xp5_ASAP7_75t_R add_8_11_g1240__6417(.A1 (iA[23]), .A2 (iB[23]),
       .B (add_8_11_n_920), .Y (add_8_11_n_891));
  AND2x2_ASAP7_75t_R add_8_11_g1241__5477(.A (add_8_11_n_986), .B
       (add_8_11_n_913), .Y (add_8_11_n_892));
  NAND2xp33_ASAP7_75t_R add_8_11_g1242__2398(.A (add_8_11_n_916), .B
       (add_8_11_n_928), .Y (add_8_11_n_894));
  AND2x2_ASAP7_75t_R add_8_11_g1243__5107(.A (add_8_11_n_932), .B
       (add_8_11_n_906), .Y (add_8_11_n_895));
  AOI21xp5_ASAP7_75t_R add_8_11_g1244__6260(.A1 (iA[21]), .A2 (iB[21]),
       .B (add_8_11_n_933), .Y (add_8_11_n_898));
  AND2x2_ASAP7_75t_R add_8_11_g1245__4319(.A (add_8_11_n_968), .B
       (add_8_11_n_911), .Y (add_8_11_n_899));
  NOR2xp33_ASAP7_75t_R add_8_11_g1246__8428(.A (add_8_11_n_917), .B
       (add_8_11_n_989), .Y (add_8_11_n_901));
  XNOR2xp5_ASAP7_75t_R add_8_11_g1247__5526(.A (iA[31]), .B (iB[31]),
       .Y (add_8_11_n_902));
  INVx1_ASAP7_75t_R add_8_11_g1248(.A (add_8_11_n_904), .Y
       (add_8_11_n_903));
  INVx1_ASAP7_75t_R add_8_11_g1249(.A (add_8_11_n_909), .Y
       (add_8_11_n_908));
  INVxp67_ASAP7_75t_R add_8_11_g1250(.A (add_8_11_n_914), .Y
       (add_8_11_n_915));
  INVxp67_ASAP7_75t_R add_8_11_g1254(.A (add_8_11_n_927), .Y
       (add_8_11_n_928));
  INVx1_ASAP7_75t_R add_8_11_g1255(.A (add_8_11_n_929), .Y
       (add_8_11_n_930));
  INVxp67_ASAP7_75t_R add_8_11_g1256(.A (add_8_11_n_931), .Y
       (add_8_11_n_932));
  NOR2xp33_ASAP7_75t_R add_8_11_g1257__6783(.A (n_80), .B (n_69), .Y
       (add_8_11_n_934));
  NAND2xp5_ASAP7_75t_R add_8_11_g1258__3680(.A (iB[21]), .B (iA[21]),
       .Y (add_8_11_n_937));
  NOR2xp33_ASAP7_75t_R add_8_11_g1259__1617(.A (iB[12]), .B (iA[12]),
       .Y (add_8_11_n_940));
  NAND2xp5_ASAP7_75t_R add_8_11_g1260__2802(.A (iB[29]), .B (iA[29]),
       .Y (add_8_11_n_904));
  NOR2xp33_ASAP7_75t_R add_8_11_g1261__1705(.A (n_66), .B (n_18), .Y
       (add_8_11_n_905));
  NAND2xp5_ASAP7_75t_R add_8_11_g1262__5122(.A (iB[9]), .B (iA[9]), .Y
       (add_8_11_n_906));
  NOR2xp33_ASAP7_75t_R add_8_11_g1263__8246(.A (iB[7]), .B (iA[7]), .Y
       (add_8_11_n_945));
  NOR2xp33_ASAP7_75t_R add_8_11_g1264__7098(.A (iB[30]), .B (iA[30]),
       .Y (add_8_11_n_948));
  NAND2xp5_ASAP7_75t_R add_8_11_g1265__6131(.A (iB[25]), .B (iA[25]),
       .Y (add_8_11_n_951));
  NAND2xp5_ASAP7_75t_R add_8_11_g1266__1881(.A (iB[11]), .B (iA[11]),
       .Y (add_8_11_n_954));
  AND2x2_ASAP7_75t_R add_8_11_g1267__5115(.A (iB[6]), .B (iA[6]), .Y
       (add_8_11_n_907));
  NAND2xp5_ASAP7_75t_R add_8_11_g1268__7482(.A (n_66), .B (n_18), .Y
       (add_8_11_n_957));
  NOR2xp33_ASAP7_75t_R add_8_11_g1269__4733(.A (iB[27]), .B (iA[27]),
       .Y (add_8_11_n_909));
  NAND2xp5_ASAP7_75t_R add_8_11_g1270__6161(.A (iB[13]), .B (iA[13]),
       .Y (add_8_11_n_910));
  NAND2xp5_ASAP7_75t_R add_8_11_g1271__9315(.A (iB[20]), .B (iA[20]),
       .Y (add_8_11_n_911));
  NAND2xp5_ASAP7_75t_R add_8_11_g1273__2883(.A (iB[8]), .B (iA[8]), .Y
       (add_8_11_n_913));
  NOR2xp33_ASAP7_75t_R add_8_11_g1274__2346(.A (iB[4]), .B (iA[4]), .Y
       (add_8_11_n_914));
  NAND2xp5_ASAP7_75t_R add_8_11_g1275__1666(.A (iB[22]), .B (iA[22]),
       .Y (add_8_11_n_916));
  NOR2xp33_ASAP7_75t_R add_8_11_g1276__7410(.A (iB[24]), .B (iA[24]),
       .Y (add_8_11_n_917));
  NAND2xp5_ASAP7_75t_R add_8_11_g1277__6417(.A (iB[18]), .B (iA[18]),
       .Y (add_8_11_n_918));
  NAND2xp5_ASAP7_75t_R add_8_11_g1278__5477(.A (iB[10]), .B (iA[10]),
       .Y (add_8_11_n_919));
  NOR2xp33_ASAP7_75t_R add_8_11_g1279__2398(.A (iB[23]), .B (iA[23]),
       .Y (add_8_11_n_920));
  NOR2xp33_ASAP7_75t_R add_8_11_g1280__5107(.A (iB[11]), .B (iA[11]),
       .Y (add_8_11_n_921));
  NOR2xp33_ASAP7_75t_R add_8_11_g1281__6260(.A (iB[15]), .B (iA[15]),
       .Y (add_8_11_n_922));
  NAND2x1p5_ASAP7_75t_R add_8_11_g1282__4319(.A (n_82), .B (n_78), .Y
       (add_8_11_n_923));
  NOR2xp33_ASAP7_75t_R add_8_11_g1283__8428(.A (iB[22]), .B (iA[22]),
       .Y (add_8_11_n_927));
  NOR2xp33_ASAP7_75t_R add_8_11_g1284__5526(.A (iB[14]), .B (iA[14]),
       .Y (add_8_11_n_929));
  NOR2xp33_ASAP7_75t_R add_8_11_g1285__6783(.A (iB[9]), .B (iA[9]), .Y
       (add_8_11_n_931));
  NOR2xp33_ASAP7_75t_R add_8_11_g1286__3680(.A (iB[21]), .B (iA[21]),
       .Y (add_8_11_n_933));
  INVx1_ASAP7_75t_R add_8_11_g1287(.A (add_8_11_n_972), .Y
       (add_8_11_n_971));
  INVx1_ASAP7_75t_R add_8_11_g1288(.A (add_8_11_n_981), .Y
       (add_8_11_n_980));
  INVxp67_ASAP7_75t_R add_8_11_g1289(.A (add_8_11_n_985), .Y
       (add_8_11_n_984));
  INVxp67_ASAP7_75t_R add_8_11_g1290(.A (add_8_11_n_987), .Y
       (add_8_11_n_986));
  INVxp67_ASAP7_75t_R add_8_11_g1291(.A (add_8_11_n_988), .Y
       (add_8_11_n_989));
  INVx1_ASAP7_75t_R add_8_11_g1292(.A (add_8_11_n_994), .Y
       (add_8_11_n_995));
  INVxp67_ASAP7_75t_R add_8_11_g1293(.A (add_8_11_n_996), .Y
       (add_8_11_n_997));
  INVxp67_ASAP7_75t_R add_8_11_g1294(.A (add_8_11_n_998), .Y
       (add_8_11_n_999));
  NOR2xp33_ASAP7_75t_R add_8_11_g1295__1617(.A (n_83), .B (n_86), .Y
       (add_8_11_n_1000));
  OR2x2_ASAP7_75t_R add_8_11_g1296__2802(.A (iA[20]), .B (iB[20]), .Y
       (add_8_11_n_968));
  NAND2xp5_ASAP7_75t_R add_8_11_g1297__1705(.A (iB[17]), .B (iA[17]),
       .Y (add_8_11_n_969));
  AND2x2_ASAP7_75t_R add_8_11_g1298__5122(.A (iB[3]), .B (iA[3]), .Y
       (add_8_11_n_970));
  NOR2xp33_ASAP7_75t_R add_8_11_g1299__8246(.A (iB[3]), .B (iA[3]), .Y
       (add_8_11_n_972));
  NOR2xp33_ASAP7_75t_R add_8_11_g1300__7098(.A (n_33), .B (n_21), .Y
       (add_8_11_n_1007));
  NAND2xp5_ASAP7_75t_R add_8_11_g1301__6131(.A (iB[5]), .B (iA[5]), .Y
       (add_8_11_n_1010));
  OR2x2_ASAP7_75t_R add_8_11_g1305__4733(.A (iA[29]), .B (iB[29]), .Y
       (add_8_11_n_976));
  NOR2xp33_ASAP7_75t_R add_8_11_g1306__6161(.A (iB[16]), .B (iA[16]),
       .Y (add_8_11_n_1015));
  NAND2xp5_ASAP7_75t_R add_8_11_g1307__9315(.A (iB[23]), .B (iA[23]),
       .Y (add_8_11_n_1018));
  NAND2xp5_ASAP7_75t_R add_8_11_g1308__9945(.A (iB[15]), .B (iA[15]),
       .Y (add_8_11_n_1019));
  AND2x2_ASAP7_75t_R add_8_11_g1310__2346(.A (iB[27]), .B (iA[27]), .Y
       (add_8_11_n_978));
  NAND2xp5_ASAP7_75t_R add_8_11_g1311__1666(.A (iB[19]), .B (iA[19]),
       .Y (add_8_11_n_1022));
  NOR2xp33_ASAP7_75t_R add_8_11_g1313__6417(.A (iB[6]), .B (iA[6]), .Y
       (add_8_11_n_981));
  NOR2xp33_ASAP7_75t_R add_8_11_g1314__5477(.A (iB[19]), .B (iA[19]),
       .Y (add_8_11_n_982));
  NOR2xp33_ASAP7_75t_R add_8_11_g1315__2398(.A (iB[25]), .B (iA[25]),
       .Y (add_8_11_n_983));
  NOR2xp33_ASAP7_75t_R add_8_11_g1316__5107(.A (iB[17]), .B (iA[17]),
       .Y (add_8_11_n_985));
  NOR2xp33_ASAP7_75t_R add_8_11_g1317__6260(.A (iB[8]), .B (iA[8]), .Y
       (add_8_11_n_987));
  NAND2xp5_ASAP7_75t_R add_8_11_g1318__4319(.A (iB[24]), .B (iA[24]),
       .Y (add_8_11_n_988));
  NAND2xp5_ASAP7_75t_R add_8_11_g1319__8428(.A (iB[14]), .B (iA[14]),
       .Y (add_8_11_n_990));
  NOR2xp33_ASAP7_75t_R add_8_11_g1320__5526(.A (iB[5]), .B (iA[5]), .Y
       (add_8_11_n_991));
  NAND2xp5_ASAP7_75t_R add_8_11_g1322__3680(.A (iB[4]), .B (iA[4]), .Y
       (add_8_11_n_993));
  NOR2xp33_ASAP7_75t_R add_8_11_g1323__1617(.A (iB[10]), .B (iA[10]),
       .Y (add_8_11_n_994));
  NOR2xp33_ASAP7_75t_R add_8_11_g1324__2802(.A (iB[13]), .B (iA[13]),
       .Y (add_8_11_n_996));
  NOR2xp33_ASAP7_75t_R add_8_11_g1325__1705(.A (iB[18]), .B (iA[18]),
       .Y (add_8_11_n_998));
  XNOR2xp5_ASAP7_75t_R g2(.A (add_8_11_n_889), .B (add_8_11_n_767), .Y
       (n_219));
  XNOR2xp5_ASAP7_75t_R g1366(.A (n_250), .B (add_8_11_n_754), .Y
       (n_220));
  OAI21xp5_ASAP7_75t_R g1367(.A1 (n_78), .A2 (n_82), .B
       (add_8_11_n_923), .Y (n_221));
  XNOR2x2_ASAP7_75t_R g1368(.A (n_260), .B (add_8_11_n_703), .Y
       (n_222));
  XOR2xp5_ASAP7_75t_R g1369(.A (add_8_11_n_901), .B (add_8_11_n_722),
       .Y (n_223));
  XNOR2xp5_ASAP7_75t_R g1370(.A (add_8_11_n_858), .B (add_8_11_n_743),
       .Y (n_224));
  XNOR2xp5_ASAP7_75t_R g1371(.A (add_8_11_n_891), .B (add_8_11_n_712),
       .Y (n_225));
  XNOR2xp5_ASAP7_75t_R g1372(.A (add_8_11_n_854), .B (add_8_11_n_759),
       .Y (n_226));
  XNOR2xp5_ASAP7_75t_R g1373(.A (add_8_11_n_852), .B (add_8_11_n_752),
       .Y (n_227));
  XNOR2xp5_ASAP7_75t_R g1374(.A (add_8_11_n_894), .B (add_8_11_n_720),
       .Y (n_228));
  XNOR2xp5_ASAP7_75t_R g1375(.A (n_256), .B (add_8_11_n_769), .Y
       (n_229));
  XNOR2xp5_ASAP7_75t_R g1376(.A (add_8_11_n_882), .B (add_8_11_n_707),
       .Y (n_230));
  XNOR2xp5_ASAP7_75t_R g1377(.A (add_8_11_n_863), .B (add_8_11_n_753),
       .Y (n_231));
  XNOR2xp5_ASAP7_75t_R g1378(.A (add_8_11_n_898), .B (add_8_11_n_727),
       .Y (n_232));
  XNOR2xp5_ASAP7_75t_R g1379(.A (n_258), .B (add_8_11_n_696), .Y
       (n_233));
  XNOR2xp5_ASAP7_75t_R g1380(.A (add_8_11_n_923), .B (n_254), .Y
       (n_234));
  XOR2xp5_ASAP7_75t_R g1381(.A (add_8_11_n_878), .B (add_8_11_n_699),
       .Y (n_235));
  XNOR2xp5_ASAP7_75t_R g1382(.A (add_8_11_n_884), .B (add_8_11_n_714),
       .Y (n_236));
  XNOR2xp5_ASAP7_75t_R g1383(.A (add_8_11_n_899), .B (add_8_11_n_736),
       .Y (n_237));
  XNOR2xp5_ASAP7_75t_R g1384(.A (add_8_11_n_892), .B (add_8_11_n_775),
       .Y (n_238));
  XNOR2xp5_ASAP7_75t_R g1385(.A (n_262), .B (add_8_11_n_781), .Y
       (n_239));
  XNOR2xp5_ASAP7_75t_R g1386(.A (add_8_11_n_851), .B (add_8_11_n_733),
       .Y (n_240));
  XNOR2xp5_ASAP7_75t_R g1387(.A (add_8_11_n_869), .B (add_8_11_n_786),
       .Y (n_241));
  XNOR2xp5_ASAP7_75t_R g1388(.A (add_8_11_n_875), .B (add_8_11_n_785),
       .Y (n_242));
  XNOR2xp5_ASAP7_75t_R g1389(.A (add_8_11_n_888), .B (add_8_11_n_711),
       .Y (n_243));
  XNOR2xp5_ASAP7_75t_R g1390(.A (add_8_11_n_862), .B (add_8_11_n_739),
       .Y (n_244));
  XNOR2xp5_ASAP7_75t_R g1391(.A (add_8_11_n_864), .B (add_8_11_n_796),
       .Y (n_245));
  XNOR2xp5_ASAP7_75t_R g1392(.A (add_8_11_n_871), .B (add_8_11_n_805),
       .Y (n_246));
  XNOR2xp5_ASAP7_75t_R g1393(.A (add_8_11_n_859), .B (add_8_11_n_740),
       .Y (n_247));
  XNOR2xp5_ASAP7_75t_R g1394(.A (n_252), .B (add_8_11_n_827), .Y
       (n_248));
  XNOR2xp5_ASAP7_75t_R g1395(.A (add_8_11_n_895), .B (add_8_11_n_768),
       .Y (n_249));
  HAxp5_ASAP7_75t_R g1396(.A (iA[16]), .B (iB[16]), .CON (n_251), .SN
       (n_250));
  HAxp5_ASAP7_75t_R g1397(.A (n_69), .B (n_80), .CON (n_253), .SN
       (n_252));
  HAxp5_ASAP7_75t_R g1398(.A (n_86), .B (n_83), .CON (n_255), .SN
       (n_254));
  HAxp5_ASAP7_75t_R g1399(.A (iA[12]), .B (iB[12]), .CON (n_257), .SN
       (n_256));
  HAxp5_ASAP7_75t_R g1400(.A (iA[30]), .B (iB[30]), .CON (n_259), .SN
       (n_258));
  HAxp5_ASAP7_75t_R g1401(.A (n_21), .B (n_33), .CON (n_261), .SN
       (n_260));
  HAxp5_ASAP7_75t_R g1402(.A (iA[7]), .B (iB[7]), .CON (n_263), .SN
       (n_262));
endmodule

