
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Apr  8 2026 18:34:15 +07 (Apr  8 2026 11:34:15 UTC)

// Verification Directory fv/Adder32 

module Adder32(iClk, iA, iB, oS);
  input iClk;
  input [31:0] iA, iB;
  output [31:0] oS;
  wire iClk;
  wire [31:0] iA, iB;
  wire [31:0] oS;
  wire add_8_11_n_2654, add_8_11_n_2656, add_8_11_n_2660,
       add_8_11_n_2662, add_8_11_n_2664, add_8_11_n_2674,
       add_8_11_n_2675, add_8_11_n_2676;
  wire add_8_11_n_2689, add_8_11_n_2714, add_8_11_n_2718,
       add_8_11_n_2732, add_8_11_n_2742, add_8_11_n_2745,
       add_8_11_n_2748, add_8_11_n_2750;
  wire add_8_11_n_2754, add_8_11_n_2756, add_8_11_n_2778,
       add_8_11_n_2779, add_8_11_n_2784, add_8_11_n_2790,
       add_8_11_n_2792, add_8_11_n_2794;
  wire add_8_11_n_2800, add_8_11_n_2812, add_8_11_n_2815,
       add_8_11_n_2821, add_8_11_n_2888, add_8_11_n_2896,
       add_8_11_n_2899, add_8_11_n_2902;
  wire add_8_11_n_2916, add_8_11_n_2929, add_8_11_n_2930,
       add_8_11_n_2931, add_8_11_n_2934, add_8_11_n_2935,
       add_8_11_n_2936, add_8_11_n_2941;
  wire add_8_11_n_2942, add_8_11_n_2943, add_8_11_n_2951,
       add_8_11_n_2966, add_8_11_n_2976, add_8_11_n_2997,
       add_8_11_n_3016, add_8_11_n_3024;
  wire add_8_11_n_3037, add_8_11_n_3041, add_8_11_n_3044,
       add_8_11_n_3045, add_8_11_n_3049, add_8_11_n_3053,
       add_8_11_n_3057, n_148;
  wire n_154, n_157, n_181, n_184, n_191, n_206, n_223, n_227;
  wire n_235, n_236, n_241, n_244, n_248, n_249, n_254, n_255;
  wire n_256, n_260, n_273, n_281, n_285, n_287, n_288, n_289;
  wire n_292, n_316, n_332, n_348, n_410, n_423, n_430, n_432;
  wire n_454, n_455, n_456, n_462, n_463, n_464, n_466, n_467;
  wire n_472, n_494, n_500, n_502, n_507, n_508, n_511, n_646;
  wire n_660, n_661, n_662, n_663, n_668, n_685, n_686, n_687;
  wire n_696, n_698, n_700, n_703, n_714, n_715, n_716, n_719;
  wire n_722, n_803, n_1095, n_1116, n_1592, n_1594, n_1759, n_1761;
  wire n_2240, n_2243, n_2253, n_2264, n_2279, n_2377, n_2378, n_2379;
  wire n_2380, n_2382, n_2384, n_2386, n_2387, n_2389, n_2390, n_2419;
  wire n_2420, n_2421, n_2432, n_2436, n_2437, n_2439, n_2464, n_2475;
  wire n_2476, n_2478, n_2479, n_2480, n_2481, n_2482, n_2483, n_2485;
  wire n_2486, n_2490, n_2503, n_2506, n_2507, n_2508, n_2514, n_2515;
  wire n_2516, n_2520, n_2522, n_2531, n_2533, n_2536, n_2538, n_2539;
  wire n_2541, n_2543, n_2546, n_2547, n_2551, n_2553, n_2555, n_2557;
  wire n_2558, n_2559, n_2565, n_2566, n_2567, n_2568, n_2571, n_2572;
  wire n_2573, n_2575, n_2577, n_2578, n_2579, n_2581, n_2582, n_2583;
  wire n_2584, n_2585, n_2586, n_2587, n_2590, n_2591, n_2593, n_2625;
  wire n_2626, n_2634, n_2642, n_2643, n_2644, n_2645, n_2648, n_2651;
  wire n_2665, n_2666, n_2667, n_2668, n_2700, n_2709, n_2710, n_2711;
  wire n_2712, n_2713, n_2714, n_2715, n_2718, n_2720, n_2721, n_2723;
  wire n_2726, n_2727, n_2736, n_2737, n_2738, n_2741, n_2747, n_2755;
  wire n_2756, n_2757, n_2758, n_2763, n_2768, n_2769, n_2770, n_2771;
  wire n_2772, n_2774, n_2775, n_2776, n_2786, n_2787, n_2789, n_2790;
  wire n_2791, n_2792, n_2793, n_2794, n_2795, n_2796, n_2798, n_2801;
  wire n_2805, n_2806, n_2808, n_2809, n_2811, n_2845, n_2848, n_2849;
  wire n_2850, n_2851, n_2852, n_2854, n_2855, n_2894, n_2895, n_2896;
  wire n_2998, n_3026, n_3070, n_3136, n_3258, n_3363, n_3385, n_3464;
  wire n_3485, n_4400, n_4401, n_4428, n_4429, n_4437, n_4438, n_4481;
  wire n_4482, n_4483, n_4491, n_4492, n_4493, n_4498, n_4499, n_4500;
  wire n_4501, n_4502, n_4503, n_4504, n_4547, n_4552, n_4553, n_4554;
  wire n_4555, n_4557, n_4558, n_4561, n_4564, n_4565, n_4610, n_4611;
  wire n_4671, n_4673, n_4716, n_4718, n_4825, n_5885, n_5932, n_5933;
  wire n_5934, n_5935, n_5936, n_5937, n_5938, n_5939, n_7184, n_7185;
  wire n_7186, n_7187, n_7188, n_7189, n_7191, n_7193, n_7196, n_7197;
  wire n_7198, n_7199, n_7202, n_7207, n_7208, n_7223, n_7225, n_7268;
  wire n_7279, n_7280, n_7281, n_7282, n_7283, n_7291, n_7292, n_7293;
  wire n_7294, n_7310, n_7311, n_7312, n_7313, n_7314, n_7315, n_7316;
  wire n_7317, n_7318, n_7319, n_7320, n_7321, n_7322, n_7323, n_7725;
  wire n_7990;
  DFFHQNx1_ASAP7_75t_SL \oS_reg[31] (.CLK (iClk), .D (n_2483), .QN
       (oS[31]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[30] (.CLK (iClk), .D (n_2796), .QN
       (oS[30]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[28] (.CLK (iClk), .D (n_248), .QN
       (oS[28]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[24] (.CLK (iClk), .D (n_249), .QN
       (oS[24]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[16] (.CLK (iClk), .D (n_4555), .QN
       (oS[16]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[0] (.CLK (iClk), .D (n_2382), .QN
       (oS[0]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[15] (.CLK (iClk), .D (n_2490), .QN
       (oS[15]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[23] (.CLK (iClk), .D (n_235), .QN
       (oS[23]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[14] (.CLK (iClk), .D (n_2421), .QN
       (oS[14]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[13] (.CLK (iClk), .D (n_273), .QN
       (oS[13]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[27] (.CLK (iClk), .D (n_236), .QN
       (oS[27]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[22] (.CLK (iClk), .D (n_2379), .QN
       (oS[22]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[12] (.CLK (iClk), .D (n_2387), .QN
       (oS[12]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[11] (.CLK (iClk), .D (n_2390), .QN
       (oS[11]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[21] (.CLK (iClk), .D (n_254), .QN
       (oS[21]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[10] (.CLK (iClk), .D (n_2377), .QN
       (oS[10]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[9] (.CLK (iClk), .D (n_2384), .QN
       (oS[9]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[29] (.CLK (iClk), .D (n_2486), .QN
       (oS[29]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[26] (.CLK (iClk), .D (n_244), .QN
       (oS[26]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[20] (.CLK (iClk), .D (n_255), .QN
       (oS[20]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[8] (.CLK (iClk), .D (n_2475), .QN
       (oS[8]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[7] (.CLK (iClk), .D (n_2386), .QN
       (oS[7]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[19] (.CLK (iClk), .D (n_256), .QN
       (oS[19]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[6] (.CLK (iClk), .D (n_2380), .QN
       (oS[6]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[5] (.CLK (iClk), .D (n_2389), .QN
       (oS[5]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[25] (.CLK (iClk), .D (n_260), .QN
       (oS[25]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[18] (.CLK (iClk), .D (n_241), .QN
       (oS[18]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[4] (.CLK (iClk), .D (n_4429), .QN
       (oS[4]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[3] (.CLK (iClk), .D (n_2378), .QN
       (oS[3]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[17] (.CLK (iClk), .D (n_7225), .QN
       (oS[17]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[2] (.CLK (iClk), .D (n_2480), .QN
       (oS[2]));
  DFFHQNx1_ASAP7_75t_SL \oS_reg[1] (.CLK (iClk), .D (n_2522), .QN
       (oS[1]));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3101__5115(.A1 (add_8_11_n_2778), .A2
       (n_7197), .B (n_7314), .Y (add_8_11_n_2654));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3102__7482(.A1 (add_8_11_n_2750), .A2
       (n_7197), .B (n_7321), .Y (add_8_11_n_2656));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3106__9945(.A1 (add_8_11_n_2790), .A2
       (n_7197), .B (add_8_11_n_2732), .Y (add_8_11_n_2660));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3108__2346(.A1 (add_8_11_n_2756), .A2
       (n_7197), .B (n_7319), .Y (add_8_11_n_2662));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3110__7410(.A1 (add_8_11_n_2779), .A2
       (n_7197), .B (add_8_11_n_2718), .Y (add_8_11_n_2664));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3119__6783(.A1 (add_8_11_n_2821), .A2
       (n_7197), .B (add_8_11_n_2754), .Y (add_8_11_n_2674));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3120__3680(.A1 (add_8_11_n_2748), .A2
       (n_7197), .B (n_7316), .Y (add_8_11_n_2675));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3121__1617(.A1 (add_8_11_n_2745), .A2
       (n_7197), .B (n_7315), .Y (add_8_11_n_2676));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3131__4733(.A1 (n_7207), .A2
       (add_8_11_n_2794), .B (n_507), .Y (add_8_11_n_2689));
  AOI21xp5_ASAP7_75t_SL add_8_11_g3149__4319(.A1 (n_2808), .A2 (n_285),
       .B (n_2536), .Y (add_8_11_n_2714));
  OA21x2_ASAP7_75t_SL add_8_11_g3152__6783(.A1 (n_2571), .A2 (n_148),
       .B (n_2665), .Y (add_8_11_n_2718));
  AOI221xp5_ASAP7_75t_SL add_8_11_g3161__6131(.A1 (n_2508), .A2
       (add_8_11_n_2800), .B1 (n_2668), .B2 (add_8_11_n_3053), .C
       (add_8_11_n_3045), .Y (add_8_11_n_2732));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3167__9315(.A (n_2776), .B (n_2583),
       .Y (add_8_11_n_2742));
  OR2x2_ASAP7_75t_SL add_8_11_g3168__9945(.A (add_8_11_n_3057), .B
       (add_8_11_n_2778), .Y (add_8_11_n_2745));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3169__2883(.A (n_2774), .B (n_2583),
       .Y (add_8_11_n_2748));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3170__2346(.A (n_2555), .B (n_2583),
       .Y (add_8_11_n_2750));
  OA21x2_ASAP7_75t_SL add_8_11_g3172__7410(.A1 (n_454), .A2 (n_696), .B
       (n_2572), .Y (add_8_11_n_2754));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3173__6417(.A (n_157), .B (n_2583),
       .Y (add_8_11_n_2756));
  INVx1_ASAP7_75t_SL add_8_11_g3189(.A (n_2583), .Y (add_8_11_n_2778));
  OR2x2_ASAP7_75t_SL add_8_11_g3190__2802(.A (n_2571), .B (n_7196), .Y
       (add_8_11_n_2779));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3192__5122(.A (n_4502), .B (n_181),
       .Y (add_8_11_n_2784));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3195__6131(.A (add_8_11_n_2800), .B
       (n_154), .Y (add_8_11_n_2790));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3196__1881(.A (n_2539), .B (n_7196),
       .Y (add_8_11_n_2792));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3198__7482(.A (n_2553), .B (n_4502),
       .Y (add_8_11_n_2794));
  OR2x2_ASAP7_75t_SL add_8_11_g3204__9315(.A (n_511), .B (n_2264), .Y
       (add_8_11_n_2812));
  AND2x2_ASAP7_75t_SRAM add_8_11_g3205__9945(.A (n_2643), .B
       (add_8_11_n_2916), .Y (add_8_11_n_2815));
  OR2x2_ASAP7_75t_SL add_8_11_g3207__2346(.A (n_454), .B (n_2240), .Y
       (add_8_11_n_2821));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3209__7410(.A (n_410), .B (n_2539),
       .Y (add_8_11_n_2800));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3244__7410(.A (add_8_11_n_3044), .B
       (add_8_11_n_3053), .Y (add_8_11_n_2888));
  AOI21xp5_ASAP7_75t_SL add_8_11_g3249__6260(.A1 (iA[23]), .A2
       (iB[23]), .B (n_292), .Y (add_8_11_n_2896));
  AOI21xp5_ASAP7_75t_SL add_8_11_g3252__5526(.A1 (iA[25]), .A2
       (iB[25]), .B (n_430), .Y (add_8_11_n_2899));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3254__3680(.A (n_191), .B (n_2543),
       .Y (add_8_11_n_2902));
  NOR2xp33_ASAP7_75t_R add_8_11_g3272__9945(.A (n_511), .B (n_4558), .Y
       (add_8_11_n_2929));
  NOR2xp33_ASAP7_75t_L add_8_11_g3273__2883(.A (n_2531), .B (n_2538),
       .Y (add_8_11_n_2930));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3274__2346(.A (add_8_11_n_3057), .B
       (add_8_11_n_3041), .Y (add_8_11_n_2931));
  AOI21xp33_ASAP7_75t_SL add_8_11_g3276__7410(.A1 (iA[17]), .A2
       (iB[17]), .B (n_2642), .Y (add_8_11_n_2916));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3277__6417(.A (n_454), .B
       (add_8_11_n_3049), .Y (add_8_11_n_2934));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3278__5477(.A (n_2571), .B
       (add_8_11_n_3037), .Y (add_8_11_n_2935));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3279__2398(.A (n_2852), .B (n_184),
       .Y (add_8_11_n_2936));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3282__4319(.A (n_2573), .B
       (add_8_11_n_2951), .Y (add_8_11_n_2941));
  NOR2xp67_ASAP7_75t_L add_8_11_g3283__8428(.A (n_423), .B
       (add_8_11_n_2976), .Y (add_8_11_n_2942));
  NOR2xp67_ASAP7_75t_L add_8_11_g3285__6783(.A (n_462), .B
       (add_8_11_n_3024), .Y (add_8_11_n_2943));
  INVxp33_ASAP7_75t_SL add_8_11_g3291(.A (n_4557), .Y
       (add_8_11_n_2951));
  INVxp67_ASAP7_75t_SL add_8_11_g3297(.A (n_227), .Y (add_8_11_n_2966));
  INVxp33_ASAP7_75t_SL add_8_11_g3300(.A (n_467), .Y (add_8_11_n_2976));
  NAND2xp5_ASAP7_75t_SL add_8_11_g3311__7482(.A (iA[23]), .B (iB[23]),
       .Y (add_8_11_n_2997));
  INVxp33_ASAP7_75t_SL add_8_11_g3335(.A (n_2848), .Y
       (add_8_11_n_3016));
  INVxp33_ASAP7_75t_SL add_8_11_g3339(.A (n_463), .Y (add_8_11_n_3024));
  INVxp33_ASAP7_75t_SL add_8_11_g3342(.A (n_2665), .Y
       (add_8_11_n_3037));
  INVxp67_ASAP7_75t_SL add_8_11_g3345(.A (add_8_11_n_3044), .Y
       (add_8_11_n_3045));
  INVxp33_ASAP7_75t_SL add_8_11_g3346(.A (n_2572), .Y
       (add_8_11_n_3049));
  INVxp67_ASAP7_75t_SL add_8_11_g3347(.A (n_410), .Y (add_8_11_n_3053));
  NAND2x1p5_ASAP7_75t_SL add_8_11_g3369__8428(.A (iA[22]), .B (iB[22]),
       .Y (add_8_11_n_3044));
  NOR2x1p5_ASAP7_75t_L add_8_11_g3378__7098(.A (iB[24]), .B (iA[24]),
       .Y (add_8_11_n_3057));
  INVxp67_ASAP7_75t_SL fopt3395(.A (n_7196), .Y (n_154));
  HB1xp67_ASAP7_75t_SL fopt3414(.A (n_2651), .Y (n_181));
  INVxp33_ASAP7_75t_SL fopt3416(.A (n_646), .Y (n_184));
  INVxp33_ASAP7_75t_SL fopt3429(.A (n_2546), .Y (n_206));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3270__3438(.A (n_316), .B
       (add_8_11_n_3016), .Y (n_223));
  NOR2x1_ASAP7_75t_SL add_8_11_g3318__3443(.A (n_3464), .B (n_4825), .Y
       (n_227));
  XNOR2xp5_ASAP7_75t_SL g3450(.A (add_8_11_n_2896), .B
       (add_8_11_n_2660), .Y (n_235));
  XNOR2xp5_ASAP7_75t_SL g3451(.A (add_8_11_n_2943), .B
       (add_8_11_n_2656), .Y (n_236));
  XNOR2xp5_ASAP7_75t_SL g3455(.A (add_8_11_n_2934), .B (n_2243), .Y
       (n_241));
  XNOR2xp5_ASAP7_75t_SL g3458(.A (add_8_11_n_2902), .B
       (add_8_11_n_2662), .Y (n_244));
  XNOR2xp5_ASAP7_75t_SL g3462(.A (add_8_11_n_2942), .B
       (add_8_11_n_2675), .Y (n_248));
  XNOR2xp5_ASAP7_75t_SL g3463(.A (add_8_11_n_2931), .B
       (add_8_11_n_2654), .Y (n_249));
  XNOR2xp5_ASAP7_75t_SL g3468(.A (n_4565), .B (add_8_11_n_2664), .Y
       (n_254));
  XNOR2xp5_ASAP7_75t_SL g3469(.A (add_8_11_n_2935), .B (n_7199), .Y
       (n_255));
  XNOR2xp5_ASAP7_75t_SL g3470(.A (add_8_11_n_2941), .B
       (add_8_11_n_2674), .Y (n_256));
  XNOR2xp5_ASAP7_75t_SL g3474(.A (add_8_11_n_2899), .B
       (add_8_11_n_2676), .Y (n_260));
  XNOR2xp5_ASAP7_75t_SL g3486(.A (add_8_11_n_2930), .B (n_288), .Y
       (n_273));
  INVxp67_ASAP7_75t_SL add_8_11_g3496(.A (n_287), .Y (n_285));
  OAI31xp33_ASAP7_75t_SL add_8_11_g3128__3499(.A1 (n_7207), .A2
       (n_4503), .A3 (n_287), .B (add_8_11_n_2714), .Y (n_288));
  NOR2xp33_ASAP7_75t_SL add_8_11_g3275__3501(.A (n_287), .B (n_2536),
       .Y (n_289));
  NOR2x1_ASAP7_75t_SL add_8_11_g3373__3531(.A (iB[15]), .B (iA[15]), .Y
       (n_316));
  OAI21xp5_ASAP7_75t_SL add_8_11_g3184__3543(.A1 (n_2439), .A2
       (n_2533), .B (n_348), .Y (n_332));
  NAND2x1p5_ASAP7_75t_SL add_8_11_g3326__8428_dup(.A (iA[2]), .B
       (iB[2]), .Y (n_348));
  AOI21xp33_ASAP7_75t_SL g3563(.A1 (n_2645), .A2 (n_2585), .B (n_2575),
       .Y (n_148));
  NOR2x1_ASAP7_75t_SL g90(.A (iA[23]), .B (iB[23]), .Y (n_292));
  NOR2x1_ASAP7_75t_SL g91(.A (iA[22]), .B (iB[22]), .Y (n_410));
  NOR2x1p5_ASAP7_75t_SL g266(.A (iA[28]), .B (iB[28]), .Y (n_423));
  INVxp67_ASAP7_75t_SL g263(.A (n_2551), .Y (n_432));
  NOR2x1_ASAP7_75t_SL g124(.A (iA[18]), .B (iB[18]), .Y (n_454));
  NOR2x1_ASAP7_75t_SL g926(.A (iA[30]), .B (iB[30]), .Y (n_455));
  NOR2x1_ASAP7_75t_SL g918(.A (iB[29]), .B (iA[29]), .Y (n_456));
  OAI21xp5_ASAP7_75t_SL g913(.A1 (n_722), .A2 (n_462), .B (n_463), .Y
       (n_464));
  NOR2x1_ASAP7_75t_SL g927(.A (iA[27]), .B (iB[27]), .Y (n_462));
  NAND2xp5_ASAP7_75t_SL g920(.A (iA[27]), .B (iB[27]), .Y (n_463));
  INVx1_ASAP7_75t_SL g924(.A (n_455), .Y (n_466));
  NAND2xp5_ASAP7_75t_SL g922(.A (iB[28]), .B (iA[28]), .Y (n_467));
  NAND2xp5_ASAP7_75t_SL g921(.A (n_1759), .B (n_1592), .Y (n_472));
  AOI21xp33_ASAP7_75t_SL g981(.A1 (n_2808), .A2 (n_2553), .B (n_2792),
       .Y (n_507));
  NOR2xp33_ASAP7_75t_SL g1008(.A (n_2855), .B (n_803), .Y (n_494));
  NAND2x1_ASAP7_75t_SL g1005(.A (iA[12]), .B (iB[12]), .Y (n_500));
  NAND2x1p5_ASAP7_75t_SL g996(.A (iB[13]), .B (iA[13]), .Y (n_502));
  NAND2xp5_ASAP7_75t_SL g1003(.A (iB[14]), .B (iA[14]), .Y (n_508));
  NAND2xp5_ASAP7_75t_SL g998(.A (n_3464), .B (n_4825), .Y (n_281));
  NOR2x1_ASAP7_75t_SL g994(.A (n_3136), .B (n_3070), .Y (n_511));
  NAND2xp5_ASAP7_75t_SL g368(.A (iA[6]), .B (iB[6]), .Y (n_646));
  INVx2_ASAP7_75t_SL g3592(.A (iA[12]), .Y (n_660));
  INVx2_ASAP7_75t_SL g3593(.A (iB[12]), .Y (n_661));
  INVx2_ASAP7_75t_SL g3594(.A (iA[13]), .Y (n_662));
  INVx4_ASAP7_75t_SL g3595(.A (iB[13]), .Y (n_663));
  NOR2x1_ASAP7_75t_SL g84(.A (n_3258), .B (iB[12]), .Y (n_287));
  NOR2x1_ASAP7_75t_SL g30(.A (iB[4]), .B (iA[4]), .Y (n_668));
  NAND2x1p5_ASAP7_75t_SL g79(.A (iB[1]), .B (iA[1]), .Y (n_685));
  NAND2x1_ASAP7_75t_SL g3596(.A (iB[0]), .B (iA[0]), .Y (n_686));
  NOR2x1p5_ASAP7_75t_SL g78(.A (iA[1]), .B (iB[1]), .Y (n_687));
  INVx2_ASAP7_75t_SL g2870(.A (n_2645), .Y (n_696));
  INVx1_ASAP7_75t_SL g2882(.A (n_2585), .Y (n_698));
  INVx1_ASAP7_75t_SL g2867(.A (n_2575), .Y (n_700));
  OAI21xp5_ASAP7_75t_L g2866(.A1 (n_292), .A2 (add_8_11_n_3044), .B
       (add_8_11_n_2997), .Y (n_703));
  INVx1_ASAP7_75t_SL g2885(.A (n_2547), .Y (n_191));
  AO21x1_ASAP7_75t_SL g2857(.A1 (n_2547), .A2 (n_716), .B (n_2543), .Y
       (n_719));
  OAI21xp5_ASAP7_75t_SL g2863(.A1 (n_430), .A2 (n_714), .B (n_715), .Y
       (n_716));
  NAND2xp5_ASAP7_75t_SL g2881(.A (iA[24]), .B (iB[24]), .Y (n_714));
  NAND2xp5_ASAP7_75t_SL g2875(.A (iB[25]), .B (iA[25]), .Y (n_715));
  NAND2xp5_ASAP7_75t_SL g2880(.A (iB[26]), .B (iA[26]), .Y (n_722));
  NOR2x1p5_ASAP7_75t_SL g2864(.A (n_430), .B (add_8_11_n_3057), .Y
       (n_157));
  HB1xp67_ASAP7_75t_SL fopt3654(.A (iB[14]), .Y (n_803));
  HB1xp67_ASAP7_75t_SL fopt3904(.A (iB[26]), .Y (n_1095));
  HB1xp67_ASAP7_75t_SL fopt3922(.A (iA[26]), .Y (n_1116));
  INVxp67_ASAP7_75t_SL drc_buf_sp4339(.A (n_1594), .Y (n_1592));
  INVxp67_ASAP7_75t_SL drc_buf_sp4341(.A (iB[30]), .Y (n_1594));
  INVxp67_ASAP7_75t_SL drc_buf_sp4488(.A (n_1761), .Y (n_1759));
  INVxp67_ASAP7_75t_SL drc_buf_sp4490(.A (iA[30]), .Y (n_1761));
  OAI21xp5_ASAP7_75t_SL g19(.A1 (n_2240), .A2 (n_7197), .B (n_696), .Y
       (n_2243));
  INVx1_ASAP7_75t_SL g22(.A (n_2584), .Y (n_2240));
  NOR2x1_ASAP7_75t_SL g25(.A (iB[4]), .B (n_3485), .Y (n_2253));
  INVxp67_ASAP7_75t_SL g21(.A (n_4498), .Y (n_2264));
  OAI21xp5_ASAP7_75t_SL g4924(.A1 (n_4503), .A2 (n_7207), .B (n_2809),
       .Y (n_2279));
  XNOR2xp5_ASAP7_75t_SL g2(.A (add_8_11_n_2929), .B (n_7193), .Y
       (n_2377));
  XNOR2xp5_ASAP7_75t_SL g5007(.A (n_4564), .B (n_332), .Y (n_2378));
  XNOR2xp5_ASAP7_75t_SL g5008(.A (add_8_11_n_2888), .B (n_2806), .Y
       (n_2379));
  XNOR2xp5_ASAP7_75t_SL g5009(.A (add_8_11_n_2936), .B (n_4483), .Y
       (n_2380));
  XNOR2xp5_ASAP7_75t_SL g5011(.A (iB[0]), .B (iA[0]), .Y (n_2382));
  XNOR2xp5_ASAP7_75t_SL g5013(.A (n_4561), .B (n_7208), .Y (n_2384));
  XNOR2xp5_ASAP7_75t_SL g5015(.A (n_5885), .B (n_2516), .Y (n_2386));
  XNOR2xp5_ASAP7_75t_SL g5016(.A (n_289), .B (n_2279), .Y (n_2387));
  XNOR2xp5_ASAP7_75t_SL g5018(.A (n_2464), .B (n_7191), .Y (n_2389));
  XNOR2xp5_ASAP7_75t_SL g5019(.A (n_2741), .B (n_7202), .Y (n_2390));
  XNOR2xp5_ASAP7_75t_SL g5044(.A (n_2419), .B (n_2420), .Y (n_2421));
  NOR2xp33_ASAP7_75t_SL g5045(.A (n_2541), .B (n_206), .Y (n_2419));
  OAI21xp5_ASAP7_75t_SL g5046(.A1 (n_7207), .A2 (add_8_11_n_2784), .B
       (n_2793), .Y (n_2420));
  NAND2xp33_ASAP7_75t_R add_8_11_g3284__5055(.A (n_281), .B
       (add_8_11_n_2966), .Y (n_2432));
  INVxp67_ASAP7_75t_SL fopt5058(.A (n_2476), .Y (n_2439));
  NAND2xp5_ASAP7_75t_SL g5060(.A (iB[0]), .B (iA[0]), .Y (n_2436));
  NAND2xp5_ASAP7_75t_SL g5061(.A (iA[1]), .B (iB[1]), .Y (n_2437));
  AOI21xp5_ASAP7_75t_SL g5076(.A1 (iA[5]), .A2 (iB[5]), .B (n_7283), .Y
       (n_2464));
  XNOR2xp5_ASAP7_75t_SL g5085(.A (n_2432), .B (n_7207), .Y (n_2475));
  XNOR2xp5_ASAP7_75t_SL g47(.A (n_2479), .B (n_2476), .Y (n_2480));
  OAI21xp5_ASAP7_75t_SL g49(.A1 (n_4401), .A2 (n_2436), .B (n_2437), .Y
       (n_2476));
  NOR2x1_ASAP7_75t_SL g48(.A (n_2533), .B (n_2478), .Y (n_2479));
  INVx1_ASAP7_75t_SL g51(.A (n_348), .Y (n_2478));
  XNOR2xp5_ASAP7_75t_SL g5086(.A (n_2481), .B (n_2482), .Y (n_2483));
  XOR2xp5_ASAP7_75t_SL g68(.A (iA[31]), .B (iB[31]), .Y (n_2481));
  OAI21xp5_ASAP7_75t_SL g67(.A1 (n_2775), .A2 (n_7197), .B (n_7322), .Y
       (n_2482));
  XNOR2xp5_ASAP7_75t_SL g5087(.A (n_2559), .B (n_2485), .Y (n_2486));
  OAI21xp5_ASAP7_75t_SL g5088(.A1 (add_8_11_n_2742), .A2 (n_7197), .B
       (n_7320), .Y (n_2485));
  XNOR2xp5_ASAP7_75t_SL g5090(.A (n_223), .B (add_8_11_n_2689), .Y
       (n_2490));
  INVx1_ASAP7_75t_SL g5103(.A (n_7283), .Y (n_2503));
  OAI21xp33_ASAP7_75t_SL g5104(.A1 (n_2539), .A2 (n_148), .B (n_2506),
       .Y (n_2507));
  INVxp33_ASAP7_75t_SL g5106(.A (n_2668), .Y (n_2506));
  INVx1_ASAP7_75t_SL g33(.A (n_148), .Y (n_2508));
  AOI21xp5_ASAP7_75t_SL g5110(.A1 (n_4428), .A2 (n_2514), .B (n_2515),
       .Y (n_2516));
  NOR3xp33_ASAP7_75t_SL g5112(.A (n_2852), .B (n_7283), .C (n_2253), .Y
       (n_2514));
  OAI21xp5_ASAP7_75t_SL g5113(.A1 (n_2852), .A2 (n_4482), .B (n_646),
       .Y (n_2515));
  XNOR2xp5_ASAP7_75t_SL g135(.A (n_2520), .B (n_4400), .Y (n_2522));
  AND2x2_ASAP7_75t_SL g137(.A (iA[0]), .B (iB[0]), .Y (n_2520));
  NOR2x1p5_ASAP7_75t_SL g5118(.A (iA[25]), .B (iB[25]), .Y (n_430));
  NOR2x1p5_ASAP7_75t_L g5124(.A (iA[13]), .B (iB[13]), .Y (n_2531));
  NOR2x1p5_ASAP7_75t_L g5126(.A (iA[2]), .B (iB[2]), .Y (n_2533));
  AND2x2_ASAP7_75t_SL g5129(.A (n_3258), .B (iB[12]), .Y (n_2536));
  AND2x2_ASAP7_75t_SL g5131(.A (iA[13]), .B (iB[13]), .Y (n_2538));
  OAI22xp5_ASAP7_75t_SL g5132(.A1 (n_2998), .A2 (n_3026), .B1 (n_3385),
       .B2 (n_3363), .Y (n_2539));
  AND2x2_ASAP7_75t_SL g5134(.A (n_2855), .B (n_803), .Y (n_2541));
  AND2x2_ASAP7_75t_SL g5136(.A (n_1116), .B (n_1095), .Y (n_2543));
  OR2x2_ASAP7_75t_SL g5139(.A (n_2855), .B (n_803), .Y (n_2546));
  OR2x2_ASAP7_75t_SL g5140(.A (n_1095), .B (n_1116), .Y (n_2547));
  OA22x2_ASAP7_75t_SL g5144(.A1 (iB[27]), .A2 (iA[27]), .B1 (iA[26]),
       .B2 (iB[26]), .Y (n_2551));
  NOR3xp33_ASAP7_75t_SL g5146(.A (n_494), .B (n_287), .C (n_2531), .Y
       (n_2553));
  NOR3xp33_ASAP7_75t_SL g5148(.A (n_191), .B (add_8_11_n_3057), .C
       (n_430), .Y (n_2555));
  HAxp5_ASAP7_75t_SL g5150(.A (iA[29]), .B (iB[29]), .CON (n_2557), .SN
       (n_2558));
  INVxp67_ASAP7_75t_SL g3(.A (n_2558), .Y (n_2559));
  INVx2_ASAP7_75t_SL g5154(.A (iB[23]), .Y (n_2565));
  INVx1_ASAP7_75t_SL g5155(.A (iA[23]), .Y (n_2566));
  INVx2_ASAP7_75t_SL g86(.A (iB[22]), .Y (n_2567));
  INVx1_ASAP7_75t_SL g88(.A (iA[22]), .Y (n_2568));
  NOR2x1_ASAP7_75t_SL g81(.A (n_3363), .B (n_3385), .Y (n_2571));
  OAI21x1_ASAP7_75t_SL g109(.A1 (n_2572), .A2 (n_2573), .B (n_4557), .Y
       (n_2575));
  NAND2x1p5_ASAP7_75t_SL g113(.A (iA[18]), .B (iB[18]), .Y (n_2572));
  NOR2x1_ASAP7_75t_SL g110(.A (iB[19]), .B (iA[19]), .Y (n_2573));
  NOR2x1p5_ASAP7_75t_SL g141(.A (n_2579), .B (n_2582), .Y (n_2583));
  OR2x2_ASAP7_75t_SL g142(.A (n_2577), .B (n_2578), .Y (n_2579));
  OAI22xp5_ASAP7_75t_SL g145(.A1 (iA[17]), .A2 (iB[17]), .B1 (iA[16]),
       .B2 (iB[16]), .Y (n_2577));
  OAI22x1_ASAP7_75t_SL g147(.A1 (iA[19]), .A2 (iB[19]), .B1 (iA[18]),
       .B2 (iB[18]), .Y (n_2578));
  NAND2x1p5_ASAP7_75t_SL g143(.A (n_2581), .B (n_7323), .Y (n_2582));
  AOI22x1_ASAP7_75t_SL g148(.A1 (n_2568), .A2 (n_2567), .B1 (n_2566),
       .B2 (n_2565), .Y (n_2581));
  INVxp67_ASAP7_75t_SL g144(.A (n_2577), .Y (n_2584));
  INVx1_ASAP7_75t_SL g146(.A (n_2578), .Y (n_2585));
  NOR2x2_ASAP7_75t_SL g537(.A (iA[7]), .B (iB[7]), .Y (n_2586));
  NOR2x1p5_ASAP7_75t_SL g541(.A (iA[6]), .B (iB[6]), .Y (n_2587));
  NAND2x1p5_ASAP7_75t_SL g536(.A (iB[4]), .B (iA[4]), .Y (n_2590));
  NAND2x1p5_ASAP7_75t_SL g538(.A (iB[5]), .B (iA[5]), .Y (n_2591));
  NAND2x1p5_ASAP7_75t_L g542(.A (iB[6]), .B (iA[6]), .Y (n_2593));
  INVx1_ASAP7_75t_SL g1344(.A (n_2625), .Y (n_2626));
  OAI22x1_ASAP7_75t_L g1345(.A1 (iA[7]), .A2 (iB[7]), .B1 (iA[6]), .B2
       (iB[6]), .Y (n_2625));
  NOR2x1_ASAP7_75t_SL g1349(.A (n_2587), .B (n_2586), .Y (n_2634));
  OAI21x1_ASAP7_75t_SL g108(.A1 (n_2642), .A2 (n_2643), .B (n_2644), .Y
       (n_2645));
  NOR2x1p5_ASAP7_75t_SL g5158(.A (iA[17]), .B (iB[17]), .Y (n_2642));
  NAND2x1p5_ASAP7_75t_SL g5159(.A (iA[16]), .B (iB[16]), .Y (n_2643));
  NAND2x1_ASAP7_75t_SL g5160(.A (iB[17]), .B (iA[17]), .Y (n_2644));
  AOI21x1_ASAP7_75t_SL g803(.A1 (n_7281), .A2 (n_2634), .B (n_4611), .Y
       (n_2648));
  AOI22x1_ASAP7_75t_SL g806(.A1 (n_660), .A2 (n_661), .B1 (n_662), .B2
       (n_663), .Y (n_2651));
  OAI21x1_ASAP7_75t_SL g5165(.A1 (n_2665), .A2 (n_2666), .B (n_2667),
       .Y (n_2668));
  NAND2x1p5_ASAP7_75t_SL g112(.A (iA[20]), .B (iB[20]), .Y (n_2665));
  NOR2x1_ASAP7_75t_SL g5166(.A (iB[21]), .B (iA[21]), .Y (n_2666));
  NAND2x1p5_ASAP7_75t_L g5167(.A (iA[21]), .B (iB[21]), .Y (n_2667));
  NOR2x1p5_ASAP7_75t_SL g5182(.A (iA[10]), .B (iB[10]), .Y (n_2700));
  NAND2xp33_ASAP7_75t_SL g463(.A (n_2583), .B (n_2710), .Y (n_2711));
  NOR4xp25_ASAP7_75t_SL g469(.A (n_432), .B (n_2709), .C
       (add_8_11_n_3057), .D (n_430), .Y (n_2710));
  OR2x2_ASAP7_75t_SL g476(.A (n_423), .B (n_456), .Y (n_2709));
  OAI21xp5_ASAP7_75t_SL g467(.A1 (n_2709), .A2 (n_2712), .B (n_2714),
       .Y (n_2715));
  AOI21x1_ASAP7_75t_SL g473(.A1 (n_716), .A2 (n_2551), .B (n_464), .Y
       (n_2712));
  INVxp67_ASAP7_75t_SL g470(.A (n_2713), .Y (n_2714));
  OAI21xp5_ASAP7_75t_SL g471(.A1 (n_456), .A2 (n_467), .B (n_2557), .Y
       (n_2713));
  INVxp67_ASAP7_75t_SL g472(.A (n_2712), .Y (n_2718));
  OAI21xp5_ASAP7_75t_SL g465(.A1 (n_423), .A2 (n_2712), .B (n_467), .Y
       (n_2720));
  AOI22xp33_ASAP7_75t_SL g468(.A1 (n_466), .A2 (n_2713), .B1 (n_1592),
       .B2 (n_1759), .Y (n_2721));
  INVxp67_ASAP7_75t_SRAM g478(.A (add_8_11_n_3057), .Y (n_2723));
  INVx1_ASAP7_75t_SL g477(.A (n_714), .Y (add_8_11_n_3041));
  NOR2x1_ASAP7_75t_SL g198(.A (n_2700), .B (n_2726), .Y (n_2727));
  NOR2x1p5_ASAP7_75t_L g201(.A (iA[11]), .B (iB[11]), .Y (n_2726));
  INVx1_ASAP7_75t_SL g5189(.A (iB[10]), .Y (n_2736));
  INVx1_ASAP7_75t_SL g5190(.A (iA[10]), .Y (n_2737));
  NOR2x1_ASAP7_75t_SL g5191(.A (iA[11]), .B (iB[11]), .Y (n_2738));
  XOR2xp5_ASAP7_75t_SL g80(.A (iB[11]), .B (iA[11]), .Y (n_2741));
  INVx1_ASAP7_75t_SL g5194(.A (n_511), .Y (n_2747));
  OAI21x1_ASAP7_75t_SL g153(.A1 (n_2755), .A2 (n_2756), .B (n_2757), .Y
       (n_2758));
  NAND2x1p5_ASAP7_75t_SL g154(.A (iA[10]), .B (iB[10]), .Y (n_2755));
  NOR2x1p5_ASAP7_75t_L g156(.A (iB[11]), .B (iA[11]), .Y (n_2756));
  NAND2x1p5_ASAP7_75t_SL g155(.A (iA[11]), .B (iB[11]), .Y (n_2757));
  INVx3_ASAP7_75t_SL g106(.A (iB[14]), .Y (n_2763));
  NOR2xp33_ASAP7_75t_SL g5200(.A (n_2769), .B (n_2770), .Y (n_2771));
  INVxp67_ASAP7_75t_SL g93(.A (n_2768), .Y (n_2769));
  NOR3xp33_ASAP7_75t_SL g94(.A (n_456), .B (n_455), .C (n_423), .Y
       (n_2768));
  NAND2xp5_ASAP7_75t_SL g97(.A (n_2551), .B (n_157), .Y (n_2770));
  OAI21xp5_ASAP7_75t_SL g5201(.A1 (n_2769), .A2 (n_2712), .B (n_2721),
       .Y (n_2772));
  NAND3xp33_ASAP7_75t_SL g5202(.A (n_2774), .B (n_2583), .C (n_2768),
       .Y (n_2775));
  INVx1_ASAP7_75t_SL g96(.A (n_2770), .Y (n_2774));
  NOR2xp33_ASAP7_75t_SL g92(.A (n_423), .B (n_2770), .Y (n_2776));
  OAI21xp5_ASAP7_75t_SL g801(.A1 (n_5936), .A2 (n_2786), .B (n_2789),
       .Y (n_2790));
  NAND2x1p5_ASAP7_75t_SL g5206(.A (n_2851), .B (n_2651), .Y (n_2786));
  AOI21xp5_ASAP7_75t_SL g5207(.A1 (n_2787), .A2 (n_2851), .B (n_2849),
       .Y (n_2789));
  OAI21x1_ASAP7_75t_SL g807(.A1 (n_500), .A2 (n_2531), .B (n_502), .Y
       (n_2787));
  AO21x1_ASAP7_75t_SL g802(.A1 (n_2791), .A2 (n_2546), .B (n_2541), .Y
       (n_2792));
  HB1xp67_ASAP7_75t_SL g5208(.A (n_2787), .Y (n_2791));
  AOI21xp33_ASAP7_75t_SL g805(.A1 (n_2808), .A2 (n_181), .B (n_2791),
       .Y (n_2793));
  XNOR2xp5_ASAP7_75t_SL g5209(.A (n_2794), .B (n_2795), .Y (n_2796));
  AND2x2_ASAP7_75t_SL g5210(.A (n_466), .B (n_472), .Y (n_2794));
  OAI21xp5_ASAP7_75t_SL g5211(.A1 (n_2711), .A2 (n_7197), .B (n_7317),
       .Y (n_2795));
  OAI22x1_ASAP7_75t_SL g64(.A1 (iA[8]), .A2 (iB[8]), .B1 (iA[9]), .B2
       (iB[9]), .Y (n_2798));
  AOI21x1_ASAP7_75t_SL g5213(.A1 (n_4504), .A2 (n_7188), .B (n_2790),
       .Y (n_2801));
  NAND2xp5_ASAP7_75t_SL g5215(.A (n_4438), .B (n_4553), .Y (n_2805));
  AOI21xp5_ASAP7_75t_SL g5216(.A1 (n_4553), .A2 (add_8_11_n_2792), .B
       (n_2507), .Y (n_2806));
  INVxp67_ASAP7_75t_SL fopt1(.A (n_2808), .Y (n_2809));
  INVx1_ASAP7_75t_SL fopt2(.A (n_2811), .Y (n_2808));
  HB1xp67_ASAP7_75t_SL fopt3(.A (n_5936), .Y (n_2811));
  INVx2_ASAP7_75t_SL g54(.A (iA[15]), .Y (n_2845));
  OAI21x1_ASAP7_75t_SL g5244(.A1 (n_508), .A2 (n_316), .B (n_2848), .Y
       (n_2849));
  NAND2x1p5_ASAP7_75t_SL g5245(.A (iA[15]), .B (iB[15]), .Y (n_2848));
  AOI22x1_ASAP7_75t_SL g5246(.A1 (n_2845), .A2 (n_2850), .B1 (n_2763),
       .B2 (n_2854), .Y (n_2851));
  INVx3_ASAP7_75t_SL g5247(.A (iB[15]), .Y (n_2850));
  HB1xp67_ASAP7_75t_SL fopt5248(.A (n_2587), .Y (n_2852));
  INVx4_ASAP7_75t_SL fopt5249(.A (iA[14]), .Y (n_2854));
  HB1xp67_ASAP7_75t_SL fopt5250(.A (iA[14]), .Y (n_2855));
  NAND2x1p5_ASAP7_75t_L g830(.A (iB[2]), .B (iA[2]), .Y (n_2894));
  NOR2x1p5_ASAP7_75t_SL g831(.A (iA[3]), .B (iB[3]), .Y (n_2895));
  NAND2x1p5_ASAP7_75t_SL g832(.A (iB[3]), .B (iA[3]), .Y (n_2896));
  HB1xp67_ASAP7_75t_SL fopt5352(.A (iB[21]), .Y (n_2998));
  HB1xp67_ASAP7_75t_SL fopt5377(.A (iA[21]), .Y (n_3026));
  HB1xp67_ASAP7_75t_SL fopt5413(.A (iB[10]), .Y (n_3070));
  HB1xp67_ASAP7_75t_SL fopt5469(.A (iA[10]), .Y (n_3136));
  HB1xp67_ASAP7_75t_SL fopt5576(.A (iA[12]), .Y (n_3258));
  HB1xp67_ASAP7_75t_SL fopt5669(.A (iB[20]), .Y (n_3363));
  HB1xp67_ASAP7_75t_SL fopt5688(.A (iA[20]), .Y (n_3385));
  HB1xp67_ASAP7_75t_SL fopt5757(.A (iB[8]), .Y (n_3464));
  BUFx3_ASAP7_75t_SL fopt5776(.A (iA[4]), .Y (n_3485));
  XOR2x1_ASAP7_75t_SL g6580(.A (iA[1]), .B (iB[1]), .Y (n_4400));
  NOR2x1_ASAP7_75t_SL g6581(.A (iA[1]), .B (iB[1]), .Y (n_4401));
  INVxp67_ASAP7_75t_SL fopt6602(.A (n_7189), .Y (n_4428));
  XNOR2xp5_ASAP7_75t_SL g6605(.A (n_4493), .B (n_7189), .Y (n_4429));
  INVxp67_ASAP7_75t_SL add_8_11_g6612(.A (n_4437), .Y (n_4438));
  NOR2x1_ASAP7_75t_SL add_8_11_g3313__6613(.A (n_7990), .B (n_7725), .Y
       (n_4437));
  OAI21xp5_ASAP7_75t_SL g31(.A1 (n_4481), .A2 (n_7189), .B (n_4482), .Y
       (n_4483));
  NAND2xp5_ASAP7_75t_SL g6639(.A (n_4491), .B (n_2503), .Y (n_4481));
  OA21x2_ASAP7_75t_SL g32(.A1 (n_2590), .A2 (n_7283), .B (n_2591), .Y
       (n_4482));
  NAND2xp5_ASAP7_75t_SL g16(.A (n_4492), .B (n_4491), .Y (n_4493));
  INVxp67_ASAP7_75t_SL g6646(.A (n_2253), .Y (n_4491));
  NAND2xp5_ASAP7_75t_SL g17(.A (iB[4]), .B (n_3485), .Y (n_4492));
  INVx2_ASAP7_75t_SL fopt6650(.A (n_2798), .Y (n_4498));
  INVxp67_ASAP7_75t_SL fopt6651(.A (n_4501), .Y (n_4502));
  HB1xp67_ASAP7_75t_SL fopt6652(.A (n_4500), .Y (n_4501));
  NAND2xp5_ASAP7_75t_SL g6653(.A (n_4499), .B (n_4498), .Y (n_4500));
  AOI21xp5_ASAP7_75t_SL g6654(.A1 (n_2736), .A2 (n_2737), .B (n_2738),
       .Y (n_4499));
  HB1xp67_ASAP7_75t_SL fopt6655(.A (n_4500), .Y (n_4503));
  NOR2xp67_ASAP7_75t_SL g6656(.A (n_2786), .B (n_4500), .Y (n_4504));
  OAI22x1_ASAP7_75t_SL g240(.A1 (iB[3]), .A2 (iA[3]), .B1 (iA[2]), .B2
       (iB[2]), .Y (n_4547));
  XNOR2xp5_ASAP7_75t_SL g24(.A (n_4552), .B (n_4554), .Y (n_4555));
  OAI21xp5_ASAP7_75t_SL g6690(.A1 (n_7990), .A2 (n_7725), .B (n_2643),
       .Y (n_4552));
  INVxp67_ASAP7_75t_SL fopt6691(.A (n_4553), .Y (n_4554));
  INVxp67_ASAP7_75t_SL fopt29(.A (n_2801), .Y (n_4553));
  NAND2x1p5_ASAP7_75t_SL g6693(.A (iA[19]), .B (iB[19]), .Y (n_4557));
  AND2x2_ASAP7_75t_SL g6694(.A (n_3070), .B (n_3136), .Y (n_4558));
  XOR2xp5_ASAP7_75t_SL g6697(.A (iB[9]), .B (iA[9]), .Y (n_4561));
  XOR2xp5_ASAP7_75t_SL g6700(.A (iA[3]), .B (iB[3]), .Y (n_4564));
  XOR2x2_ASAP7_75t_R g6701(.A (n_3026), .B (n_2998), .Y (n_4565));
  OAI21x1_ASAP7_75t_SL g6743(.A1 (n_2586), .A2 (n_2593), .B (n_4610),
       .Y (n_4611));
  NAND2x1p5_ASAP7_75t_SL g540_dup(.A (iB[7]), .B (iA[7]), .Y (n_4610));
  INVx1_ASAP7_75t_SL fopt6797(.A (n_4673), .Y (n_4671));
  INVxp67_ASAP7_75t_SL fopt6798(.A (iB[7]), .Y (n_4673));
  INVx1_ASAP7_75t_SL fopt6835(.A (n_4718), .Y (n_4716));
  INVxp67_ASAP7_75t_SL fopt6836(.A (iA[7]), .Y (n_4718));
  HB1xp67_ASAP7_75t_SL fopt6930(.A (iA[8]), .Y (n_4825));
  XNOR2x1_ASAP7_75t_SL g7862(.A (n_4716), .B (n_4671), .Y (n_5885));
  AOI21x1_ASAP7_75t_SL g7906(.A1 (n_5935), .A2 (n_2727), .B (n_2758),
       .Y (n_5936));
  OAI21x1_ASAP7_75t_SL g213(.A1 (n_5932), .A2 (n_5933), .B (n_5934), .Y
       (n_5935));
  NAND2x1p5_ASAP7_75t_SL g214(.A (iB[8]), .B (iA[8]), .Y (n_5932));
  NOR2x1p5_ASAP7_75t_SL g216(.A (iB[9]), .B (iA[9]), .Y (n_5933));
  NAND2x1p5_ASAP7_75t_SL g215(.A (iA[9]), .B (iB[9]), .Y (n_5934));
  AOI21xp5_ASAP7_75t_SL g7907(.A1 (n_2747), .A2 (n_5937), .B (n_4558),
       .Y (n_5938));
  HB1xp67_ASAP7_75t_SL g212(.A (n_5935), .Y (n_5937));
  INVxp67_ASAP7_75t_SL g211(.A (n_5937), .Y (n_5939));
  OAI21x1_ASAP7_75t_SL g8970(.A1 (n_7268), .A2 (n_7187), .B (n_2648),
       .Y (n_7188));
  AOI21x1_ASAP7_75t_SL g8971(.A1 (n_7184), .A2 (n_7185), .B (n_7186),
       .Y (n_7187));
  INVx1_ASAP7_75t_SL g8972(.A (n_4547), .Y (n_7184));
  AOI21x1_ASAP7_75t_SL g8973(.A1 (n_685), .A2 (n_686), .B (n_687), .Y
       (n_7185));
  OAI21x1_ASAP7_75t_SL g8974(.A1 (n_2894), .A2 (n_2895), .B (n_2896),
       .Y (n_7186));
  HB1xp67_ASAP7_75t_SL fopt8975(.A (n_7187), .Y (n_7189));
  OAI21xp33_ASAP7_75t_SL g8977(.A1 (n_7187), .A2 (n_2253), .B (n_4492),
       .Y (n_7191));
  OAI21xp5_ASAP7_75t_SL g8978(.A1 (n_2264), .A2 (n_7207), .B (n_5939),
       .Y (n_7193));
  OAI21xp5_ASAP7_75t_SL g8982(.A1 (n_7196), .A2 (n_7197), .B (n_7198),
       .Y (n_7199));
  BUFx3_ASAP7_75t_SL fopt21(.A (n_2579), .Y (n_7196));
  BUFx6f_ASAP7_75t_SL fopt22(.A (n_2801), .Y (n_7197));
  INVx1_ASAP7_75t_SL g20(.A (n_2508), .Y (n_7198));
  OAI21xp5_ASAP7_75t_SL g26(.A1 (add_8_11_n_2812), .A2 (n_7207), .B
       (n_5938), .Y (n_7202));
  OAI21xp5_ASAP7_75t_SL g8985(.A1 (n_227), .A2 (n_7207), .B (n_281), .Y
       (n_7208));
  OA21x2_ASAP7_75t_SL g34(.A1 (n_7187), .A2 (n_7268), .B (n_2648), .Y
       (n_7207));
  NOR2xp33_ASAP7_75t_SL g39(.A (n_7223), .B (n_7294), .Y (n_7225));
  AOI21xp33_ASAP7_75t_SL g40(.A1 (n_2643), .A2 (n_2805), .B
       (add_8_11_n_2916), .Y (n_7223));
  NAND2x1_ASAP7_75t_SL g13(.A (n_7280), .B (n_2626), .Y (n_7268));
  NOR2x1_ASAP7_75t_SL g9043(.A (n_668), .B (n_7279), .Y (n_7280));
  NOR2x2_ASAP7_75t_SL g9044(.A (iA[5]), .B (iB[5]), .Y (n_7279));
  OAI21x1_ASAP7_75t_SL g9045(.A1 (n_2590), .A2 (n_7279), .B (n_2591),
       .Y (n_7281));
  HB1xp67_ASAP7_75t_SL fopt9046(.A (n_7282), .Y (n_7283));
  NOR2x1p5_ASAP7_75t_L g539_dup(.A (iA[5]), .B (iB[5]), .Y (n_7282));
  AOI21xp5_ASAP7_75t_SL g9050(.A1 (n_7292), .A2 (n_7291), .B (n_7293),
       .Y (n_7294));
  INVxp67_ASAP7_75t_SL fopt(.A (n_7197), .Y (n_7291));
  INVx1_ASAP7_75t_SL g9051(.A (n_4437), .Y (n_7292));
  INVx1_ASAP7_75t_SL g36(.A (add_8_11_n_2815), .Y (n_7293));
  INVxp67_ASAP7_75t_SL fopt9065(.A (n_7313), .Y (n_7314));
  AO21x2_ASAP7_75t_SL g9066(.A1 (n_7310), .A2 (n_7311), .B (n_7312), .Y
       (n_7313));
  INVx1_ASAP7_75t_SL fopt9067(.A (n_2582), .Y (n_7310));
  OAI21x1_ASAP7_75t_SL g9068(.A1 (n_696), .A2 (n_698), .B (n_700), .Y
       (n_7311));
  AO21x1_ASAP7_75t_SL g9069(.A1 (n_2581), .A2 (n_2668), .B (n_703), .Y
       (n_7312));
  AOI21xp5_ASAP7_75t_SL g9070(.A1 (n_7313), .A2 (n_2723), .B
       (add_8_11_n_3041), .Y (n_7315));
  AOI21xp5_ASAP7_75t_SL g9071(.A1 (n_7313), .A2 (n_2774), .B (n_2718),
       .Y (n_7316));
  AOI21xp5_ASAP7_75t_SL g9072(.A1 (n_7313), .A2 (n_2710), .B (n_2715),
       .Y (n_7317));
  AOI21xp5_ASAP7_75t_SL add_8_11_g3125__9073(.A1 (n_7318), .A2 (n_157),
       .B (n_716), .Y (n_7319));
  AO21x2_ASAP7_75t_SL g18_dup(.A1 (n_7310), .A2 (n_7311), .B (n_7312),
       .Y (n_7318));
  AOI21xp5_ASAP7_75t_SL add_8_11_g3135__9074(.A1 (n_7318), .A2
       (n_2776), .B (n_2720), .Y (n_7320));
  AOI21xp5_ASAP7_75t_SL g9075(.A1 (n_7318), .A2 (n_2555), .B (n_719),
       .Y (n_7321));
  AOI21xp5_ASAP7_75t_SL g9076(.A1 (n_7318), .A2 (n_2771), .B (n_2772),
       .Y (n_7322));
  OA22x2_ASAP7_75t_SL g9077(.A1 (iA[21]), .A2 (iB[21]), .B1 (iB[20]),
       .B2 (iA[20]), .Y (n_7323));
  HB1xp67_ASAP7_75t_SL fopt9427(.A (iA[16]), .Y (n_7725));
  HB1xp67_ASAP7_75t_SL fopt9660(.A (iB[16]), .Y (n_7990));
endmodule

