###############################################################
#  Generated by:      Cadence Innovus 22.17-s086_1
#  OS:                Linux x86_64(Host ID vlsiktmt)
#  Generated on:      Fri Apr  3 19:26:21 2026
#  Design:            Adder32
#  Command:           create_ccopt_clock_tree_spec -filename ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin iClk true

# Clocks present at pin iClk
#   CLK (period 10.0ps) in timing_config constraint_typical([outputs/synthesis.sdc])
create_ccopt_clock_tree -name CLK -source iClk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -early -clock_tree CLK 0.5
set_ccopt_property target_max_trans_sdc -delay_corner delay_corner_typical -late -clock_tree CLK 1.0
# Clock period setting for source pin of CLK
set_ccopt_property clock_period -pin iClk 10

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:CLK in timing_config:constraint_typical (sdc outputs/synthesis.sdc)
create_ccopt_skew_group -name CLK/constraint_typical -sources iClk -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK/constraint_typical true
set_ccopt_property extracted_from_clock_name -skew_group CLK/constraint_typical CLK
set_ccopt_property extracted_from_constraint_mode_names -skew_group CLK/constraint_typical {constraint_typical  }
set_ccopt_property extracted_from_delay_corners -skew_group CLK/constraint_typical delay_corner_typical


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

